// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: executor.proto

package server

import (
	"context"

	"github.com/Humphrey-He/star-flow-scheduler/apps/executor/rpc/internal/logic/executorregistryservice"
	"github.com/Humphrey-He/star-flow-scheduler/apps/executor/rpc/internal/svc"
	"github.com/Humphrey-He/star-flow-scheduler/proto/pb/github.com/Humphrey-He/star-flow-scheduler/proto/schedulerv1"
)

type ExecutorRegistryServiceServer struct {
	svcCtx *svc.ServiceContext
	schedulerv1_schedulev1.UnimplementedExecutorRegistryServiceServer
}

func NewExecutorRegistryServiceServer(svcCtx *svc.ServiceContext) *ExecutorRegistryServiceServer {
	return &ExecutorRegistryServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ExecutorRegistryServiceServer) RegisterExecutor(ctx context.Context, in *schedulerv1_schedulev1.RegisterExecutorRequest) (*schedulerv1_schedulev1.RegisterExecutorResponse, error) {
	l := executorregistryservicelogic.NewRegisterExecutorLogic(ctx, s.svcCtx)
	return l.RegisterExecutor(in)
}

func (s *ExecutorRegistryServiceServer) Heartbeat(ctx context.Context, in *schedulerv1_schedulev1.HeartbeatRequest) (*schedulerv1_schedulev1.HeartbeatResponse, error) {
	l := executorregistryservicelogic.NewHeartbeatLogic(ctx, s.svcCtx)
	return l.Heartbeat(in)
}
