// Code generated by ent, DO NOT EDIT.

package jobinstance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldDeletedAt, v))
}

// InstanceNo applies equality check predicate on the "instance_no" field. It's identical to InstanceNoEQ.
func InstanceNo(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldInstanceNo, v))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldJobID, v))
}

// WorkflowID applies equality check predicate on the "workflow_id" field. It's identical to WorkflowIDEQ.
func WorkflowID(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldWorkflowID, v))
}

// TriggerType applies equality check predicate on the "trigger_type" field. It's identical to TriggerTypeEQ.
func TriggerType(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldTriggerType, v))
}

// TriggerTime applies equality check predicate on the "trigger_time" field. It's identical to TriggerTimeEQ.
func TriggerTime(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldTriggerTime, v))
}

// ScheduledTime applies equality check predicate on the "scheduled_time" field. It's identical to ScheduledTimeEQ.
func ScheduledTime(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldScheduledTime, v))
}

// DispatchTime applies equality check predicate on the "dispatch_time" field. It's identical to DispatchTimeEQ.
func DispatchTime(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldDispatchTime, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldStartTime, v))
}

// FinishTime applies equality check predicate on the "finish_time" field. It's identical to FinishTimeEQ.
func FinishTime(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldFinishTime, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldStatus, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldRetryCount, v))
}

// CurrentBackoffMs applies equality check predicate on the "current_backoff_ms" field. It's identical to CurrentBackoffMsEQ.
func CurrentBackoffMs(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldCurrentBackoffMs, v))
}

// ExecutorID applies equality check predicate on the "executor_id" field. It's identical to ExecutorIDEQ.
func ExecutorID(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldExecutorID, v))
}

// ShardTotal applies equality check predicate on the "shard_total" field. It's identical to ShardTotalEQ.
func ShardTotal(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldShardTotal, v))
}

// SuccessShards applies equality check predicate on the "success_shards" field. It's identical to SuccessShardsEQ.
func SuccessShards(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldSuccessShards, v))
}

// FailedShards applies equality check predicate on the "failed_shards" field. It's identical to FailedShardsEQ.
func FailedShards(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldFailedShards, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldPayload, v))
}

// ResultSummary applies equality check predicate on the "result_summary" field. It's identical to ResultSummaryEQ.
func ResultSummary(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldResultSummary, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotNull(FieldDeletedAt))
}

// InstanceNoEQ applies the EQ predicate on the "instance_no" field.
func InstanceNoEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldInstanceNo, v))
}

// InstanceNoNEQ applies the NEQ predicate on the "instance_no" field.
func InstanceNoNEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldInstanceNo, v))
}

// InstanceNoIn applies the In predicate on the "instance_no" field.
func InstanceNoIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldInstanceNo, vs...))
}

// InstanceNoNotIn applies the NotIn predicate on the "instance_no" field.
func InstanceNoNotIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldInstanceNo, vs...))
}

// InstanceNoGT applies the GT predicate on the "instance_no" field.
func InstanceNoGT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldInstanceNo, v))
}

// InstanceNoGTE applies the GTE predicate on the "instance_no" field.
func InstanceNoGTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldInstanceNo, v))
}

// InstanceNoLT applies the LT predicate on the "instance_no" field.
func InstanceNoLT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldInstanceNo, v))
}

// InstanceNoLTE applies the LTE predicate on the "instance_no" field.
func InstanceNoLTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldInstanceNo, v))
}

// InstanceNoContains applies the Contains predicate on the "instance_no" field.
func InstanceNoContains(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContains(FieldInstanceNo, v))
}

// InstanceNoHasPrefix applies the HasPrefix predicate on the "instance_no" field.
func InstanceNoHasPrefix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasPrefix(FieldInstanceNo, v))
}

// InstanceNoHasSuffix applies the HasSuffix predicate on the "instance_no" field.
func InstanceNoHasSuffix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasSuffix(FieldInstanceNo, v))
}

// InstanceNoEqualFold applies the EqualFold predicate on the "instance_no" field.
func InstanceNoEqualFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEqualFold(FieldInstanceNo, v))
}

// InstanceNoContainsFold applies the ContainsFold predicate on the "instance_no" field.
func InstanceNoContainsFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContainsFold(FieldInstanceNo, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldJobID, v))
}

// WorkflowIDEQ applies the EQ predicate on the "workflow_id" field.
func WorkflowIDEQ(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldWorkflowID, v))
}

// WorkflowIDNEQ applies the NEQ predicate on the "workflow_id" field.
func WorkflowIDNEQ(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldWorkflowID, v))
}

// WorkflowIDIn applies the In predicate on the "workflow_id" field.
func WorkflowIDIn(vs ...int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldWorkflowID, vs...))
}

// WorkflowIDNotIn applies the NotIn predicate on the "workflow_id" field.
func WorkflowIDNotIn(vs ...int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldWorkflowID, vs...))
}

// WorkflowIDGT applies the GT predicate on the "workflow_id" field.
func WorkflowIDGT(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldWorkflowID, v))
}

// WorkflowIDGTE applies the GTE predicate on the "workflow_id" field.
func WorkflowIDGTE(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldWorkflowID, v))
}

// WorkflowIDLT applies the LT predicate on the "workflow_id" field.
func WorkflowIDLT(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldWorkflowID, v))
}

// WorkflowIDLTE applies the LTE predicate on the "workflow_id" field.
func WorkflowIDLTE(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldWorkflowID, v))
}

// WorkflowIDIsNil applies the IsNil predicate on the "workflow_id" field.
func WorkflowIDIsNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIsNull(FieldWorkflowID))
}

// WorkflowIDNotNil applies the NotNil predicate on the "workflow_id" field.
func WorkflowIDNotNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotNull(FieldWorkflowID))
}

// TriggerTypeEQ applies the EQ predicate on the "trigger_type" field.
func TriggerTypeEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldTriggerType, v))
}

// TriggerTypeNEQ applies the NEQ predicate on the "trigger_type" field.
func TriggerTypeNEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldTriggerType, v))
}

// TriggerTypeIn applies the In predicate on the "trigger_type" field.
func TriggerTypeIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldTriggerType, vs...))
}

// TriggerTypeNotIn applies the NotIn predicate on the "trigger_type" field.
func TriggerTypeNotIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldTriggerType, vs...))
}

// TriggerTypeGT applies the GT predicate on the "trigger_type" field.
func TriggerTypeGT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldTriggerType, v))
}

// TriggerTypeGTE applies the GTE predicate on the "trigger_type" field.
func TriggerTypeGTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldTriggerType, v))
}

// TriggerTypeLT applies the LT predicate on the "trigger_type" field.
func TriggerTypeLT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldTriggerType, v))
}

// TriggerTypeLTE applies the LTE predicate on the "trigger_type" field.
func TriggerTypeLTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldTriggerType, v))
}

// TriggerTypeContains applies the Contains predicate on the "trigger_type" field.
func TriggerTypeContains(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContains(FieldTriggerType, v))
}

// TriggerTypeHasPrefix applies the HasPrefix predicate on the "trigger_type" field.
func TriggerTypeHasPrefix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasPrefix(FieldTriggerType, v))
}

// TriggerTypeHasSuffix applies the HasSuffix predicate on the "trigger_type" field.
func TriggerTypeHasSuffix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasSuffix(FieldTriggerType, v))
}

// TriggerTypeEqualFold applies the EqualFold predicate on the "trigger_type" field.
func TriggerTypeEqualFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEqualFold(FieldTriggerType, v))
}

// TriggerTypeContainsFold applies the ContainsFold predicate on the "trigger_type" field.
func TriggerTypeContainsFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContainsFold(FieldTriggerType, v))
}

// TriggerTimeEQ applies the EQ predicate on the "trigger_time" field.
func TriggerTimeEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldTriggerTime, v))
}

// TriggerTimeNEQ applies the NEQ predicate on the "trigger_time" field.
func TriggerTimeNEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldTriggerTime, v))
}

// TriggerTimeIn applies the In predicate on the "trigger_time" field.
func TriggerTimeIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldTriggerTime, vs...))
}

// TriggerTimeNotIn applies the NotIn predicate on the "trigger_time" field.
func TriggerTimeNotIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldTriggerTime, vs...))
}

// TriggerTimeGT applies the GT predicate on the "trigger_time" field.
func TriggerTimeGT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldTriggerTime, v))
}

// TriggerTimeGTE applies the GTE predicate on the "trigger_time" field.
func TriggerTimeGTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldTriggerTime, v))
}

// TriggerTimeLT applies the LT predicate on the "trigger_time" field.
func TriggerTimeLT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldTriggerTime, v))
}

// TriggerTimeLTE applies the LTE predicate on the "trigger_time" field.
func TriggerTimeLTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldTriggerTime, v))
}

// ScheduledTimeEQ applies the EQ predicate on the "scheduled_time" field.
func ScheduledTimeEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldScheduledTime, v))
}

// ScheduledTimeNEQ applies the NEQ predicate on the "scheduled_time" field.
func ScheduledTimeNEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldScheduledTime, v))
}

// ScheduledTimeIn applies the In predicate on the "scheduled_time" field.
func ScheduledTimeIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldScheduledTime, vs...))
}

// ScheduledTimeNotIn applies the NotIn predicate on the "scheduled_time" field.
func ScheduledTimeNotIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldScheduledTime, vs...))
}

// ScheduledTimeGT applies the GT predicate on the "scheduled_time" field.
func ScheduledTimeGT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldScheduledTime, v))
}

// ScheduledTimeGTE applies the GTE predicate on the "scheduled_time" field.
func ScheduledTimeGTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldScheduledTime, v))
}

// ScheduledTimeLT applies the LT predicate on the "scheduled_time" field.
func ScheduledTimeLT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldScheduledTime, v))
}

// ScheduledTimeLTE applies the LTE predicate on the "scheduled_time" field.
func ScheduledTimeLTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldScheduledTime, v))
}

// DispatchTimeEQ applies the EQ predicate on the "dispatch_time" field.
func DispatchTimeEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldDispatchTime, v))
}

// DispatchTimeNEQ applies the NEQ predicate on the "dispatch_time" field.
func DispatchTimeNEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldDispatchTime, v))
}

// DispatchTimeIn applies the In predicate on the "dispatch_time" field.
func DispatchTimeIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldDispatchTime, vs...))
}

// DispatchTimeNotIn applies the NotIn predicate on the "dispatch_time" field.
func DispatchTimeNotIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldDispatchTime, vs...))
}

// DispatchTimeGT applies the GT predicate on the "dispatch_time" field.
func DispatchTimeGT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldDispatchTime, v))
}

// DispatchTimeGTE applies the GTE predicate on the "dispatch_time" field.
func DispatchTimeGTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldDispatchTime, v))
}

// DispatchTimeLT applies the LT predicate on the "dispatch_time" field.
func DispatchTimeLT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldDispatchTime, v))
}

// DispatchTimeLTE applies the LTE predicate on the "dispatch_time" field.
func DispatchTimeLTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldDispatchTime, v))
}

// DispatchTimeIsNil applies the IsNil predicate on the "dispatch_time" field.
func DispatchTimeIsNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIsNull(FieldDispatchTime))
}

// DispatchTimeNotNil applies the NotNil predicate on the "dispatch_time" field.
func DispatchTimeNotNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotNull(FieldDispatchTime))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldStartTime, v))
}

// StartTimeIsNil applies the IsNil predicate on the "start_time" field.
func StartTimeIsNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIsNull(FieldStartTime))
}

// StartTimeNotNil applies the NotNil predicate on the "start_time" field.
func StartTimeNotNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotNull(FieldStartTime))
}

// FinishTimeEQ applies the EQ predicate on the "finish_time" field.
func FinishTimeEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldFinishTime, v))
}

// FinishTimeNEQ applies the NEQ predicate on the "finish_time" field.
func FinishTimeNEQ(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldFinishTime, v))
}

// FinishTimeIn applies the In predicate on the "finish_time" field.
func FinishTimeIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldFinishTime, vs...))
}

// FinishTimeNotIn applies the NotIn predicate on the "finish_time" field.
func FinishTimeNotIn(vs ...time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldFinishTime, vs...))
}

// FinishTimeGT applies the GT predicate on the "finish_time" field.
func FinishTimeGT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldFinishTime, v))
}

// FinishTimeGTE applies the GTE predicate on the "finish_time" field.
func FinishTimeGTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldFinishTime, v))
}

// FinishTimeLT applies the LT predicate on the "finish_time" field.
func FinishTimeLT(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldFinishTime, v))
}

// FinishTimeLTE applies the LTE predicate on the "finish_time" field.
func FinishTimeLTE(v time.Time) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldFinishTime, v))
}

// FinishTimeIsNil applies the IsNil predicate on the "finish_time" field.
func FinishTimeIsNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIsNull(FieldFinishTime))
}

// FinishTimeNotNil applies the NotNil predicate on the "finish_time" field.
func FinishTimeNotNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotNull(FieldFinishTime))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContainsFold(FieldStatus, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldRetryCount, v))
}

// CurrentBackoffMsEQ applies the EQ predicate on the "current_backoff_ms" field.
func CurrentBackoffMsEQ(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldCurrentBackoffMs, v))
}

// CurrentBackoffMsNEQ applies the NEQ predicate on the "current_backoff_ms" field.
func CurrentBackoffMsNEQ(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldCurrentBackoffMs, v))
}

// CurrentBackoffMsIn applies the In predicate on the "current_backoff_ms" field.
func CurrentBackoffMsIn(vs ...int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldCurrentBackoffMs, vs...))
}

// CurrentBackoffMsNotIn applies the NotIn predicate on the "current_backoff_ms" field.
func CurrentBackoffMsNotIn(vs ...int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldCurrentBackoffMs, vs...))
}

// CurrentBackoffMsGT applies the GT predicate on the "current_backoff_ms" field.
func CurrentBackoffMsGT(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldCurrentBackoffMs, v))
}

// CurrentBackoffMsGTE applies the GTE predicate on the "current_backoff_ms" field.
func CurrentBackoffMsGTE(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldCurrentBackoffMs, v))
}

// CurrentBackoffMsLT applies the LT predicate on the "current_backoff_ms" field.
func CurrentBackoffMsLT(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldCurrentBackoffMs, v))
}

// CurrentBackoffMsLTE applies the LTE predicate on the "current_backoff_ms" field.
func CurrentBackoffMsLTE(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldCurrentBackoffMs, v))
}

// ExecutorIDEQ applies the EQ predicate on the "executor_id" field.
func ExecutorIDEQ(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldExecutorID, v))
}

// ExecutorIDNEQ applies the NEQ predicate on the "executor_id" field.
func ExecutorIDNEQ(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldExecutorID, v))
}

// ExecutorIDIn applies the In predicate on the "executor_id" field.
func ExecutorIDIn(vs ...int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldExecutorID, vs...))
}

// ExecutorIDNotIn applies the NotIn predicate on the "executor_id" field.
func ExecutorIDNotIn(vs ...int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldExecutorID, vs...))
}

// ExecutorIDGT applies the GT predicate on the "executor_id" field.
func ExecutorIDGT(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldExecutorID, v))
}

// ExecutorIDGTE applies the GTE predicate on the "executor_id" field.
func ExecutorIDGTE(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldExecutorID, v))
}

// ExecutorIDLT applies the LT predicate on the "executor_id" field.
func ExecutorIDLT(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldExecutorID, v))
}

// ExecutorIDLTE applies the LTE predicate on the "executor_id" field.
func ExecutorIDLTE(v int64) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldExecutorID, v))
}

// ExecutorIDIsNil applies the IsNil predicate on the "executor_id" field.
func ExecutorIDIsNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIsNull(FieldExecutorID))
}

// ExecutorIDNotNil applies the NotNil predicate on the "executor_id" field.
func ExecutorIDNotNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotNull(FieldExecutorID))
}

// ShardTotalEQ applies the EQ predicate on the "shard_total" field.
func ShardTotalEQ(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldShardTotal, v))
}

// ShardTotalNEQ applies the NEQ predicate on the "shard_total" field.
func ShardTotalNEQ(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldShardTotal, v))
}

// ShardTotalIn applies the In predicate on the "shard_total" field.
func ShardTotalIn(vs ...int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldShardTotal, vs...))
}

// ShardTotalNotIn applies the NotIn predicate on the "shard_total" field.
func ShardTotalNotIn(vs ...int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldShardTotal, vs...))
}

// ShardTotalGT applies the GT predicate on the "shard_total" field.
func ShardTotalGT(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldShardTotal, v))
}

// ShardTotalGTE applies the GTE predicate on the "shard_total" field.
func ShardTotalGTE(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldShardTotal, v))
}

// ShardTotalLT applies the LT predicate on the "shard_total" field.
func ShardTotalLT(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldShardTotal, v))
}

// ShardTotalLTE applies the LTE predicate on the "shard_total" field.
func ShardTotalLTE(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldShardTotal, v))
}

// SuccessShardsEQ applies the EQ predicate on the "success_shards" field.
func SuccessShardsEQ(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldSuccessShards, v))
}

// SuccessShardsNEQ applies the NEQ predicate on the "success_shards" field.
func SuccessShardsNEQ(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldSuccessShards, v))
}

// SuccessShardsIn applies the In predicate on the "success_shards" field.
func SuccessShardsIn(vs ...int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldSuccessShards, vs...))
}

// SuccessShardsNotIn applies the NotIn predicate on the "success_shards" field.
func SuccessShardsNotIn(vs ...int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldSuccessShards, vs...))
}

// SuccessShardsGT applies the GT predicate on the "success_shards" field.
func SuccessShardsGT(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldSuccessShards, v))
}

// SuccessShardsGTE applies the GTE predicate on the "success_shards" field.
func SuccessShardsGTE(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldSuccessShards, v))
}

// SuccessShardsLT applies the LT predicate on the "success_shards" field.
func SuccessShardsLT(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldSuccessShards, v))
}

// SuccessShardsLTE applies the LTE predicate on the "success_shards" field.
func SuccessShardsLTE(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldSuccessShards, v))
}

// FailedShardsEQ applies the EQ predicate on the "failed_shards" field.
func FailedShardsEQ(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldFailedShards, v))
}

// FailedShardsNEQ applies the NEQ predicate on the "failed_shards" field.
func FailedShardsNEQ(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldFailedShards, v))
}

// FailedShardsIn applies the In predicate on the "failed_shards" field.
func FailedShardsIn(vs ...int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldFailedShards, vs...))
}

// FailedShardsNotIn applies the NotIn predicate on the "failed_shards" field.
func FailedShardsNotIn(vs ...int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldFailedShards, vs...))
}

// FailedShardsGT applies the GT predicate on the "failed_shards" field.
func FailedShardsGT(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldFailedShards, v))
}

// FailedShardsGTE applies the GTE predicate on the "failed_shards" field.
func FailedShardsGTE(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldFailedShards, v))
}

// FailedShardsLT applies the LT predicate on the "failed_shards" field.
func FailedShardsLT(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldFailedShards, v))
}

// FailedShardsLTE applies the LTE predicate on the "failed_shards" field.
func FailedShardsLTE(v int) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldFailedShards, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldPayload, v))
}

// PayloadContains applies the Contains predicate on the "payload" field.
func PayloadContains(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContains(FieldPayload, v))
}

// PayloadHasPrefix applies the HasPrefix predicate on the "payload" field.
func PayloadHasPrefix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasPrefix(FieldPayload, v))
}

// PayloadHasSuffix applies the HasSuffix predicate on the "payload" field.
func PayloadHasSuffix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasSuffix(FieldPayload, v))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotNull(FieldPayload))
}

// PayloadEqualFold applies the EqualFold predicate on the "payload" field.
func PayloadEqualFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEqualFold(FieldPayload, v))
}

// PayloadContainsFold applies the ContainsFold predicate on the "payload" field.
func PayloadContainsFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContainsFold(FieldPayload, v))
}

// ResultSummaryEQ applies the EQ predicate on the "result_summary" field.
func ResultSummaryEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldResultSummary, v))
}

// ResultSummaryNEQ applies the NEQ predicate on the "result_summary" field.
func ResultSummaryNEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldResultSummary, v))
}

// ResultSummaryIn applies the In predicate on the "result_summary" field.
func ResultSummaryIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldResultSummary, vs...))
}

// ResultSummaryNotIn applies the NotIn predicate on the "result_summary" field.
func ResultSummaryNotIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldResultSummary, vs...))
}

// ResultSummaryGT applies the GT predicate on the "result_summary" field.
func ResultSummaryGT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldResultSummary, v))
}

// ResultSummaryGTE applies the GTE predicate on the "result_summary" field.
func ResultSummaryGTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldResultSummary, v))
}

// ResultSummaryLT applies the LT predicate on the "result_summary" field.
func ResultSummaryLT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldResultSummary, v))
}

// ResultSummaryLTE applies the LTE predicate on the "result_summary" field.
func ResultSummaryLTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldResultSummary, v))
}

// ResultSummaryContains applies the Contains predicate on the "result_summary" field.
func ResultSummaryContains(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContains(FieldResultSummary, v))
}

// ResultSummaryHasPrefix applies the HasPrefix predicate on the "result_summary" field.
func ResultSummaryHasPrefix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasPrefix(FieldResultSummary, v))
}

// ResultSummaryHasSuffix applies the HasSuffix predicate on the "result_summary" field.
func ResultSummaryHasSuffix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasSuffix(FieldResultSummary, v))
}

// ResultSummaryIsNil applies the IsNil predicate on the "result_summary" field.
func ResultSummaryIsNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIsNull(FieldResultSummary))
}

// ResultSummaryNotNil applies the NotNil predicate on the "result_summary" field.
func ResultSummaryNotNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotNull(FieldResultSummary))
}

// ResultSummaryEqualFold applies the EqualFold predicate on the "result_summary" field.
func ResultSummaryEqualFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEqualFold(FieldResultSummary, v))
}

// ResultSummaryContainsFold applies the ContainsFold predicate on the "result_summary" field.
func ResultSummaryContainsFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContainsFold(FieldResultSummary, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.JobInstance {
	return predicate.JobInstance(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.JobInstance {
	return predicate.JobInstance(sql.FieldContainsFold(FieldErrorMessage, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.JobInstance) predicate.JobInstance {
	return predicate.JobInstance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.JobInstance) predicate.JobInstance {
	return predicate.JobInstance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.JobInstance) predicate.JobInstance {
	return predicate.JobInstance(sql.NotPredicates(p))
}
