// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/jobdefinition"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
)

// JobDefinitionUpdate is the builder for updating JobDefinition entities.
type JobDefinitionUpdate struct {
	config
	hooks    []Hook
	mutation *JobDefinitionMutation
}

// Where appends a list predicates to the JobDefinitionUpdate builder.
func (jdu *JobDefinitionUpdate) Where(ps ...predicate.JobDefinition) *JobDefinitionUpdate {
	jdu.mutation.Where(ps...)
	return jdu
}

// SetUpdatedAt sets the "updated_at" field.
func (jdu *JobDefinitionUpdate) SetUpdatedAt(t time.Time) *JobDefinitionUpdate {
	jdu.mutation.SetUpdatedAt(t)
	return jdu
}

// SetDeletedAt sets the "deleted_at" field.
func (jdu *JobDefinitionUpdate) SetDeletedAt(t time.Time) *JobDefinitionUpdate {
	jdu.mutation.SetDeletedAt(t)
	return jdu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableDeletedAt(t *time.Time) *JobDefinitionUpdate {
	if t != nil {
		jdu.SetDeletedAt(*t)
	}
	return jdu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (jdu *JobDefinitionUpdate) ClearDeletedAt() *JobDefinitionUpdate {
	jdu.mutation.ClearDeletedAt()
	return jdu
}

// SetJobCode sets the "job_code" field.
func (jdu *JobDefinitionUpdate) SetJobCode(s string) *JobDefinitionUpdate {
	jdu.mutation.SetJobCode(s)
	return jdu
}

// SetNillableJobCode sets the "job_code" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableJobCode(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetJobCode(*s)
	}
	return jdu
}

// SetJobName sets the "job_name" field.
func (jdu *JobDefinitionUpdate) SetJobName(s string) *JobDefinitionUpdate {
	jdu.mutation.SetJobName(s)
	return jdu
}

// SetNillableJobName sets the "job_name" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableJobName(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetJobName(*s)
	}
	return jdu
}

// SetJobType sets the "job_type" field.
func (jdu *JobDefinitionUpdate) SetJobType(s string) *JobDefinitionUpdate {
	jdu.mutation.SetJobType(s)
	return jdu
}

// SetNillableJobType sets the "job_type" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableJobType(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetJobType(*s)
	}
	return jdu
}

// SetScheduleExpr sets the "schedule_expr" field.
func (jdu *JobDefinitionUpdate) SetScheduleExpr(s string) *JobDefinitionUpdate {
	jdu.mutation.SetScheduleExpr(s)
	return jdu
}

// SetNillableScheduleExpr sets the "schedule_expr" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableScheduleExpr(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetScheduleExpr(*s)
	}
	return jdu
}

// ClearScheduleExpr clears the value of the "schedule_expr" field.
func (jdu *JobDefinitionUpdate) ClearScheduleExpr() *JobDefinitionUpdate {
	jdu.mutation.ClearScheduleExpr()
	return jdu
}

// SetDelayMs sets the "delay_ms" field.
func (jdu *JobDefinitionUpdate) SetDelayMs(i int64) *JobDefinitionUpdate {
	jdu.mutation.ResetDelayMs()
	jdu.mutation.SetDelayMs(i)
	return jdu
}

// SetNillableDelayMs sets the "delay_ms" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableDelayMs(i *int64) *JobDefinitionUpdate {
	if i != nil {
		jdu.SetDelayMs(*i)
	}
	return jdu
}

// AddDelayMs adds i to the "delay_ms" field.
func (jdu *JobDefinitionUpdate) AddDelayMs(i int64) *JobDefinitionUpdate {
	jdu.mutation.AddDelayMs(i)
	return jdu
}

// ClearDelayMs clears the value of the "delay_ms" field.
func (jdu *JobDefinitionUpdate) ClearDelayMs() *JobDefinitionUpdate {
	jdu.mutation.ClearDelayMs()
	return jdu
}

// SetExecuteMode sets the "execute_mode" field.
func (jdu *JobDefinitionUpdate) SetExecuteMode(s string) *JobDefinitionUpdate {
	jdu.mutation.SetExecuteMode(s)
	return jdu
}

// SetNillableExecuteMode sets the "execute_mode" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableExecuteMode(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetExecuteMode(*s)
	}
	return jdu
}

// SetHandlerName sets the "handler_name" field.
func (jdu *JobDefinitionUpdate) SetHandlerName(s string) *JobDefinitionUpdate {
	jdu.mutation.SetHandlerName(s)
	return jdu
}

// SetNillableHandlerName sets the "handler_name" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableHandlerName(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetHandlerName(*s)
	}
	return jdu
}

// SetHandlerPayload sets the "handler_payload" field.
func (jdu *JobDefinitionUpdate) SetHandlerPayload(s string) *JobDefinitionUpdate {
	jdu.mutation.SetHandlerPayload(s)
	return jdu
}

// SetNillableHandlerPayload sets the "handler_payload" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableHandlerPayload(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetHandlerPayload(*s)
	}
	return jdu
}

// ClearHandlerPayload clears the value of the "handler_payload" field.
func (jdu *JobDefinitionUpdate) ClearHandlerPayload() *JobDefinitionUpdate {
	jdu.mutation.ClearHandlerPayload()
	return jdu
}

// SetTimeoutMs sets the "timeout_ms" field.
func (jdu *JobDefinitionUpdate) SetTimeoutMs(i int) *JobDefinitionUpdate {
	jdu.mutation.ResetTimeoutMs()
	jdu.mutation.SetTimeoutMs(i)
	return jdu
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableTimeoutMs(i *int) *JobDefinitionUpdate {
	if i != nil {
		jdu.SetTimeoutMs(*i)
	}
	return jdu
}

// AddTimeoutMs adds i to the "timeout_ms" field.
func (jdu *JobDefinitionUpdate) AddTimeoutMs(i int) *JobDefinitionUpdate {
	jdu.mutation.AddTimeoutMs(i)
	return jdu
}

// SetRetryLimit sets the "retry_limit" field.
func (jdu *JobDefinitionUpdate) SetRetryLimit(i int) *JobDefinitionUpdate {
	jdu.mutation.ResetRetryLimit()
	jdu.mutation.SetRetryLimit(i)
	return jdu
}

// SetNillableRetryLimit sets the "retry_limit" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableRetryLimit(i *int) *JobDefinitionUpdate {
	if i != nil {
		jdu.SetRetryLimit(*i)
	}
	return jdu
}

// AddRetryLimit adds i to the "retry_limit" field.
func (jdu *JobDefinitionUpdate) AddRetryLimit(i int) *JobDefinitionUpdate {
	jdu.mutation.AddRetryLimit(i)
	return jdu
}

// SetRetryBackoff sets the "retry_backoff" field.
func (jdu *JobDefinitionUpdate) SetRetryBackoff(s string) *JobDefinitionUpdate {
	jdu.mutation.SetRetryBackoff(s)
	return jdu
}

// SetNillableRetryBackoff sets the "retry_backoff" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableRetryBackoff(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetRetryBackoff(*s)
	}
	return jdu
}

// SetPriority sets the "priority" field.
func (jdu *JobDefinitionUpdate) SetPriority(i int) *JobDefinitionUpdate {
	jdu.mutation.ResetPriority()
	jdu.mutation.SetPriority(i)
	return jdu
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillablePriority(i *int) *JobDefinitionUpdate {
	if i != nil {
		jdu.SetPriority(*i)
	}
	return jdu
}

// AddPriority adds i to the "priority" field.
func (jdu *JobDefinitionUpdate) AddPriority(i int) *JobDefinitionUpdate {
	jdu.mutation.AddPriority(i)
	return jdu
}

// SetShardTotal sets the "shard_total" field.
func (jdu *JobDefinitionUpdate) SetShardTotal(i int) *JobDefinitionUpdate {
	jdu.mutation.ResetShardTotal()
	jdu.mutation.SetShardTotal(i)
	return jdu
}

// SetNillableShardTotal sets the "shard_total" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableShardTotal(i *int) *JobDefinitionUpdate {
	if i != nil {
		jdu.SetShardTotal(*i)
	}
	return jdu
}

// AddShardTotal adds i to the "shard_total" field.
func (jdu *JobDefinitionUpdate) AddShardTotal(i int) *JobDefinitionUpdate {
	jdu.mutation.AddShardTotal(i)
	return jdu
}

// SetRouteStrategy sets the "route_strategy" field.
func (jdu *JobDefinitionUpdate) SetRouteStrategy(s string) *JobDefinitionUpdate {
	jdu.mutation.SetRouteStrategy(s)
	return jdu
}

// SetNillableRouteStrategy sets the "route_strategy" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableRouteStrategy(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetRouteStrategy(*s)
	}
	return jdu
}

// SetExecutorTag sets the "executor_tag" field.
func (jdu *JobDefinitionUpdate) SetExecutorTag(s string) *JobDefinitionUpdate {
	jdu.mutation.SetExecutorTag(s)
	return jdu
}

// SetNillableExecutorTag sets the "executor_tag" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableExecutorTag(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetExecutorTag(*s)
	}
	return jdu
}

// ClearExecutorTag clears the value of the "executor_tag" field.
func (jdu *JobDefinitionUpdate) ClearExecutorTag() *JobDefinitionUpdate {
	jdu.mutation.ClearExecutorTag()
	return jdu
}

// SetIdempotentKeyExpr sets the "idempotent_key_expr" field.
func (jdu *JobDefinitionUpdate) SetIdempotentKeyExpr(s string) *JobDefinitionUpdate {
	jdu.mutation.SetIdempotentKeyExpr(s)
	return jdu
}

// SetNillableIdempotentKeyExpr sets the "idempotent_key_expr" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableIdempotentKeyExpr(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetIdempotentKeyExpr(*s)
	}
	return jdu
}

// ClearIdempotentKeyExpr clears the value of the "idempotent_key_expr" field.
func (jdu *JobDefinitionUpdate) ClearIdempotentKeyExpr() *JobDefinitionUpdate {
	jdu.mutation.ClearIdempotentKeyExpr()
	return jdu
}

// SetStatus sets the "status" field.
func (jdu *JobDefinitionUpdate) SetStatus(s string) *JobDefinitionUpdate {
	jdu.mutation.SetStatus(s)
	return jdu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableStatus(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetStatus(*s)
	}
	return jdu
}

// SetCreatedBy sets the "created_by" field.
func (jdu *JobDefinitionUpdate) SetCreatedBy(s string) *JobDefinitionUpdate {
	jdu.mutation.SetCreatedBy(s)
	return jdu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableCreatedBy(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetCreatedBy(*s)
	}
	return jdu
}

// ClearCreatedBy clears the value of the "created_by" field.
func (jdu *JobDefinitionUpdate) ClearCreatedBy() *JobDefinitionUpdate {
	jdu.mutation.ClearCreatedBy()
	return jdu
}

// SetUpdatedBy sets the "updated_by" field.
func (jdu *JobDefinitionUpdate) SetUpdatedBy(s string) *JobDefinitionUpdate {
	jdu.mutation.SetUpdatedBy(s)
	return jdu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (jdu *JobDefinitionUpdate) SetNillableUpdatedBy(s *string) *JobDefinitionUpdate {
	if s != nil {
		jdu.SetUpdatedBy(*s)
	}
	return jdu
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (jdu *JobDefinitionUpdate) ClearUpdatedBy() *JobDefinitionUpdate {
	jdu.mutation.ClearUpdatedBy()
	return jdu
}

// Mutation returns the JobDefinitionMutation object of the builder.
func (jdu *JobDefinitionUpdate) Mutation() *JobDefinitionMutation {
	return jdu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (jdu *JobDefinitionUpdate) Save(ctx context.Context) (int, error) {
	jdu.defaults()
	return withHooks(ctx, jdu.sqlSave, jdu.mutation, jdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (jdu *JobDefinitionUpdate) SaveX(ctx context.Context) int {
	affected, err := jdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (jdu *JobDefinitionUpdate) Exec(ctx context.Context) error {
	_, err := jdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jdu *JobDefinitionUpdate) ExecX(ctx context.Context) {
	if err := jdu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jdu *JobDefinitionUpdate) defaults() {
	if _, ok := jdu.mutation.UpdatedAt(); !ok {
		v := jobdefinition.UpdateDefaultUpdatedAt()
		jdu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jdu *JobDefinitionUpdate) check() error {
	if v, ok := jdu.mutation.JobCode(); ok {
		if err := jobdefinition.JobCodeValidator(v); err != nil {
			return &ValidationError{Name: "job_code", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.job_code": %w`, err)}
		}
	}
	if v, ok := jdu.mutation.JobName(); ok {
		if err := jobdefinition.JobNameValidator(v); err != nil {
			return &ValidationError{Name: "job_name", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.job_name": %w`, err)}
		}
	}
	if v, ok := jdu.mutation.JobType(); ok {
		if err := jobdefinition.JobTypeValidator(v); err != nil {
			return &ValidationError{Name: "job_type", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.job_type": %w`, err)}
		}
	}
	if v, ok := jdu.mutation.ScheduleExpr(); ok {
		if err := jobdefinition.ScheduleExprValidator(v); err != nil {
			return &ValidationError{Name: "schedule_expr", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.schedule_expr": %w`, err)}
		}
	}
	if v, ok := jdu.mutation.ExecuteMode(); ok {
		if err := jobdefinition.ExecuteModeValidator(v); err != nil {
			return &ValidationError{Name: "execute_mode", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.execute_mode": %w`, err)}
		}
	}
	if v, ok := jdu.mutation.HandlerName(); ok {
		if err := jobdefinition.HandlerNameValidator(v); err != nil {
			return &ValidationError{Name: "handler_name", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.handler_name": %w`, err)}
		}
	}
	if v, ok := jdu.mutation.RouteStrategy(); ok {
		if err := jobdefinition.RouteStrategyValidator(v); err != nil {
			return &ValidationError{Name: "route_strategy", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.route_strategy": %w`, err)}
		}
	}
	if v, ok := jdu.mutation.ExecutorTag(); ok {
		if err := jobdefinition.ExecutorTagValidator(v); err != nil {
			return &ValidationError{Name: "executor_tag", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.executor_tag": %w`, err)}
		}
	}
	if v, ok := jdu.mutation.IdempotentKeyExpr(); ok {
		if err := jobdefinition.IdempotentKeyExprValidator(v); err != nil {
			return &ValidationError{Name: "idempotent_key_expr", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.idempotent_key_expr": %w`, err)}
		}
	}
	if v, ok := jdu.mutation.Status(); ok {
		if err := jobdefinition.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.status": %w`, err)}
		}
	}
	if v, ok := jdu.mutation.CreatedBy(); ok {
		if err := jobdefinition.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.created_by": %w`, err)}
		}
	}
	if v, ok := jdu.mutation.UpdatedBy(); ok {
		if err := jobdefinition.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.updated_by": %w`, err)}
		}
	}
	return nil
}

func (jdu *JobDefinitionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := jdu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(jobdefinition.Table, jobdefinition.Columns, sqlgraph.NewFieldSpec(jobdefinition.FieldID, field.TypeInt))
	if ps := jdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := jdu.mutation.UpdatedAt(); ok {
		_spec.SetField(jobdefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := jdu.mutation.DeletedAt(); ok {
		_spec.SetField(jobdefinition.FieldDeletedAt, field.TypeTime, value)
	}
	if jdu.mutation.DeletedAtCleared() {
		_spec.ClearField(jobdefinition.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := jdu.mutation.JobCode(); ok {
		_spec.SetField(jobdefinition.FieldJobCode, field.TypeString, value)
	}
	if value, ok := jdu.mutation.JobName(); ok {
		_spec.SetField(jobdefinition.FieldJobName, field.TypeString, value)
	}
	if value, ok := jdu.mutation.JobType(); ok {
		_spec.SetField(jobdefinition.FieldJobType, field.TypeString, value)
	}
	if value, ok := jdu.mutation.ScheduleExpr(); ok {
		_spec.SetField(jobdefinition.FieldScheduleExpr, field.TypeString, value)
	}
	if jdu.mutation.ScheduleExprCleared() {
		_spec.ClearField(jobdefinition.FieldScheduleExpr, field.TypeString)
	}
	if value, ok := jdu.mutation.DelayMs(); ok {
		_spec.SetField(jobdefinition.FieldDelayMs, field.TypeInt64, value)
	}
	if value, ok := jdu.mutation.AddedDelayMs(); ok {
		_spec.AddField(jobdefinition.FieldDelayMs, field.TypeInt64, value)
	}
	if jdu.mutation.DelayMsCleared() {
		_spec.ClearField(jobdefinition.FieldDelayMs, field.TypeInt64)
	}
	if value, ok := jdu.mutation.ExecuteMode(); ok {
		_spec.SetField(jobdefinition.FieldExecuteMode, field.TypeString, value)
	}
	if value, ok := jdu.mutation.HandlerName(); ok {
		_spec.SetField(jobdefinition.FieldHandlerName, field.TypeString, value)
	}
	if value, ok := jdu.mutation.HandlerPayload(); ok {
		_spec.SetField(jobdefinition.FieldHandlerPayload, field.TypeString, value)
	}
	if jdu.mutation.HandlerPayloadCleared() {
		_spec.ClearField(jobdefinition.FieldHandlerPayload, field.TypeString)
	}
	if value, ok := jdu.mutation.TimeoutMs(); ok {
		_spec.SetField(jobdefinition.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := jdu.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(jobdefinition.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := jdu.mutation.RetryLimit(); ok {
		_spec.SetField(jobdefinition.FieldRetryLimit, field.TypeInt, value)
	}
	if value, ok := jdu.mutation.AddedRetryLimit(); ok {
		_spec.AddField(jobdefinition.FieldRetryLimit, field.TypeInt, value)
	}
	if value, ok := jdu.mutation.RetryBackoff(); ok {
		_spec.SetField(jobdefinition.FieldRetryBackoff, field.TypeString, value)
	}
	if value, ok := jdu.mutation.Priority(); ok {
		_spec.SetField(jobdefinition.FieldPriority, field.TypeInt, value)
	}
	if value, ok := jdu.mutation.AddedPriority(); ok {
		_spec.AddField(jobdefinition.FieldPriority, field.TypeInt, value)
	}
	if value, ok := jdu.mutation.ShardTotal(); ok {
		_spec.SetField(jobdefinition.FieldShardTotal, field.TypeInt, value)
	}
	if value, ok := jdu.mutation.AddedShardTotal(); ok {
		_spec.AddField(jobdefinition.FieldShardTotal, field.TypeInt, value)
	}
	if value, ok := jdu.mutation.RouteStrategy(); ok {
		_spec.SetField(jobdefinition.FieldRouteStrategy, field.TypeString, value)
	}
	if value, ok := jdu.mutation.ExecutorTag(); ok {
		_spec.SetField(jobdefinition.FieldExecutorTag, field.TypeString, value)
	}
	if jdu.mutation.ExecutorTagCleared() {
		_spec.ClearField(jobdefinition.FieldExecutorTag, field.TypeString)
	}
	if value, ok := jdu.mutation.IdempotentKeyExpr(); ok {
		_spec.SetField(jobdefinition.FieldIdempotentKeyExpr, field.TypeString, value)
	}
	if jdu.mutation.IdempotentKeyExprCleared() {
		_spec.ClearField(jobdefinition.FieldIdempotentKeyExpr, field.TypeString)
	}
	if value, ok := jdu.mutation.Status(); ok {
		_spec.SetField(jobdefinition.FieldStatus, field.TypeString, value)
	}
	if value, ok := jdu.mutation.CreatedBy(); ok {
		_spec.SetField(jobdefinition.FieldCreatedBy, field.TypeString, value)
	}
	if jdu.mutation.CreatedByCleared() {
		_spec.ClearField(jobdefinition.FieldCreatedBy, field.TypeString)
	}
	if value, ok := jdu.mutation.UpdatedBy(); ok {
		_spec.SetField(jobdefinition.FieldUpdatedBy, field.TypeString, value)
	}
	if jdu.mutation.UpdatedByCleared() {
		_spec.ClearField(jobdefinition.FieldUpdatedBy, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, jdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jobdefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	jdu.mutation.done = true
	return n, nil
}

// JobDefinitionUpdateOne is the builder for updating a single JobDefinition entity.
type JobDefinitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobDefinitionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (jduo *JobDefinitionUpdateOne) SetUpdatedAt(t time.Time) *JobDefinitionUpdateOne {
	jduo.mutation.SetUpdatedAt(t)
	return jduo
}

// SetDeletedAt sets the "deleted_at" field.
func (jduo *JobDefinitionUpdateOne) SetDeletedAt(t time.Time) *JobDefinitionUpdateOne {
	jduo.mutation.SetDeletedAt(t)
	return jduo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableDeletedAt(t *time.Time) *JobDefinitionUpdateOne {
	if t != nil {
		jduo.SetDeletedAt(*t)
	}
	return jduo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (jduo *JobDefinitionUpdateOne) ClearDeletedAt() *JobDefinitionUpdateOne {
	jduo.mutation.ClearDeletedAt()
	return jduo
}

// SetJobCode sets the "job_code" field.
func (jduo *JobDefinitionUpdateOne) SetJobCode(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetJobCode(s)
	return jduo
}

// SetNillableJobCode sets the "job_code" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableJobCode(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetJobCode(*s)
	}
	return jduo
}

// SetJobName sets the "job_name" field.
func (jduo *JobDefinitionUpdateOne) SetJobName(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetJobName(s)
	return jduo
}

// SetNillableJobName sets the "job_name" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableJobName(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetJobName(*s)
	}
	return jduo
}

// SetJobType sets the "job_type" field.
func (jduo *JobDefinitionUpdateOne) SetJobType(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetJobType(s)
	return jduo
}

// SetNillableJobType sets the "job_type" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableJobType(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetJobType(*s)
	}
	return jduo
}

// SetScheduleExpr sets the "schedule_expr" field.
func (jduo *JobDefinitionUpdateOne) SetScheduleExpr(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetScheduleExpr(s)
	return jduo
}

// SetNillableScheduleExpr sets the "schedule_expr" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableScheduleExpr(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetScheduleExpr(*s)
	}
	return jduo
}

// ClearScheduleExpr clears the value of the "schedule_expr" field.
func (jduo *JobDefinitionUpdateOne) ClearScheduleExpr() *JobDefinitionUpdateOne {
	jduo.mutation.ClearScheduleExpr()
	return jduo
}

// SetDelayMs sets the "delay_ms" field.
func (jduo *JobDefinitionUpdateOne) SetDelayMs(i int64) *JobDefinitionUpdateOne {
	jduo.mutation.ResetDelayMs()
	jduo.mutation.SetDelayMs(i)
	return jduo
}

// SetNillableDelayMs sets the "delay_ms" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableDelayMs(i *int64) *JobDefinitionUpdateOne {
	if i != nil {
		jduo.SetDelayMs(*i)
	}
	return jduo
}

// AddDelayMs adds i to the "delay_ms" field.
func (jduo *JobDefinitionUpdateOne) AddDelayMs(i int64) *JobDefinitionUpdateOne {
	jduo.mutation.AddDelayMs(i)
	return jduo
}

// ClearDelayMs clears the value of the "delay_ms" field.
func (jduo *JobDefinitionUpdateOne) ClearDelayMs() *JobDefinitionUpdateOne {
	jduo.mutation.ClearDelayMs()
	return jduo
}

// SetExecuteMode sets the "execute_mode" field.
func (jduo *JobDefinitionUpdateOne) SetExecuteMode(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetExecuteMode(s)
	return jduo
}

// SetNillableExecuteMode sets the "execute_mode" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableExecuteMode(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetExecuteMode(*s)
	}
	return jduo
}

// SetHandlerName sets the "handler_name" field.
func (jduo *JobDefinitionUpdateOne) SetHandlerName(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetHandlerName(s)
	return jduo
}

// SetNillableHandlerName sets the "handler_name" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableHandlerName(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetHandlerName(*s)
	}
	return jduo
}

// SetHandlerPayload sets the "handler_payload" field.
func (jduo *JobDefinitionUpdateOne) SetHandlerPayload(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetHandlerPayload(s)
	return jduo
}

// SetNillableHandlerPayload sets the "handler_payload" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableHandlerPayload(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetHandlerPayload(*s)
	}
	return jduo
}

// ClearHandlerPayload clears the value of the "handler_payload" field.
func (jduo *JobDefinitionUpdateOne) ClearHandlerPayload() *JobDefinitionUpdateOne {
	jduo.mutation.ClearHandlerPayload()
	return jduo
}

// SetTimeoutMs sets the "timeout_ms" field.
func (jduo *JobDefinitionUpdateOne) SetTimeoutMs(i int) *JobDefinitionUpdateOne {
	jduo.mutation.ResetTimeoutMs()
	jduo.mutation.SetTimeoutMs(i)
	return jduo
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableTimeoutMs(i *int) *JobDefinitionUpdateOne {
	if i != nil {
		jduo.SetTimeoutMs(*i)
	}
	return jduo
}

// AddTimeoutMs adds i to the "timeout_ms" field.
func (jduo *JobDefinitionUpdateOne) AddTimeoutMs(i int) *JobDefinitionUpdateOne {
	jduo.mutation.AddTimeoutMs(i)
	return jduo
}

// SetRetryLimit sets the "retry_limit" field.
func (jduo *JobDefinitionUpdateOne) SetRetryLimit(i int) *JobDefinitionUpdateOne {
	jduo.mutation.ResetRetryLimit()
	jduo.mutation.SetRetryLimit(i)
	return jduo
}

// SetNillableRetryLimit sets the "retry_limit" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableRetryLimit(i *int) *JobDefinitionUpdateOne {
	if i != nil {
		jduo.SetRetryLimit(*i)
	}
	return jduo
}

// AddRetryLimit adds i to the "retry_limit" field.
func (jduo *JobDefinitionUpdateOne) AddRetryLimit(i int) *JobDefinitionUpdateOne {
	jduo.mutation.AddRetryLimit(i)
	return jduo
}

// SetRetryBackoff sets the "retry_backoff" field.
func (jduo *JobDefinitionUpdateOne) SetRetryBackoff(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetRetryBackoff(s)
	return jduo
}

// SetNillableRetryBackoff sets the "retry_backoff" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableRetryBackoff(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetRetryBackoff(*s)
	}
	return jduo
}

// SetPriority sets the "priority" field.
func (jduo *JobDefinitionUpdateOne) SetPriority(i int) *JobDefinitionUpdateOne {
	jduo.mutation.ResetPriority()
	jduo.mutation.SetPriority(i)
	return jduo
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillablePriority(i *int) *JobDefinitionUpdateOne {
	if i != nil {
		jduo.SetPriority(*i)
	}
	return jduo
}

// AddPriority adds i to the "priority" field.
func (jduo *JobDefinitionUpdateOne) AddPriority(i int) *JobDefinitionUpdateOne {
	jduo.mutation.AddPriority(i)
	return jduo
}

// SetShardTotal sets the "shard_total" field.
func (jduo *JobDefinitionUpdateOne) SetShardTotal(i int) *JobDefinitionUpdateOne {
	jduo.mutation.ResetShardTotal()
	jduo.mutation.SetShardTotal(i)
	return jduo
}

// SetNillableShardTotal sets the "shard_total" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableShardTotal(i *int) *JobDefinitionUpdateOne {
	if i != nil {
		jduo.SetShardTotal(*i)
	}
	return jduo
}

// AddShardTotal adds i to the "shard_total" field.
func (jduo *JobDefinitionUpdateOne) AddShardTotal(i int) *JobDefinitionUpdateOne {
	jduo.mutation.AddShardTotal(i)
	return jduo
}

// SetRouteStrategy sets the "route_strategy" field.
func (jduo *JobDefinitionUpdateOne) SetRouteStrategy(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetRouteStrategy(s)
	return jduo
}

// SetNillableRouteStrategy sets the "route_strategy" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableRouteStrategy(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetRouteStrategy(*s)
	}
	return jduo
}

// SetExecutorTag sets the "executor_tag" field.
func (jduo *JobDefinitionUpdateOne) SetExecutorTag(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetExecutorTag(s)
	return jduo
}

// SetNillableExecutorTag sets the "executor_tag" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableExecutorTag(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetExecutorTag(*s)
	}
	return jduo
}

// ClearExecutorTag clears the value of the "executor_tag" field.
func (jduo *JobDefinitionUpdateOne) ClearExecutorTag() *JobDefinitionUpdateOne {
	jduo.mutation.ClearExecutorTag()
	return jduo
}

// SetIdempotentKeyExpr sets the "idempotent_key_expr" field.
func (jduo *JobDefinitionUpdateOne) SetIdempotentKeyExpr(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetIdempotentKeyExpr(s)
	return jduo
}

// SetNillableIdempotentKeyExpr sets the "idempotent_key_expr" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableIdempotentKeyExpr(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetIdempotentKeyExpr(*s)
	}
	return jduo
}

// ClearIdempotentKeyExpr clears the value of the "idempotent_key_expr" field.
func (jduo *JobDefinitionUpdateOne) ClearIdempotentKeyExpr() *JobDefinitionUpdateOne {
	jduo.mutation.ClearIdempotentKeyExpr()
	return jduo
}

// SetStatus sets the "status" field.
func (jduo *JobDefinitionUpdateOne) SetStatus(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetStatus(s)
	return jduo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableStatus(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetStatus(*s)
	}
	return jduo
}

// SetCreatedBy sets the "created_by" field.
func (jduo *JobDefinitionUpdateOne) SetCreatedBy(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetCreatedBy(s)
	return jduo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableCreatedBy(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetCreatedBy(*s)
	}
	return jduo
}

// ClearCreatedBy clears the value of the "created_by" field.
func (jduo *JobDefinitionUpdateOne) ClearCreatedBy() *JobDefinitionUpdateOne {
	jduo.mutation.ClearCreatedBy()
	return jduo
}

// SetUpdatedBy sets the "updated_by" field.
func (jduo *JobDefinitionUpdateOne) SetUpdatedBy(s string) *JobDefinitionUpdateOne {
	jduo.mutation.SetUpdatedBy(s)
	return jduo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (jduo *JobDefinitionUpdateOne) SetNillableUpdatedBy(s *string) *JobDefinitionUpdateOne {
	if s != nil {
		jduo.SetUpdatedBy(*s)
	}
	return jduo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (jduo *JobDefinitionUpdateOne) ClearUpdatedBy() *JobDefinitionUpdateOne {
	jduo.mutation.ClearUpdatedBy()
	return jduo
}

// Mutation returns the JobDefinitionMutation object of the builder.
func (jduo *JobDefinitionUpdateOne) Mutation() *JobDefinitionMutation {
	return jduo.mutation
}

// Where appends a list predicates to the JobDefinitionUpdate builder.
func (jduo *JobDefinitionUpdateOne) Where(ps ...predicate.JobDefinition) *JobDefinitionUpdateOne {
	jduo.mutation.Where(ps...)
	return jduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (jduo *JobDefinitionUpdateOne) Select(field string, fields ...string) *JobDefinitionUpdateOne {
	jduo.fields = append([]string{field}, fields...)
	return jduo
}

// Save executes the query and returns the updated JobDefinition entity.
func (jduo *JobDefinitionUpdateOne) Save(ctx context.Context) (*JobDefinition, error) {
	jduo.defaults()
	return withHooks(ctx, jduo.sqlSave, jduo.mutation, jduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (jduo *JobDefinitionUpdateOne) SaveX(ctx context.Context) *JobDefinition {
	node, err := jduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (jduo *JobDefinitionUpdateOne) Exec(ctx context.Context) error {
	_, err := jduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jduo *JobDefinitionUpdateOne) ExecX(ctx context.Context) {
	if err := jduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jduo *JobDefinitionUpdateOne) defaults() {
	if _, ok := jduo.mutation.UpdatedAt(); !ok {
		v := jobdefinition.UpdateDefaultUpdatedAt()
		jduo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jduo *JobDefinitionUpdateOne) check() error {
	if v, ok := jduo.mutation.JobCode(); ok {
		if err := jobdefinition.JobCodeValidator(v); err != nil {
			return &ValidationError{Name: "job_code", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.job_code": %w`, err)}
		}
	}
	if v, ok := jduo.mutation.JobName(); ok {
		if err := jobdefinition.JobNameValidator(v); err != nil {
			return &ValidationError{Name: "job_name", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.job_name": %w`, err)}
		}
	}
	if v, ok := jduo.mutation.JobType(); ok {
		if err := jobdefinition.JobTypeValidator(v); err != nil {
			return &ValidationError{Name: "job_type", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.job_type": %w`, err)}
		}
	}
	if v, ok := jduo.mutation.ScheduleExpr(); ok {
		if err := jobdefinition.ScheduleExprValidator(v); err != nil {
			return &ValidationError{Name: "schedule_expr", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.schedule_expr": %w`, err)}
		}
	}
	if v, ok := jduo.mutation.ExecuteMode(); ok {
		if err := jobdefinition.ExecuteModeValidator(v); err != nil {
			return &ValidationError{Name: "execute_mode", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.execute_mode": %w`, err)}
		}
	}
	if v, ok := jduo.mutation.HandlerName(); ok {
		if err := jobdefinition.HandlerNameValidator(v); err != nil {
			return &ValidationError{Name: "handler_name", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.handler_name": %w`, err)}
		}
	}
	if v, ok := jduo.mutation.RouteStrategy(); ok {
		if err := jobdefinition.RouteStrategyValidator(v); err != nil {
			return &ValidationError{Name: "route_strategy", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.route_strategy": %w`, err)}
		}
	}
	if v, ok := jduo.mutation.ExecutorTag(); ok {
		if err := jobdefinition.ExecutorTagValidator(v); err != nil {
			return &ValidationError{Name: "executor_tag", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.executor_tag": %w`, err)}
		}
	}
	if v, ok := jduo.mutation.IdempotentKeyExpr(); ok {
		if err := jobdefinition.IdempotentKeyExprValidator(v); err != nil {
			return &ValidationError{Name: "idempotent_key_expr", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.idempotent_key_expr": %w`, err)}
		}
	}
	if v, ok := jduo.mutation.Status(); ok {
		if err := jobdefinition.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.status": %w`, err)}
		}
	}
	if v, ok := jduo.mutation.CreatedBy(); ok {
		if err := jobdefinition.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.created_by": %w`, err)}
		}
	}
	if v, ok := jduo.mutation.UpdatedBy(); ok {
		if err := jobdefinition.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.updated_by": %w`, err)}
		}
	}
	return nil
}

func (jduo *JobDefinitionUpdateOne) sqlSave(ctx context.Context) (_node *JobDefinition, err error) {
	if err := jduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(jobdefinition.Table, jobdefinition.Columns, sqlgraph.NewFieldSpec(jobdefinition.FieldID, field.TypeInt))
	id, ok := jduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "JobDefinition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := jduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobdefinition.FieldID)
		for _, f := range fields {
			if !jobdefinition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != jobdefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := jduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := jduo.mutation.UpdatedAt(); ok {
		_spec.SetField(jobdefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := jduo.mutation.DeletedAt(); ok {
		_spec.SetField(jobdefinition.FieldDeletedAt, field.TypeTime, value)
	}
	if jduo.mutation.DeletedAtCleared() {
		_spec.ClearField(jobdefinition.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := jduo.mutation.JobCode(); ok {
		_spec.SetField(jobdefinition.FieldJobCode, field.TypeString, value)
	}
	if value, ok := jduo.mutation.JobName(); ok {
		_spec.SetField(jobdefinition.FieldJobName, field.TypeString, value)
	}
	if value, ok := jduo.mutation.JobType(); ok {
		_spec.SetField(jobdefinition.FieldJobType, field.TypeString, value)
	}
	if value, ok := jduo.mutation.ScheduleExpr(); ok {
		_spec.SetField(jobdefinition.FieldScheduleExpr, field.TypeString, value)
	}
	if jduo.mutation.ScheduleExprCleared() {
		_spec.ClearField(jobdefinition.FieldScheduleExpr, field.TypeString)
	}
	if value, ok := jduo.mutation.DelayMs(); ok {
		_spec.SetField(jobdefinition.FieldDelayMs, field.TypeInt64, value)
	}
	if value, ok := jduo.mutation.AddedDelayMs(); ok {
		_spec.AddField(jobdefinition.FieldDelayMs, field.TypeInt64, value)
	}
	if jduo.mutation.DelayMsCleared() {
		_spec.ClearField(jobdefinition.FieldDelayMs, field.TypeInt64)
	}
	if value, ok := jduo.mutation.ExecuteMode(); ok {
		_spec.SetField(jobdefinition.FieldExecuteMode, field.TypeString, value)
	}
	if value, ok := jduo.mutation.HandlerName(); ok {
		_spec.SetField(jobdefinition.FieldHandlerName, field.TypeString, value)
	}
	if value, ok := jduo.mutation.HandlerPayload(); ok {
		_spec.SetField(jobdefinition.FieldHandlerPayload, field.TypeString, value)
	}
	if jduo.mutation.HandlerPayloadCleared() {
		_spec.ClearField(jobdefinition.FieldHandlerPayload, field.TypeString)
	}
	if value, ok := jduo.mutation.TimeoutMs(); ok {
		_spec.SetField(jobdefinition.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := jduo.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(jobdefinition.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := jduo.mutation.RetryLimit(); ok {
		_spec.SetField(jobdefinition.FieldRetryLimit, field.TypeInt, value)
	}
	if value, ok := jduo.mutation.AddedRetryLimit(); ok {
		_spec.AddField(jobdefinition.FieldRetryLimit, field.TypeInt, value)
	}
	if value, ok := jduo.mutation.RetryBackoff(); ok {
		_spec.SetField(jobdefinition.FieldRetryBackoff, field.TypeString, value)
	}
	if value, ok := jduo.mutation.Priority(); ok {
		_spec.SetField(jobdefinition.FieldPriority, field.TypeInt, value)
	}
	if value, ok := jduo.mutation.AddedPriority(); ok {
		_spec.AddField(jobdefinition.FieldPriority, field.TypeInt, value)
	}
	if value, ok := jduo.mutation.ShardTotal(); ok {
		_spec.SetField(jobdefinition.FieldShardTotal, field.TypeInt, value)
	}
	if value, ok := jduo.mutation.AddedShardTotal(); ok {
		_spec.AddField(jobdefinition.FieldShardTotal, field.TypeInt, value)
	}
	if value, ok := jduo.mutation.RouteStrategy(); ok {
		_spec.SetField(jobdefinition.FieldRouteStrategy, field.TypeString, value)
	}
	if value, ok := jduo.mutation.ExecutorTag(); ok {
		_spec.SetField(jobdefinition.FieldExecutorTag, field.TypeString, value)
	}
	if jduo.mutation.ExecutorTagCleared() {
		_spec.ClearField(jobdefinition.FieldExecutorTag, field.TypeString)
	}
	if value, ok := jduo.mutation.IdempotentKeyExpr(); ok {
		_spec.SetField(jobdefinition.FieldIdempotentKeyExpr, field.TypeString, value)
	}
	if jduo.mutation.IdempotentKeyExprCleared() {
		_spec.ClearField(jobdefinition.FieldIdempotentKeyExpr, field.TypeString)
	}
	if value, ok := jduo.mutation.Status(); ok {
		_spec.SetField(jobdefinition.FieldStatus, field.TypeString, value)
	}
	if value, ok := jduo.mutation.CreatedBy(); ok {
		_spec.SetField(jobdefinition.FieldCreatedBy, field.TypeString, value)
	}
	if jduo.mutation.CreatedByCleared() {
		_spec.ClearField(jobdefinition.FieldCreatedBy, field.TypeString)
	}
	if value, ok := jduo.mutation.UpdatedBy(); ok {
		_spec.SetField(jobdefinition.FieldUpdatedBy, field.TypeString, value)
	}
	if jduo.mutation.UpdatedByCleared() {
		_spec.ClearField(jobdefinition.FieldUpdatedBy, field.TypeString)
	}
	_node = &JobDefinition{config: jduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, jduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jobdefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	jduo.mutation.done = true
	return _node, nil
}
