// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/jobdefinition"
)

// JobDefinitionCreate is the builder for creating a JobDefinition entity.
type JobDefinitionCreate struct {
	config
	mutation *JobDefinitionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (jdc *JobDefinitionCreate) SetCreatedAt(t time.Time) *JobDefinitionCreate {
	jdc.mutation.SetCreatedAt(t)
	return jdc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableCreatedAt(t *time.Time) *JobDefinitionCreate {
	if t != nil {
		jdc.SetCreatedAt(*t)
	}
	return jdc
}

// SetUpdatedAt sets the "updated_at" field.
func (jdc *JobDefinitionCreate) SetUpdatedAt(t time.Time) *JobDefinitionCreate {
	jdc.mutation.SetUpdatedAt(t)
	return jdc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableUpdatedAt(t *time.Time) *JobDefinitionCreate {
	if t != nil {
		jdc.SetUpdatedAt(*t)
	}
	return jdc
}

// SetDeletedAt sets the "deleted_at" field.
func (jdc *JobDefinitionCreate) SetDeletedAt(t time.Time) *JobDefinitionCreate {
	jdc.mutation.SetDeletedAt(t)
	return jdc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableDeletedAt(t *time.Time) *JobDefinitionCreate {
	if t != nil {
		jdc.SetDeletedAt(*t)
	}
	return jdc
}

// SetJobCode sets the "job_code" field.
func (jdc *JobDefinitionCreate) SetJobCode(s string) *JobDefinitionCreate {
	jdc.mutation.SetJobCode(s)
	return jdc
}

// SetJobName sets the "job_name" field.
func (jdc *JobDefinitionCreate) SetJobName(s string) *JobDefinitionCreate {
	jdc.mutation.SetJobName(s)
	return jdc
}

// SetJobType sets the "job_type" field.
func (jdc *JobDefinitionCreate) SetJobType(s string) *JobDefinitionCreate {
	jdc.mutation.SetJobType(s)
	return jdc
}

// SetScheduleExpr sets the "schedule_expr" field.
func (jdc *JobDefinitionCreate) SetScheduleExpr(s string) *JobDefinitionCreate {
	jdc.mutation.SetScheduleExpr(s)
	return jdc
}

// SetNillableScheduleExpr sets the "schedule_expr" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableScheduleExpr(s *string) *JobDefinitionCreate {
	if s != nil {
		jdc.SetScheduleExpr(*s)
	}
	return jdc
}

// SetDelayMs sets the "delay_ms" field.
func (jdc *JobDefinitionCreate) SetDelayMs(i int64) *JobDefinitionCreate {
	jdc.mutation.SetDelayMs(i)
	return jdc
}

// SetNillableDelayMs sets the "delay_ms" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableDelayMs(i *int64) *JobDefinitionCreate {
	if i != nil {
		jdc.SetDelayMs(*i)
	}
	return jdc
}

// SetExecuteMode sets the "execute_mode" field.
func (jdc *JobDefinitionCreate) SetExecuteMode(s string) *JobDefinitionCreate {
	jdc.mutation.SetExecuteMode(s)
	return jdc
}

// SetNillableExecuteMode sets the "execute_mode" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableExecuteMode(s *string) *JobDefinitionCreate {
	if s != nil {
		jdc.SetExecuteMode(*s)
	}
	return jdc
}

// SetHandlerName sets the "handler_name" field.
func (jdc *JobDefinitionCreate) SetHandlerName(s string) *JobDefinitionCreate {
	jdc.mutation.SetHandlerName(s)
	return jdc
}

// SetNillableHandlerName sets the "handler_name" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableHandlerName(s *string) *JobDefinitionCreate {
	if s != nil {
		jdc.SetHandlerName(*s)
	}
	return jdc
}

// SetHandlerPayload sets the "handler_payload" field.
func (jdc *JobDefinitionCreate) SetHandlerPayload(s string) *JobDefinitionCreate {
	jdc.mutation.SetHandlerPayload(s)
	return jdc
}

// SetNillableHandlerPayload sets the "handler_payload" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableHandlerPayload(s *string) *JobDefinitionCreate {
	if s != nil {
		jdc.SetHandlerPayload(*s)
	}
	return jdc
}

// SetTimeoutMs sets the "timeout_ms" field.
func (jdc *JobDefinitionCreate) SetTimeoutMs(i int) *JobDefinitionCreate {
	jdc.mutation.SetTimeoutMs(i)
	return jdc
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableTimeoutMs(i *int) *JobDefinitionCreate {
	if i != nil {
		jdc.SetTimeoutMs(*i)
	}
	return jdc
}

// SetRetryLimit sets the "retry_limit" field.
func (jdc *JobDefinitionCreate) SetRetryLimit(i int) *JobDefinitionCreate {
	jdc.mutation.SetRetryLimit(i)
	return jdc
}

// SetNillableRetryLimit sets the "retry_limit" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableRetryLimit(i *int) *JobDefinitionCreate {
	if i != nil {
		jdc.SetRetryLimit(*i)
	}
	return jdc
}

// SetRetryBackoff sets the "retry_backoff" field.
func (jdc *JobDefinitionCreate) SetRetryBackoff(s string) *JobDefinitionCreate {
	jdc.mutation.SetRetryBackoff(s)
	return jdc
}

// SetNillableRetryBackoff sets the "retry_backoff" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableRetryBackoff(s *string) *JobDefinitionCreate {
	if s != nil {
		jdc.SetRetryBackoff(*s)
	}
	return jdc
}

// SetPriority sets the "priority" field.
func (jdc *JobDefinitionCreate) SetPriority(i int) *JobDefinitionCreate {
	jdc.mutation.SetPriority(i)
	return jdc
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillablePriority(i *int) *JobDefinitionCreate {
	if i != nil {
		jdc.SetPriority(*i)
	}
	return jdc
}

// SetShardTotal sets the "shard_total" field.
func (jdc *JobDefinitionCreate) SetShardTotal(i int) *JobDefinitionCreate {
	jdc.mutation.SetShardTotal(i)
	return jdc
}

// SetNillableShardTotal sets the "shard_total" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableShardTotal(i *int) *JobDefinitionCreate {
	if i != nil {
		jdc.SetShardTotal(*i)
	}
	return jdc
}

// SetRouteStrategy sets the "route_strategy" field.
func (jdc *JobDefinitionCreate) SetRouteStrategy(s string) *JobDefinitionCreate {
	jdc.mutation.SetRouteStrategy(s)
	return jdc
}

// SetNillableRouteStrategy sets the "route_strategy" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableRouteStrategy(s *string) *JobDefinitionCreate {
	if s != nil {
		jdc.SetRouteStrategy(*s)
	}
	return jdc
}

// SetExecutorTag sets the "executor_tag" field.
func (jdc *JobDefinitionCreate) SetExecutorTag(s string) *JobDefinitionCreate {
	jdc.mutation.SetExecutorTag(s)
	return jdc
}

// SetNillableExecutorTag sets the "executor_tag" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableExecutorTag(s *string) *JobDefinitionCreate {
	if s != nil {
		jdc.SetExecutorTag(*s)
	}
	return jdc
}

// SetIdempotentKeyExpr sets the "idempotent_key_expr" field.
func (jdc *JobDefinitionCreate) SetIdempotentKeyExpr(s string) *JobDefinitionCreate {
	jdc.mutation.SetIdempotentKeyExpr(s)
	return jdc
}

// SetNillableIdempotentKeyExpr sets the "idempotent_key_expr" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableIdempotentKeyExpr(s *string) *JobDefinitionCreate {
	if s != nil {
		jdc.SetIdempotentKeyExpr(*s)
	}
	return jdc
}

// SetStatus sets the "status" field.
func (jdc *JobDefinitionCreate) SetStatus(s string) *JobDefinitionCreate {
	jdc.mutation.SetStatus(s)
	return jdc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableStatus(s *string) *JobDefinitionCreate {
	if s != nil {
		jdc.SetStatus(*s)
	}
	return jdc
}

// SetCreatedBy sets the "created_by" field.
func (jdc *JobDefinitionCreate) SetCreatedBy(s string) *JobDefinitionCreate {
	jdc.mutation.SetCreatedBy(s)
	return jdc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableCreatedBy(s *string) *JobDefinitionCreate {
	if s != nil {
		jdc.SetCreatedBy(*s)
	}
	return jdc
}

// SetUpdatedBy sets the "updated_by" field.
func (jdc *JobDefinitionCreate) SetUpdatedBy(s string) *JobDefinitionCreate {
	jdc.mutation.SetUpdatedBy(s)
	return jdc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (jdc *JobDefinitionCreate) SetNillableUpdatedBy(s *string) *JobDefinitionCreate {
	if s != nil {
		jdc.SetUpdatedBy(*s)
	}
	return jdc
}

// Mutation returns the JobDefinitionMutation object of the builder.
func (jdc *JobDefinitionCreate) Mutation() *JobDefinitionMutation {
	return jdc.mutation
}

// Save creates the JobDefinition in the database.
func (jdc *JobDefinitionCreate) Save(ctx context.Context) (*JobDefinition, error) {
	jdc.defaults()
	return withHooks(ctx, jdc.sqlSave, jdc.mutation, jdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (jdc *JobDefinitionCreate) SaveX(ctx context.Context) *JobDefinition {
	v, err := jdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jdc *JobDefinitionCreate) Exec(ctx context.Context) error {
	_, err := jdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jdc *JobDefinitionCreate) ExecX(ctx context.Context) {
	if err := jdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jdc *JobDefinitionCreate) defaults() {
	if _, ok := jdc.mutation.CreatedAt(); !ok {
		v := jobdefinition.DefaultCreatedAt()
		jdc.mutation.SetCreatedAt(v)
	}
	if _, ok := jdc.mutation.UpdatedAt(); !ok {
		v := jobdefinition.DefaultUpdatedAt()
		jdc.mutation.SetUpdatedAt(v)
	}
	if _, ok := jdc.mutation.ExecuteMode(); !ok {
		v := jobdefinition.DefaultExecuteMode
		jdc.mutation.SetExecuteMode(v)
	}
	if _, ok := jdc.mutation.HandlerName(); !ok {
		v := jobdefinition.DefaultHandlerName
		jdc.mutation.SetHandlerName(v)
	}
	if _, ok := jdc.mutation.TimeoutMs(); !ok {
		v := jobdefinition.DefaultTimeoutMs
		jdc.mutation.SetTimeoutMs(v)
	}
	if _, ok := jdc.mutation.RetryLimit(); !ok {
		v := jobdefinition.DefaultRetryLimit
		jdc.mutation.SetRetryLimit(v)
	}
	if _, ok := jdc.mutation.RetryBackoff(); !ok {
		v := jobdefinition.DefaultRetryBackoff
		jdc.mutation.SetRetryBackoff(v)
	}
	if _, ok := jdc.mutation.Priority(); !ok {
		v := jobdefinition.DefaultPriority
		jdc.mutation.SetPriority(v)
	}
	if _, ok := jdc.mutation.ShardTotal(); !ok {
		v := jobdefinition.DefaultShardTotal
		jdc.mutation.SetShardTotal(v)
	}
	if _, ok := jdc.mutation.RouteStrategy(); !ok {
		v := jobdefinition.DefaultRouteStrategy
		jdc.mutation.SetRouteStrategy(v)
	}
	if _, ok := jdc.mutation.Status(); !ok {
		v := jobdefinition.DefaultStatus
		jdc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jdc *JobDefinitionCreate) check() error {
	if _, ok := jdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "JobDefinition.created_at"`)}
	}
	if _, ok := jdc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "JobDefinition.updated_at"`)}
	}
	if _, ok := jdc.mutation.JobCode(); !ok {
		return &ValidationError{Name: "job_code", err: errors.New(`ent: missing required field "JobDefinition.job_code"`)}
	}
	if v, ok := jdc.mutation.JobCode(); ok {
		if err := jobdefinition.JobCodeValidator(v); err != nil {
			return &ValidationError{Name: "job_code", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.job_code": %w`, err)}
		}
	}
	if _, ok := jdc.mutation.JobName(); !ok {
		return &ValidationError{Name: "job_name", err: errors.New(`ent: missing required field "JobDefinition.job_name"`)}
	}
	if v, ok := jdc.mutation.JobName(); ok {
		if err := jobdefinition.JobNameValidator(v); err != nil {
			return &ValidationError{Name: "job_name", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.job_name": %w`, err)}
		}
	}
	if _, ok := jdc.mutation.JobType(); !ok {
		return &ValidationError{Name: "job_type", err: errors.New(`ent: missing required field "JobDefinition.job_type"`)}
	}
	if v, ok := jdc.mutation.JobType(); ok {
		if err := jobdefinition.JobTypeValidator(v); err != nil {
			return &ValidationError{Name: "job_type", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.job_type": %w`, err)}
		}
	}
	if v, ok := jdc.mutation.ScheduleExpr(); ok {
		if err := jobdefinition.ScheduleExprValidator(v); err != nil {
			return &ValidationError{Name: "schedule_expr", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.schedule_expr": %w`, err)}
		}
	}
	if _, ok := jdc.mutation.ExecuteMode(); !ok {
		return &ValidationError{Name: "execute_mode", err: errors.New(`ent: missing required field "JobDefinition.execute_mode"`)}
	}
	if v, ok := jdc.mutation.ExecuteMode(); ok {
		if err := jobdefinition.ExecuteModeValidator(v); err != nil {
			return &ValidationError{Name: "execute_mode", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.execute_mode": %w`, err)}
		}
	}
	if _, ok := jdc.mutation.HandlerName(); !ok {
		return &ValidationError{Name: "handler_name", err: errors.New(`ent: missing required field "JobDefinition.handler_name"`)}
	}
	if v, ok := jdc.mutation.HandlerName(); ok {
		if err := jobdefinition.HandlerNameValidator(v); err != nil {
			return &ValidationError{Name: "handler_name", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.handler_name": %w`, err)}
		}
	}
	if _, ok := jdc.mutation.TimeoutMs(); !ok {
		return &ValidationError{Name: "timeout_ms", err: errors.New(`ent: missing required field "JobDefinition.timeout_ms"`)}
	}
	if _, ok := jdc.mutation.RetryLimit(); !ok {
		return &ValidationError{Name: "retry_limit", err: errors.New(`ent: missing required field "JobDefinition.retry_limit"`)}
	}
	if _, ok := jdc.mutation.RetryBackoff(); !ok {
		return &ValidationError{Name: "retry_backoff", err: errors.New(`ent: missing required field "JobDefinition.retry_backoff"`)}
	}
	if _, ok := jdc.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "JobDefinition.priority"`)}
	}
	if _, ok := jdc.mutation.ShardTotal(); !ok {
		return &ValidationError{Name: "shard_total", err: errors.New(`ent: missing required field "JobDefinition.shard_total"`)}
	}
	if _, ok := jdc.mutation.RouteStrategy(); !ok {
		return &ValidationError{Name: "route_strategy", err: errors.New(`ent: missing required field "JobDefinition.route_strategy"`)}
	}
	if v, ok := jdc.mutation.RouteStrategy(); ok {
		if err := jobdefinition.RouteStrategyValidator(v); err != nil {
			return &ValidationError{Name: "route_strategy", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.route_strategy": %w`, err)}
		}
	}
	if v, ok := jdc.mutation.ExecutorTag(); ok {
		if err := jobdefinition.ExecutorTagValidator(v); err != nil {
			return &ValidationError{Name: "executor_tag", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.executor_tag": %w`, err)}
		}
	}
	if v, ok := jdc.mutation.IdempotentKeyExpr(); ok {
		if err := jobdefinition.IdempotentKeyExprValidator(v); err != nil {
			return &ValidationError{Name: "idempotent_key_expr", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.idempotent_key_expr": %w`, err)}
		}
	}
	if _, ok := jdc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "JobDefinition.status"`)}
	}
	if v, ok := jdc.mutation.Status(); ok {
		if err := jobdefinition.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.status": %w`, err)}
		}
	}
	if v, ok := jdc.mutation.CreatedBy(); ok {
		if err := jobdefinition.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.created_by": %w`, err)}
		}
	}
	if v, ok := jdc.mutation.UpdatedBy(); ok {
		if err := jobdefinition.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "JobDefinition.updated_by": %w`, err)}
		}
	}
	return nil
}

func (jdc *JobDefinitionCreate) sqlSave(ctx context.Context) (*JobDefinition, error) {
	if err := jdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := jdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, jdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	jdc.mutation.id = &_node.ID
	jdc.mutation.done = true
	return _node, nil
}

func (jdc *JobDefinitionCreate) createSpec() (*JobDefinition, *sqlgraph.CreateSpec) {
	var (
		_node = &JobDefinition{config: jdc.config}
		_spec = sqlgraph.NewCreateSpec(jobdefinition.Table, sqlgraph.NewFieldSpec(jobdefinition.FieldID, field.TypeInt))
	)
	if value, ok := jdc.mutation.CreatedAt(); ok {
		_spec.SetField(jobdefinition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := jdc.mutation.UpdatedAt(); ok {
		_spec.SetField(jobdefinition.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := jdc.mutation.DeletedAt(); ok {
		_spec.SetField(jobdefinition.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := jdc.mutation.JobCode(); ok {
		_spec.SetField(jobdefinition.FieldJobCode, field.TypeString, value)
		_node.JobCode = value
	}
	if value, ok := jdc.mutation.JobName(); ok {
		_spec.SetField(jobdefinition.FieldJobName, field.TypeString, value)
		_node.JobName = value
	}
	if value, ok := jdc.mutation.JobType(); ok {
		_spec.SetField(jobdefinition.FieldJobType, field.TypeString, value)
		_node.JobType = value
	}
	if value, ok := jdc.mutation.ScheduleExpr(); ok {
		_spec.SetField(jobdefinition.FieldScheduleExpr, field.TypeString, value)
		_node.ScheduleExpr = &value
	}
	if value, ok := jdc.mutation.DelayMs(); ok {
		_spec.SetField(jobdefinition.FieldDelayMs, field.TypeInt64, value)
		_node.DelayMs = &value
	}
	if value, ok := jdc.mutation.ExecuteMode(); ok {
		_spec.SetField(jobdefinition.FieldExecuteMode, field.TypeString, value)
		_node.ExecuteMode = value
	}
	if value, ok := jdc.mutation.HandlerName(); ok {
		_spec.SetField(jobdefinition.FieldHandlerName, field.TypeString, value)
		_node.HandlerName = value
	}
	if value, ok := jdc.mutation.HandlerPayload(); ok {
		_spec.SetField(jobdefinition.FieldHandlerPayload, field.TypeString, value)
		_node.HandlerPayload = &value
	}
	if value, ok := jdc.mutation.TimeoutMs(); ok {
		_spec.SetField(jobdefinition.FieldTimeoutMs, field.TypeInt, value)
		_node.TimeoutMs = value
	}
	if value, ok := jdc.mutation.RetryLimit(); ok {
		_spec.SetField(jobdefinition.FieldRetryLimit, field.TypeInt, value)
		_node.RetryLimit = value
	}
	if value, ok := jdc.mutation.RetryBackoff(); ok {
		_spec.SetField(jobdefinition.FieldRetryBackoff, field.TypeString, value)
		_node.RetryBackoff = value
	}
	if value, ok := jdc.mutation.Priority(); ok {
		_spec.SetField(jobdefinition.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := jdc.mutation.ShardTotal(); ok {
		_spec.SetField(jobdefinition.FieldShardTotal, field.TypeInt, value)
		_node.ShardTotal = value
	}
	if value, ok := jdc.mutation.RouteStrategy(); ok {
		_spec.SetField(jobdefinition.FieldRouteStrategy, field.TypeString, value)
		_node.RouteStrategy = value
	}
	if value, ok := jdc.mutation.ExecutorTag(); ok {
		_spec.SetField(jobdefinition.FieldExecutorTag, field.TypeString, value)
		_node.ExecutorTag = &value
	}
	if value, ok := jdc.mutation.IdempotentKeyExpr(); ok {
		_spec.SetField(jobdefinition.FieldIdempotentKeyExpr, field.TypeString, value)
		_node.IdempotentKeyExpr = &value
	}
	if value, ok := jdc.mutation.Status(); ok {
		_spec.SetField(jobdefinition.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := jdc.mutation.CreatedBy(); ok {
		_spec.SetField(jobdefinition.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = &value
	}
	if value, ok := jdc.mutation.UpdatedBy(); ok {
		_spec.SetField(jobdefinition.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = &value
	}
	return _node, _spec
}

// JobDefinitionCreateBulk is the builder for creating many JobDefinition entities in bulk.
type JobDefinitionCreateBulk struct {
	config
	err      error
	builders []*JobDefinitionCreate
}

// Save creates the JobDefinition entities in the database.
func (jdcb *JobDefinitionCreateBulk) Save(ctx context.Context) ([]*JobDefinition, error) {
	if jdcb.err != nil {
		return nil, jdcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(jdcb.builders))
	nodes := make([]*JobDefinition, len(jdcb.builders))
	mutators := make([]Mutator, len(jdcb.builders))
	for i := range jdcb.builders {
		func(i int, root context.Context) {
			builder := jdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobDefinitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, jdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, jdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, jdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (jdcb *JobDefinitionCreateBulk) SaveX(ctx context.Context) []*JobDefinition {
	v, err := jdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jdcb *JobDefinitionCreateBulk) Exec(ctx context.Context) error {
	_, err := jdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jdcb *JobDefinitionCreateBulk) ExecX(ctx context.Context) {
	if err := jdcb.Exec(ctx); err != nil {
		panic(err)
	}
}
