// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/jobdefinition"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
)

// JobDefinitionQuery is the builder for querying JobDefinition entities.
type JobDefinitionQuery struct {
	config
	ctx        *QueryContext
	order      []jobdefinition.OrderOption
	inters     []Interceptor
	predicates []predicate.JobDefinition
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the JobDefinitionQuery builder.
func (jdq *JobDefinitionQuery) Where(ps ...predicate.JobDefinition) *JobDefinitionQuery {
	jdq.predicates = append(jdq.predicates, ps...)
	return jdq
}

// Limit the number of records to be returned by this query.
func (jdq *JobDefinitionQuery) Limit(limit int) *JobDefinitionQuery {
	jdq.ctx.Limit = &limit
	return jdq
}

// Offset to start from.
func (jdq *JobDefinitionQuery) Offset(offset int) *JobDefinitionQuery {
	jdq.ctx.Offset = &offset
	return jdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (jdq *JobDefinitionQuery) Unique(unique bool) *JobDefinitionQuery {
	jdq.ctx.Unique = &unique
	return jdq
}

// Order specifies how the records should be ordered.
func (jdq *JobDefinitionQuery) Order(o ...jobdefinition.OrderOption) *JobDefinitionQuery {
	jdq.order = append(jdq.order, o...)
	return jdq
}

// First returns the first JobDefinition entity from the query.
// Returns a *NotFoundError when no JobDefinition was found.
func (jdq *JobDefinitionQuery) First(ctx context.Context) (*JobDefinition, error) {
	nodes, err := jdq.Limit(1).All(setContextOp(ctx, jdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{jobdefinition.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (jdq *JobDefinitionQuery) FirstX(ctx context.Context) *JobDefinition {
	node, err := jdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first JobDefinition ID from the query.
// Returns a *NotFoundError when no JobDefinition ID was found.
func (jdq *JobDefinitionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jdq.Limit(1).IDs(setContextOp(ctx, jdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{jobdefinition.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (jdq *JobDefinitionQuery) FirstIDX(ctx context.Context) int {
	id, err := jdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single JobDefinition entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one JobDefinition entity is found.
// Returns a *NotFoundError when no JobDefinition entities are found.
func (jdq *JobDefinitionQuery) Only(ctx context.Context) (*JobDefinition, error) {
	nodes, err := jdq.Limit(2).All(setContextOp(ctx, jdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{jobdefinition.Label}
	default:
		return nil, &NotSingularError{jobdefinition.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (jdq *JobDefinitionQuery) OnlyX(ctx context.Context) *JobDefinition {
	node, err := jdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only JobDefinition ID in the query.
// Returns a *NotSingularError when more than one JobDefinition ID is found.
// Returns a *NotFoundError when no entities are found.
func (jdq *JobDefinitionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jdq.Limit(2).IDs(setContextOp(ctx, jdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{jobdefinition.Label}
	default:
		err = &NotSingularError{jobdefinition.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (jdq *JobDefinitionQuery) OnlyIDX(ctx context.Context) int {
	id, err := jdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of JobDefinitions.
func (jdq *JobDefinitionQuery) All(ctx context.Context) ([]*JobDefinition, error) {
	ctx = setContextOp(ctx, jdq.ctx, "All")
	if err := jdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*JobDefinition, *JobDefinitionQuery]()
	return withInterceptors[[]*JobDefinition](ctx, jdq, qr, jdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (jdq *JobDefinitionQuery) AllX(ctx context.Context) []*JobDefinition {
	nodes, err := jdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of JobDefinition IDs.
func (jdq *JobDefinitionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if jdq.ctx.Unique == nil && jdq.path != nil {
		jdq.Unique(true)
	}
	ctx = setContextOp(ctx, jdq.ctx, "IDs")
	if err = jdq.Select(jobdefinition.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (jdq *JobDefinitionQuery) IDsX(ctx context.Context) []int {
	ids, err := jdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (jdq *JobDefinitionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, jdq.ctx, "Count")
	if err := jdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, jdq, querierCount[*JobDefinitionQuery](), jdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (jdq *JobDefinitionQuery) CountX(ctx context.Context) int {
	count, err := jdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (jdq *JobDefinitionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, jdq.ctx, "Exist")
	switch _, err := jdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (jdq *JobDefinitionQuery) ExistX(ctx context.Context) bool {
	exist, err := jdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the JobDefinitionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (jdq *JobDefinitionQuery) Clone() *JobDefinitionQuery {
	if jdq == nil {
		return nil
	}
	return &JobDefinitionQuery{
		config:     jdq.config,
		ctx:        jdq.ctx.Clone(),
		order:      append([]jobdefinition.OrderOption{}, jdq.order...),
		inters:     append([]Interceptor{}, jdq.inters...),
		predicates: append([]predicate.JobDefinition{}, jdq.predicates...),
		// clone intermediate query.
		sql:  jdq.sql.Clone(),
		path: jdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.JobDefinition.Query().
//		GroupBy(jobdefinition.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (jdq *JobDefinitionQuery) GroupBy(field string, fields ...string) *JobDefinitionGroupBy {
	jdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &JobDefinitionGroupBy{build: jdq}
	grbuild.flds = &jdq.ctx.Fields
	grbuild.label = jobdefinition.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.JobDefinition.Query().
//		Select(jobdefinition.FieldCreatedAt).
//		Scan(ctx, &v)
func (jdq *JobDefinitionQuery) Select(fields ...string) *JobDefinitionSelect {
	jdq.ctx.Fields = append(jdq.ctx.Fields, fields...)
	sbuild := &JobDefinitionSelect{JobDefinitionQuery: jdq}
	sbuild.label = jobdefinition.Label
	sbuild.flds, sbuild.scan = &jdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a JobDefinitionSelect configured with the given aggregations.
func (jdq *JobDefinitionQuery) Aggregate(fns ...AggregateFunc) *JobDefinitionSelect {
	return jdq.Select().Aggregate(fns...)
}

func (jdq *JobDefinitionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range jdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, jdq); err != nil {
				return err
			}
		}
	}
	for _, f := range jdq.ctx.Fields {
		if !jobdefinition.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if jdq.path != nil {
		prev, err := jdq.path(ctx)
		if err != nil {
			return err
		}
		jdq.sql = prev
	}
	return nil
}

func (jdq *JobDefinitionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*JobDefinition, error) {
	var (
		nodes = []*JobDefinition{}
		_spec = jdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*JobDefinition).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &JobDefinition{config: jdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, jdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (jdq *JobDefinitionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := jdq.querySpec()
	_spec.Node.Columns = jdq.ctx.Fields
	if len(jdq.ctx.Fields) > 0 {
		_spec.Unique = jdq.ctx.Unique != nil && *jdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, jdq.driver, _spec)
}

func (jdq *JobDefinitionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(jobdefinition.Table, jobdefinition.Columns, sqlgraph.NewFieldSpec(jobdefinition.FieldID, field.TypeInt))
	_spec.From = jdq.sql
	if unique := jdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if jdq.path != nil {
		_spec.Unique = true
	}
	if fields := jdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobdefinition.FieldID)
		for i := range fields {
			if fields[i] != jobdefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := jdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := jdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := jdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := jdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (jdq *JobDefinitionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(jdq.driver.Dialect())
	t1 := builder.Table(jobdefinition.Table)
	columns := jdq.ctx.Fields
	if len(columns) == 0 {
		columns = jobdefinition.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if jdq.sql != nil {
		selector = jdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if jdq.ctx.Unique != nil && *jdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range jdq.predicates {
		p(selector)
	}
	for _, p := range jdq.order {
		p(selector)
	}
	if offset := jdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := jdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// JobDefinitionGroupBy is the group-by builder for JobDefinition entities.
type JobDefinitionGroupBy struct {
	selector
	build *JobDefinitionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (jdgb *JobDefinitionGroupBy) Aggregate(fns ...AggregateFunc) *JobDefinitionGroupBy {
	jdgb.fns = append(jdgb.fns, fns...)
	return jdgb
}

// Scan applies the selector query and scans the result into the given value.
func (jdgb *JobDefinitionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jdgb.build.ctx, "GroupBy")
	if err := jdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JobDefinitionQuery, *JobDefinitionGroupBy](ctx, jdgb.build, jdgb, jdgb.build.inters, v)
}

func (jdgb *JobDefinitionGroupBy) sqlScan(ctx context.Context, root *JobDefinitionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(jdgb.fns))
	for _, fn := range jdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*jdgb.flds)+len(jdgb.fns))
		for _, f := range *jdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*jdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// JobDefinitionSelect is the builder for selecting fields of JobDefinition entities.
type JobDefinitionSelect struct {
	*JobDefinitionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (jds *JobDefinitionSelect) Aggregate(fns ...AggregateFunc) *JobDefinitionSelect {
	jds.fns = append(jds.fns, fns...)
	return jds
}

// Scan applies the selector query and scans the result into the given value.
func (jds *JobDefinitionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jds.ctx, "Select")
	if err := jds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JobDefinitionQuery, *JobDefinitionSelect](ctx, jds.JobDefinitionQuery, jds, jds.inters, v)
}

func (jds *JobDefinitionSelect) sqlScan(ctx context.Context, root *JobDefinitionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(jds.fns))
	for _, fn := range jds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*jds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
