// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/jobexecutionlog"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
)

// JobExecutionLogUpdate is the builder for updating JobExecutionLog entities.
type JobExecutionLogUpdate struct {
	config
	hooks    []Hook
	mutation *JobExecutionLogMutation
}

// Where appends a list predicates to the JobExecutionLogUpdate builder.
func (jelu *JobExecutionLogUpdate) Where(ps ...predicate.JobExecutionLog) *JobExecutionLogUpdate {
	jelu.mutation.Where(ps...)
	return jelu
}

// SetUpdatedAt sets the "updated_at" field.
func (jelu *JobExecutionLogUpdate) SetUpdatedAt(t time.Time) *JobExecutionLogUpdate {
	jelu.mutation.SetUpdatedAt(t)
	return jelu
}

// SetDeletedAt sets the "deleted_at" field.
func (jelu *JobExecutionLogUpdate) SetDeletedAt(t time.Time) *JobExecutionLogUpdate {
	jelu.mutation.SetDeletedAt(t)
	return jelu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (jelu *JobExecutionLogUpdate) SetNillableDeletedAt(t *time.Time) *JobExecutionLogUpdate {
	if t != nil {
		jelu.SetDeletedAt(*t)
	}
	return jelu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (jelu *JobExecutionLogUpdate) ClearDeletedAt() *JobExecutionLogUpdate {
	jelu.mutation.ClearDeletedAt()
	return jelu
}

// SetInstanceNo sets the "instance_no" field.
func (jelu *JobExecutionLogUpdate) SetInstanceNo(s string) *JobExecutionLogUpdate {
	jelu.mutation.SetInstanceNo(s)
	return jelu
}

// SetNillableInstanceNo sets the "instance_no" field if the given value is not nil.
func (jelu *JobExecutionLogUpdate) SetNillableInstanceNo(s *string) *JobExecutionLogUpdate {
	if s != nil {
		jelu.SetInstanceNo(*s)
	}
	return jelu
}

// SetShardNo sets the "shard_no" field.
func (jelu *JobExecutionLogUpdate) SetShardNo(s string) *JobExecutionLogUpdate {
	jelu.mutation.SetShardNo(s)
	return jelu
}

// SetNillableShardNo sets the "shard_no" field if the given value is not nil.
func (jelu *JobExecutionLogUpdate) SetNillableShardNo(s *string) *JobExecutionLogUpdate {
	if s != nil {
		jelu.SetShardNo(*s)
	}
	return jelu
}

// ClearShardNo clears the value of the "shard_no" field.
func (jelu *JobExecutionLogUpdate) ClearShardNo() *JobExecutionLogUpdate {
	jelu.mutation.ClearShardNo()
	return jelu
}

// SetExecutorID sets the "executor_id" field.
func (jelu *JobExecutionLogUpdate) SetExecutorID(i int64) *JobExecutionLogUpdate {
	jelu.mutation.ResetExecutorID()
	jelu.mutation.SetExecutorID(i)
	return jelu
}

// SetNillableExecutorID sets the "executor_id" field if the given value is not nil.
func (jelu *JobExecutionLogUpdate) SetNillableExecutorID(i *int64) *JobExecutionLogUpdate {
	if i != nil {
		jelu.SetExecutorID(*i)
	}
	return jelu
}

// AddExecutorID adds i to the "executor_id" field.
func (jelu *JobExecutionLogUpdate) AddExecutorID(i int64) *JobExecutionLogUpdate {
	jelu.mutation.AddExecutorID(i)
	return jelu
}

// ClearExecutorID clears the value of the "executor_id" field.
func (jelu *JobExecutionLogUpdate) ClearExecutorID() *JobExecutionLogUpdate {
	jelu.mutation.ClearExecutorID()
	return jelu
}

// SetLogLevel sets the "log_level" field.
func (jelu *JobExecutionLogUpdate) SetLogLevel(s string) *JobExecutionLogUpdate {
	jelu.mutation.SetLogLevel(s)
	return jelu
}

// SetNillableLogLevel sets the "log_level" field if the given value is not nil.
func (jelu *JobExecutionLogUpdate) SetNillableLogLevel(s *string) *JobExecutionLogUpdate {
	if s != nil {
		jelu.SetLogLevel(*s)
	}
	return jelu
}

// SetPhase sets the "phase" field.
func (jelu *JobExecutionLogUpdate) SetPhase(s string) *JobExecutionLogUpdate {
	jelu.mutation.SetPhase(s)
	return jelu
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (jelu *JobExecutionLogUpdate) SetNillablePhase(s *string) *JobExecutionLogUpdate {
	if s != nil {
		jelu.SetPhase(*s)
	}
	return jelu
}

// SetMessage sets the "message" field.
func (jelu *JobExecutionLogUpdate) SetMessage(s string) *JobExecutionLogUpdate {
	jelu.mutation.SetMessage(s)
	return jelu
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (jelu *JobExecutionLogUpdate) SetNillableMessage(s *string) *JobExecutionLogUpdate {
	if s != nil {
		jelu.SetMessage(*s)
	}
	return jelu
}

// SetTraceID sets the "trace_id" field.
func (jelu *JobExecutionLogUpdate) SetTraceID(s string) *JobExecutionLogUpdate {
	jelu.mutation.SetTraceID(s)
	return jelu
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (jelu *JobExecutionLogUpdate) SetNillableTraceID(s *string) *JobExecutionLogUpdate {
	if s != nil {
		jelu.SetTraceID(*s)
	}
	return jelu
}

// ClearTraceID clears the value of the "trace_id" field.
func (jelu *JobExecutionLogUpdate) ClearTraceID() *JobExecutionLogUpdate {
	jelu.mutation.ClearTraceID()
	return jelu
}

// Mutation returns the JobExecutionLogMutation object of the builder.
func (jelu *JobExecutionLogUpdate) Mutation() *JobExecutionLogMutation {
	return jelu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (jelu *JobExecutionLogUpdate) Save(ctx context.Context) (int, error) {
	jelu.defaults()
	return withHooks(ctx, jelu.sqlSave, jelu.mutation, jelu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (jelu *JobExecutionLogUpdate) SaveX(ctx context.Context) int {
	affected, err := jelu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (jelu *JobExecutionLogUpdate) Exec(ctx context.Context) error {
	_, err := jelu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jelu *JobExecutionLogUpdate) ExecX(ctx context.Context) {
	if err := jelu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jelu *JobExecutionLogUpdate) defaults() {
	if _, ok := jelu.mutation.UpdatedAt(); !ok {
		v := jobexecutionlog.UpdateDefaultUpdatedAt()
		jelu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jelu *JobExecutionLogUpdate) check() error {
	if v, ok := jelu.mutation.InstanceNo(); ok {
		if err := jobexecutionlog.InstanceNoValidator(v); err != nil {
			return &ValidationError{Name: "instance_no", err: fmt.Errorf(`ent: validator failed for field "JobExecutionLog.instance_no": %w`, err)}
		}
	}
	if v, ok := jelu.mutation.ShardNo(); ok {
		if err := jobexecutionlog.ShardNoValidator(v); err != nil {
			return &ValidationError{Name: "shard_no", err: fmt.Errorf(`ent: validator failed for field "JobExecutionLog.shard_no": %w`, err)}
		}
	}
	if v, ok := jelu.mutation.LogLevel(); ok {
		if err := jobexecutionlog.LogLevelValidator(v); err != nil {
			return &ValidationError{Name: "log_level", err: fmt.Errorf(`ent: validator failed for field "JobExecutionLog.log_level": %w`, err)}
		}
	}
	if v, ok := jelu.mutation.Phase(); ok {
		if err := jobexecutionlog.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "JobExecutionLog.phase": %w`, err)}
		}
	}
	if v, ok := jelu.mutation.Message(); ok {
		if err := jobexecutionlog.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "JobExecutionLog.message": %w`, err)}
		}
	}
	if v, ok := jelu.mutation.TraceID(); ok {
		if err := jobexecutionlog.TraceIDValidator(v); err != nil {
			return &ValidationError{Name: "trace_id", err: fmt.Errorf(`ent: validator failed for field "JobExecutionLog.trace_id": %w`, err)}
		}
	}
	return nil
}

func (jelu *JobExecutionLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := jelu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(jobexecutionlog.Table, jobexecutionlog.Columns, sqlgraph.NewFieldSpec(jobexecutionlog.FieldID, field.TypeInt))
	if ps := jelu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := jelu.mutation.UpdatedAt(); ok {
		_spec.SetField(jobexecutionlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := jelu.mutation.DeletedAt(); ok {
		_spec.SetField(jobexecutionlog.FieldDeletedAt, field.TypeTime, value)
	}
	if jelu.mutation.DeletedAtCleared() {
		_spec.ClearField(jobexecutionlog.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := jelu.mutation.InstanceNo(); ok {
		_spec.SetField(jobexecutionlog.FieldInstanceNo, field.TypeString, value)
	}
	if value, ok := jelu.mutation.ShardNo(); ok {
		_spec.SetField(jobexecutionlog.FieldShardNo, field.TypeString, value)
	}
	if jelu.mutation.ShardNoCleared() {
		_spec.ClearField(jobexecutionlog.FieldShardNo, field.TypeString)
	}
	if value, ok := jelu.mutation.ExecutorID(); ok {
		_spec.SetField(jobexecutionlog.FieldExecutorID, field.TypeInt64, value)
	}
	if value, ok := jelu.mutation.AddedExecutorID(); ok {
		_spec.AddField(jobexecutionlog.FieldExecutorID, field.TypeInt64, value)
	}
	if jelu.mutation.ExecutorIDCleared() {
		_spec.ClearField(jobexecutionlog.FieldExecutorID, field.TypeInt64)
	}
	if value, ok := jelu.mutation.LogLevel(); ok {
		_spec.SetField(jobexecutionlog.FieldLogLevel, field.TypeString, value)
	}
	if value, ok := jelu.mutation.Phase(); ok {
		_spec.SetField(jobexecutionlog.FieldPhase, field.TypeString, value)
	}
	if value, ok := jelu.mutation.Message(); ok {
		_spec.SetField(jobexecutionlog.FieldMessage, field.TypeString, value)
	}
	if value, ok := jelu.mutation.TraceID(); ok {
		_spec.SetField(jobexecutionlog.FieldTraceID, field.TypeString, value)
	}
	if jelu.mutation.TraceIDCleared() {
		_spec.ClearField(jobexecutionlog.FieldTraceID, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, jelu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jobexecutionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	jelu.mutation.done = true
	return n, nil
}

// JobExecutionLogUpdateOne is the builder for updating a single JobExecutionLog entity.
type JobExecutionLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobExecutionLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (jeluo *JobExecutionLogUpdateOne) SetUpdatedAt(t time.Time) *JobExecutionLogUpdateOne {
	jeluo.mutation.SetUpdatedAt(t)
	return jeluo
}

// SetDeletedAt sets the "deleted_at" field.
func (jeluo *JobExecutionLogUpdateOne) SetDeletedAt(t time.Time) *JobExecutionLogUpdateOne {
	jeluo.mutation.SetDeletedAt(t)
	return jeluo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (jeluo *JobExecutionLogUpdateOne) SetNillableDeletedAt(t *time.Time) *JobExecutionLogUpdateOne {
	if t != nil {
		jeluo.SetDeletedAt(*t)
	}
	return jeluo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (jeluo *JobExecutionLogUpdateOne) ClearDeletedAt() *JobExecutionLogUpdateOne {
	jeluo.mutation.ClearDeletedAt()
	return jeluo
}

// SetInstanceNo sets the "instance_no" field.
func (jeluo *JobExecutionLogUpdateOne) SetInstanceNo(s string) *JobExecutionLogUpdateOne {
	jeluo.mutation.SetInstanceNo(s)
	return jeluo
}

// SetNillableInstanceNo sets the "instance_no" field if the given value is not nil.
func (jeluo *JobExecutionLogUpdateOne) SetNillableInstanceNo(s *string) *JobExecutionLogUpdateOne {
	if s != nil {
		jeluo.SetInstanceNo(*s)
	}
	return jeluo
}

// SetShardNo sets the "shard_no" field.
func (jeluo *JobExecutionLogUpdateOne) SetShardNo(s string) *JobExecutionLogUpdateOne {
	jeluo.mutation.SetShardNo(s)
	return jeluo
}

// SetNillableShardNo sets the "shard_no" field if the given value is not nil.
func (jeluo *JobExecutionLogUpdateOne) SetNillableShardNo(s *string) *JobExecutionLogUpdateOne {
	if s != nil {
		jeluo.SetShardNo(*s)
	}
	return jeluo
}

// ClearShardNo clears the value of the "shard_no" field.
func (jeluo *JobExecutionLogUpdateOne) ClearShardNo() *JobExecutionLogUpdateOne {
	jeluo.mutation.ClearShardNo()
	return jeluo
}

// SetExecutorID sets the "executor_id" field.
func (jeluo *JobExecutionLogUpdateOne) SetExecutorID(i int64) *JobExecutionLogUpdateOne {
	jeluo.mutation.ResetExecutorID()
	jeluo.mutation.SetExecutorID(i)
	return jeluo
}

// SetNillableExecutorID sets the "executor_id" field if the given value is not nil.
func (jeluo *JobExecutionLogUpdateOne) SetNillableExecutorID(i *int64) *JobExecutionLogUpdateOne {
	if i != nil {
		jeluo.SetExecutorID(*i)
	}
	return jeluo
}

// AddExecutorID adds i to the "executor_id" field.
func (jeluo *JobExecutionLogUpdateOne) AddExecutorID(i int64) *JobExecutionLogUpdateOne {
	jeluo.mutation.AddExecutorID(i)
	return jeluo
}

// ClearExecutorID clears the value of the "executor_id" field.
func (jeluo *JobExecutionLogUpdateOne) ClearExecutorID() *JobExecutionLogUpdateOne {
	jeluo.mutation.ClearExecutorID()
	return jeluo
}

// SetLogLevel sets the "log_level" field.
func (jeluo *JobExecutionLogUpdateOne) SetLogLevel(s string) *JobExecutionLogUpdateOne {
	jeluo.mutation.SetLogLevel(s)
	return jeluo
}

// SetNillableLogLevel sets the "log_level" field if the given value is not nil.
func (jeluo *JobExecutionLogUpdateOne) SetNillableLogLevel(s *string) *JobExecutionLogUpdateOne {
	if s != nil {
		jeluo.SetLogLevel(*s)
	}
	return jeluo
}

// SetPhase sets the "phase" field.
func (jeluo *JobExecutionLogUpdateOne) SetPhase(s string) *JobExecutionLogUpdateOne {
	jeluo.mutation.SetPhase(s)
	return jeluo
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (jeluo *JobExecutionLogUpdateOne) SetNillablePhase(s *string) *JobExecutionLogUpdateOne {
	if s != nil {
		jeluo.SetPhase(*s)
	}
	return jeluo
}

// SetMessage sets the "message" field.
func (jeluo *JobExecutionLogUpdateOne) SetMessage(s string) *JobExecutionLogUpdateOne {
	jeluo.mutation.SetMessage(s)
	return jeluo
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (jeluo *JobExecutionLogUpdateOne) SetNillableMessage(s *string) *JobExecutionLogUpdateOne {
	if s != nil {
		jeluo.SetMessage(*s)
	}
	return jeluo
}

// SetTraceID sets the "trace_id" field.
func (jeluo *JobExecutionLogUpdateOne) SetTraceID(s string) *JobExecutionLogUpdateOne {
	jeluo.mutation.SetTraceID(s)
	return jeluo
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (jeluo *JobExecutionLogUpdateOne) SetNillableTraceID(s *string) *JobExecutionLogUpdateOne {
	if s != nil {
		jeluo.SetTraceID(*s)
	}
	return jeluo
}

// ClearTraceID clears the value of the "trace_id" field.
func (jeluo *JobExecutionLogUpdateOne) ClearTraceID() *JobExecutionLogUpdateOne {
	jeluo.mutation.ClearTraceID()
	return jeluo
}

// Mutation returns the JobExecutionLogMutation object of the builder.
func (jeluo *JobExecutionLogUpdateOne) Mutation() *JobExecutionLogMutation {
	return jeluo.mutation
}

// Where appends a list predicates to the JobExecutionLogUpdate builder.
func (jeluo *JobExecutionLogUpdateOne) Where(ps ...predicate.JobExecutionLog) *JobExecutionLogUpdateOne {
	jeluo.mutation.Where(ps...)
	return jeluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (jeluo *JobExecutionLogUpdateOne) Select(field string, fields ...string) *JobExecutionLogUpdateOne {
	jeluo.fields = append([]string{field}, fields...)
	return jeluo
}

// Save executes the query and returns the updated JobExecutionLog entity.
func (jeluo *JobExecutionLogUpdateOne) Save(ctx context.Context) (*JobExecutionLog, error) {
	jeluo.defaults()
	return withHooks(ctx, jeluo.sqlSave, jeluo.mutation, jeluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (jeluo *JobExecutionLogUpdateOne) SaveX(ctx context.Context) *JobExecutionLog {
	node, err := jeluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (jeluo *JobExecutionLogUpdateOne) Exec(ctx context.Context) error {
	_, err := jeluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jeluo *JobExecutionLogUpdateOne) ExecX(ctx context.Context) {
	if err := jeluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jeluo *JobExecutionLogUpdateOne) defaults() {
	if _, ok := jeluo.mutation.UpdatedAt(); !ok {
		v := jobexecutionlog.UpdateDefaultUpdatedAt()
		jeluo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jeluo *JobExecutionLogUpdateOne) check() error {
	if v, ok := jeluo.mutation.InstanceNo(); ok {
		if err := jobexecutionlog.InstanceNoValidator(v); err != nil {
			return &ValidationError{Name: "instance_no", err: fmt.Errorf(`ent: validator failed for field "JobExecutionLog.instance_no": %w`, err)}
		}
	}
	if v, ok := jeluo.mutation.ShardNo(); ok {
		if err := jobexecutionlog.ShardNoValidator(v); err != nil {
			return &ValidationError{Name: "shard_no", err: fmt.Errorf(`ent: validator failed for field "JobExecutionLog.shard_no": %w`, err)}
		}
	}
	if v, ok := jeluo.mutation.LogLevel(); ok {
		if err := jobexecutionlog.LogLevelValidator(v); err != nil {
			return &ValidationError{Name: "log_level", err: fmt.Errorf(`ent: validator failed for field "JobExecutionLog.log_level": %w`, err)}
		}
	}
	if v, ok := jeluo.mutation.Phase(); ok {
		if err := jobexecutionlog.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "JobExecutionLog.phase": %w`, err)}
		}
	}
	if v, ok := jeluo.mutation.Message(); ok {
		if err := jobexecutionlog.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "JobExecutionLog.message": %w`, err)}
		}
	}
	if v, ok := jeluo.mutation.TraceID(); ok {
		if err := jobexecutionlog.TraceIDValidator(v); err != nil {
			return &ValidationError{Name: "trace_id", err: fmt.Errorf(`ent: validator failed for field "JobExecutionLog.trace_id": %w`, err)}
		}
	}
	return nil
}

func (jeluo *JobExecutionLogUpdateOne) sqlSave(ctx context.Context) (_node *JobExecutionLog, err error) {
	if err := jeluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(jobexecutionlog.Table, jobexecutionlog.Columns, sqlgraph.NewFieldSpec(jobexecutionlog.FieldID, field.TypeInt))
	id, ok := jeluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "JobExecutionLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := jeluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobexecutionlog.FieldID)
		for _, f := range fields {
			if !jobexecutionlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != jobexecutionlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := jeluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := jeluo.mutation.UpdatedAt(); ok {
		_spec.SetField(jobexecutionlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := jeluo.mutation.DeletedAt(); ok {
		_spec.SetField(jobexecutionlog.FieldDeletedAt, field.TypeTime, value)
	}
	if jeluo.mutation.DeletedAtCleared() {
		_spec.ClearField(jobexecutionlog.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := jeluo.mutation.InstanceNo(); ok {
		_spec.SetField(jobexecutionlog.FieldInstanceNo, field.TypeString, value)
	}
	if value, ok := jeluo.mutation.ShardNo(); ok {
		_spec.SetField(jobexecutionlog.FieldShardNo, field.TypeString, value)
	}
	if jeluo.mutation.ShardNoCleared() {
		_spec.ClearField(jobexecutionlog.FieldShardNo, field.TypeString)
	}
	if value, ok := jeluo.mutation.ExecutorID(); ok {
		_spec.SetField(jobexecutionlog.FieldExecutorID, field.TypeInt64, value)
	}
	if value, ok := jeluo.mutation.AddedExecutorID(); ok {
		_spec.AddField(jobexecutionlog.FieldExecutorID, field.TypeInt64, value)
	}
	if jeluo.mutation.ExecutorIDCleared() {
		_spec.ClearField(jobexecutionlog.FieldExecutorID, field.TypeInt64)
	}
	if value, ok := jeluo.mutation.LogLevel(); ok {
		_spec.SetField(jobexecutionlog.FieldLogLevel, field.TypeString, value)
	}
	if value, ok := jeluo.mutation.Phase(); ok {
		_spec.SetField(jobexecutionlog.FieldPhase, field.TypeString, value)
	}
	if value, ok := jeluo.mutation.Message(); ok {
		_spec.SetField(jobexecutionlog.FieldMessage, field.TypeString, value)
	}
	if value, ok := jeluo.mutation.TraceID(); ok {
		_spec.SetField(jobexecutionlog.FieldTraceID, field.TypeString, value)
	}
	if jeluo.mutation.TraceIDCleared() {
		_spec.ClearField(jobexecutionlog.FieldTraceID, field.TypeString)
	}
	_node = &JobExecutionLog{config: jeluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, jeluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jobexecutionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	jeluo.mutation.done = true
	return _node, nil
}
