// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/jobinstance"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
)

// JobInstanceUpdate is the builder for updating JobInstance entities.
type JobInstanceUpdate struct {
	config
	hooks    []Hook
	mutation *JobInstanceMutation
}

// Where appends a list predicates to the JobInstanceUpdate builder.
func (jiu *JobInstanceUpdate) Where(ps ...predicate.JobInstance) *JobInstanceUpdate {
	jiu.mutation.Where(ps...)
	return jiu
}

// SetUpdatedAt sets the "updated_at" field.
func (jiu *JobInstanceUpdate) SetUpdatedAt(t time.Time) *JobInstanceUpdate {
	jiu.mutation.SetUpdatedAt(t)
	return jiu
}

// SetDeletedAt sets the "deleted_at" field.
func (jiu *JobInstanceUpdate) SetDeletedAt(t time.Time) *JobInstanceUpdate {
	jiu.mutation.SetDeletedAt(t)
	return jiu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableDeletedAt(t *time.Time) *JobInstanceUpdate {
	if t != nil {
		jiu.SetDeletedAt(*t)
	}
	return jiu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (jiu *JobInstanceUpdate) ClearDeletedAt() *JobInstanceUpdate {
	jiu.mutation.ClearDeletedAt()
	return jiu
}

// SetInstanceNo sets the "instance_no" field.
func (jiu *JobInstanceUpdate) SetInstanceNo(s string) *JobInstanceUpdate {
	jiu.mutation.SetInstanceNo(s)
	return jiu
}

// SetNillableInstanceNo sets the "instance_no" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableInstanceNo(s *string) *JobInstanceUpdate {
	if s != nil {
		jiu.SetInstanceNo(*s)
	}
	return jiu
}

// SetJobID sets the "job_id" field.
func (jiu *JobInstanceUpdate) SetJobID(i int64) *JobInstanceUpdate {
	jiu.mutation.ResetJobID()
	jiu.mutation.SetJobID(i)
	return jiu
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableJobID(i *int64) *JobInstanceUpdate {
	if i != nil {
		jiu.SetJobID(*i)
	}
	return jiu
}

// AddJobID adds i to the "job_id" field.
func (jiu *JobInstanceUpdate) AddJobID(i int64) *JobInstanceUpdate {
	jiu.mutation.AddJobID(i)
	return jiu
}

// SetWorkflowID sets the "workflow_id" field.
func (jiu *JobInstanceUpdate) SetWorkflowID(i int64) *JobInstanceUpdate {
	jiu.mutation.ResetWorkflowID()
	jiu.mutation.SetWorkflowID(i)
	return jiu
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableWorkflowID(i *int64) *JobInstanceUpdate {
	if i != nil {
		jiu.SetWorkflowID(*i)
	}
	return jiu
}

// AddWorkflowID adds i to the "workflow_id" field.
func (jiu *JobInstanceUpdate) AddWorkflowID(i int64) *JobInstanceUpdate {
	jiu.mutation.AddWorkflowID(i)
	return jiu
}

// ClearWorkflowID clears the value of the "workflow_id" field.
func (jiu *JobInstanceUpdate) ClearWorkflowID() *JobInstanceUpdate {
	jiu.mutation.ClearWorkflowID()
	return jiu
}

// SetTriggerType sets the "trigger_type" field.
func (jiu *JobInstanceUpdate) SetTriggerType(s string) *JobInstanceUpdate {
	jiu.mutation.SetTriggerType(s)
	return jiu
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableTriggerType(s *string) *JobInstanceUpdate {
	if s != nil {
		jiu.SetTriggerType(*s)
	}
	return jiu
}

// SetTriggerTime sets the "trigger_time" field.
func (jiu *JobInstanceUpdate) SetTriggerTime(t time.Time) *JobInstanceUpdate {
	jiu.mutation.SetTriggerTime(t)
	return jiu
}

// SetNillableTriggerTime sets the "trigger_time" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableTriggerTime(t *time.Time) *JobInstanceUpdate {
	if t != nil {
		jiu.SetTriggerTime(*t)
	}
	return jiu
}

// SetScheduledTime sets the "scheduled_time" field.
func (jiu *JobInstanceUpdate) SetScheduledTime(t time.Time) *JobInstanceUpdate {
	jiu.mutation.SetScheduledTime(t)
	return jiu
}

// SetNillableScheduledTime sets the "scheduled_time" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableScheduledTime(t *time.Time) *JobInstanceUpdate {
	if t != nil {
		jiu.SetScheduledTime(*t)
	}
	return jiu
}

// SetDispatchTime sets the "dispatch_time" field.
func (jiu *JobInstanceUpdate) SetDispatchTime(t time.Time) *JobInstanceUpdate {
	jiu.mutation.SetDispatchTime(t)
	return jiu
}

// SetNillableDispatchTime sets the "dispatch_time" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableDispatchTime(t *time.Time) *JobInstanceUpdate {
	if t != nil {
		jiu.SetDispatchTime(*t)
	}
	return jiu
}

// ClearDispatchTime clears the value of the "dispatch_time" field.
func (jiu *JobInstanceUpdate) ClearDispatchTime() *JobInstanceUpdate {
	jiu.mutation.ClearDispatchTime()
	return jiu
}

// SetStartTime sets the "start_time" field.
func (jiu *JobInstanceUpdate) SetStartTime(t time.Time) *JobInstanceUpdate {
	jiu.mutation.SetStartTime(t)
	return jiu
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableStartTime(t *time.Time) *JobInstanceUpdate {
	if t != nil {
		jiu.SetStartTime(*t)
	}
	return jiu
}

// ClearStartTime clears the value of the "start_time" field.
func (jiu *JobInstanceUpdate) ClearStartTime() *JobInstanceUpdate {
	jiu.mutation.ClearStartTime()
	return jiu
}

// SetFinishTime sets the "finish_time" field.
func (jiu *JobInstanceUpdate) SetFinishTime(t time.Time) *JobInstanceUpdate {
	jiu.mutation.SetFinishTime(t)
	return jiu
}

// SetNillableFinishTime sets the "finish_time" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableFinishTime(t *time.Time) *JobInstanceUpdate {
	if t != nil {
		jiu.SetFinishTime(*t)
	}
	return jiu
}

// ClearFinishTime clears the value of the "finish_time" field.
func (jiu *JobInstanceUpdate) ClearFinishTime() *JobInstanceUpdate {
	jiu.mutation.ClearFinishTime()
	return jiu
}

// SetStatus sets the "status" field.
func (jiu *JobInstanceUpdate) SetStatus(s string) *JobInstanceUpdate {
	jiu.mutation.SetStatus(s)
	return jiu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableStatus(s *string) *JobInstanceUpdate {
	if s != nil {
		jiu.SetStatus(*s)
	}
	return jiu
}

// SetRetryCount sets the "retry_count" field.
func (jiu *JobInstanceUpdate) SetRetryCount(i int) *JobInstanceUpdate {
	jiu.mutation.ResetRetryCount()
	jiu.mutation.SetRetryCount(i)
	return jiu
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableRetryCount(i *int) *JobInstanceUpdate {
	if i != nil {
		jiu.SetRetryCount(*i)
	}
	return jiu
}

// AddRetryCount adds i to the "retry_count" field.
func (jiu *JobInstanceUpdate) AddRetryCount(i int) *JobInstanceUpdate {
	jiu.mutation.AddRetryCount(i)
	return jiu
}

// SetCurrentBackoffMs sets the "current_backoff_ms" field.
func (jiu *JobInstanceUpdate) SetCurrentBackoffMs(i int64) *JobInstanceUpdate {
	jiu.mutation.ResetCurrentBackoffMs()
	jiu.mutation.SetCurrentBackoffMs(i)
	return jiu
}

// SetNillableCurrentBackoffMs sets the "current_backoff_ms" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableCurrentBackoffMs(i *int64) *JobInstanceUpdate {
	if i != nil {
		jiu.SetCurrentBackoffMs(*i)
	}
	return jiu
}

// AddCurrentBackoffMs adds i to the "current_backoff_ms" field.
func (jiu *JobInstanceUpdate) AddCurrentBackoffMs(i int64) *JobInstanceUpdate {
	jiu.mutation.AddCurrentBackoffMs(i)
	return jiu
}

// SetExecutorID sets the "executor_id" field.
func (jiu *JobInstanceUpdate) SetExecutorID(i int64) *JobInstanceUpdate {
	jiu.mutation.ResetExecutorID()
	jiu.mutation.SetExecutorID(i)
	return jiu
}

// SetNillableExecutorID sets the "executor_id" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableExecutorID(i *int64) *JobInstanceUpdate {
	if i != nil {
		jiu.SetExecutorID(*i)
	}
	return jiu
}

// AddExecutorID adds i to the "executor_id" field.
func (jiu *JobInstanceUpdate) AddExecutorID(i int64) *JobInstanceUpdate {
	jiu.mutation.AddExecutorID(i)
	return jiu
}

// ClearExecutorID clears the value of the "executor_id" field.
func (jiu *JobInstanceUpdate) ClearExecutorID() *JobInstanceUpdate {
	jiu.mutation.ClearExecutorID()
	return jiu
}

// SetShardTotal sets the "shard_total" field.
func (jiu *JobInstanceUpdate) SetShardTotal(i int) *JobInstanceUpdate {
	jiu.mutation.ResetShardTotal()
	jiu.mutation.SetShardTotal(i)
	return jiu
}

// SetNillableShardTotal sets the "shard_total" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableShardTotal(i *int) *JobInstanceUpdate {
	if i != nil {
		jiu.SetShardTotal(*i)
	}
	return jiu
}

// AddShardTotal adds i to the "shard_total" field.
func (jiu *JobInstanceUpdate) AddShardTotal(i int) *JobInstanceUpdate {
	jiu.mutation.AddShardTotal(i)
	return jiu
}

// SetSuccessShards sets the "success_shards" field.
func (jiu *JobInstanceUpdate) SetSuccessShards(i int) *JobInstanceUpdate {
	jiu.mutation.ResetSuccessShards()
	jiu.mutation.SetSuccessShards(i)
	return jiu
}

// SetNillableSuccessShards sets the "success_shards" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableSuccessShards(i *int) *JobInstanceUpdate {
	if i != nil {
		jiu.SetSuccessShards(*i)
	}
	return jiu
}

// AddSuccessShards adds i to the "success_shards" field.
func (jiu *JobInstanceUpdate) AddSuccessShards(i int) *JobInstanceUpdate {
	jiu.mutation.AddSuccessShards(i)
	return jiu
}

// SetFailedShards sets the "failed_shards" field.
func (jiu *JobInstanceUpdate) SetFailedShards(i int) *JobInstanceUpdate {
	jiu.mutation.ResetFailedShards()
	jiu.mutation.SetFailedShards(i)
	return jiu
}

// SetNillableFailedShards sets the "failed_shards" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableFailedShards(i *int) *JobInstanceUpdate {
	if i != nil {
		jiu.SetFailedShards(*i)
	}
	return jiu
}

// AddFailedShards adds i to the "failed_shards" field.
func (jiu *JobInstanceUpdate) AddFailedShards(i int) *JobInstanceUpdate {
	jiu.mutation.AddFailedShards(i)
	return jiu
}

// SetPayload sets the "payload" field.
func (jiu *JobInstanceUpdate) SetPayload(s string) *JobInstanceUpdate {
	jiu.mutation.SetPayload(s)
	return jiu
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillablePayload(s *string) *JobInstanceUpdate {
	if s != nil {
		jiu.SetPayload(*s)
	}
	return jiu
}

// ClearPayload clears the value of the "payload" field.
func (jiu *JobInstanceUpdate) ClearPayload() *JobInstanceUpdate {
	jiu.mutation.ClearPayload()
	return jiu
}

// SetResultSummary sets the "result_summary" field.
func (jiu *JobInstanceUpdate) SetResultSummary(s string) *JobInstanceUpdate {
	jiu.mutation.SetResultSummary(s)
	return jiu
}

// SetNillableResultSummary sets the "result_summary" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableResultSummary(s *string) *JobInstanceUpdate {
	if s != nil {
		jiu.SetResultSummary(*s)
	}
	return jiu
}

// ClearResultSummary clears the value of the "result_summary" field.
func (jiu *JobInstanceUpdate) ClearResultSummary() *JobInstanceUpdate {
	jiu.mutation.ClearResultSummary()
	return jiu
}

// SetErrorCode sets the "error_code" field.
func (jiu *JobInstanceUpdate) SetErrorCode(s string) *JobInstanceUpdate {
	jiu.mutation.SetErrorCode(s)
	return jiu
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableErrorCode(s *string) *JobInstanceUpdate {
	if s != nil {
		jiu.SetErrorCode(*s)
	}
	return jiu
}

// ClearErrorCode clears the value of the "error_code" field.
func (jiu *JobInstanceUpdate) ClearErrorCode() *JobInstanceUpdate {
	jiu.mutation.ClearErrorCode()
	return jiu
}

// SetErrorMessage sets the "error_message" field.
func (jiu *JobInstanceUpdate) SetErrorMessage(s string) *JobInstanceUpdate {
	jiu.mutation.SetErrorMessage(s)
	return jiu
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (jiu *JobInstanceUpdate) SetNillableErrorMessage(s *string) *JobInstanceUpdate {
	if s != nil {
		jiu.SetErrorMessage(*s)
	}
	return jiu
}

// ClearErrorMessage clears the value of the "error_message" field.
func (jiu *JobInstanceUpdate) ClearErrorMessage() *JobInstanceUpdate {
	jiu.mutation.ClearErrorMessage()
	return jiu
}

// Mutation returns the JobInstanceMutation object of the builder.
func (jiu *JobInstanceUpdate) Mutation() *JobInstanceMutation {
	return jiu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (jiu *JobInstanceUpdate) Save(ctx context.Context) (int, error) {
	jiu.defaults()
	return withHooks(ctx, jiu.sqlSave, jiu.mutation, jiu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (jiu *JobInstanceUpdate) SaveX(ctx context.Context) int {
	affected, err := jiu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (jiu *JobInstanceUpdate) Exec(ctx context.Context) error {
	_, err := jiu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jiu *JobInstanceUpdate) ExecX(ctx context.Context) {
	if err := jiu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jiu *JobInstanceUpdate) defaults() {
	if _, ok := jiu.mutation.UpdatedAt(); !ok {
		v := jobinstance.UpdateDefaultUpdatedAt()
		jiu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jiu *JobInstanceUpdate) check() error {
	if v, ok := jiu.mutation.InstanceNo(); ok {
		if err := jobinstance.InstanceNoValidator(v); err != nil {
			return &ValidationError{Name: "instance_no", err: fmt.Errorf(`ent: validator failed for field "JobInstance.instance_no": %w`, err)}
		}
	}
	if v, ok := jiu.mutation.TriggerType(); ok {
		if err := jobinstance.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "JobInstance.trigger_type": %w`, err)}
		}
	}
	if v, ok := jiu.mutation.Status(); ok {
		if err := jobinstance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "JobInstance.status": %w`, err)}
		}
	}
	if v, ok := jiu.mutation.ResultSummary(); ok {
		if err := jobinstance.ResultSummaryValidator(v); err != nil {
			return &ValidationError{Name: "result_summary", err: fmt.Errorf(`ent: validator failed for field "JobInstance.result_summary": %w`, err)}
		}
	}
	if v, ok := jiu.mutation.ErrorCode(); ok {
		if err := jobinstance.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "JobInstance.error_code": %w`, err)}
		}
	}
	if v, ok := jiu.mutation.ErrorMessage(); ok {
		if err := jobinstance.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "JobInstance.error_message": %w`, err)}
		}
	}
	return nil
}

func (jiu *JobInstanceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := jiu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(jobinstance.Table, jobinstance.Columns, sqlgraph.NewFieldSpec(jobinstance.FieldID, field.TypeInt))
	if ps := jiu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := jiu.mutation.UpdatedAt(); ok {
		_spec.SetField(jobinstance.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := jiu.mutation.DeletedAt(); ok {
		_spec.SetField(jobinstance.FieldDeletedAt, field.TypeTime, value)
	}
	if jiu.mutation.DeletedAtCleared() {
		_spec.ClearField(jobinstance.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := jiu.mutation.InstanceNo(); ok {
		_spec.SetField(jobinstance.FieldInstanceNo, field.TypeString, value)
	}
	if value, ok := jiu.mutation.JobID(); ok {
		_spec.SetField(jobinstance.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := jiu.mutation.AddedJobID(); ok {
		_spec.AddField(jobinstance.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := jiu.mutation.WorkflowID(); ok {
		_spec.SetField(jobinstance.FieldWorkflowID, field.TypeInt64, value)
	}
	if value, ok := jiu.mutation.AddedWorkflowID(); ok {
		_spec.AddField(jobinstance.FieldWorkflowID, field.TypeInt64, value)
	}
	if jiu.mutation.WorkflowIDCleared() {
		_spec.ClearField(jobinstance.FieldWorkflowID, field.TypeInt64)
	}
	if value, ok := jiu.mutation.TriggerType(); ok {
		_spec.SetField(jobinstance.FieldTriggerType, field.TypeString, value)
	}
	if value, ok := jiu.mutation.TriggerTime(); ok {
		_spec.SetField(jobinstance.FieldTriggerTime, field.TypeTime, value)
	}
	if value, ok := jiu.mutation.ScheduledTime(); ok {
		_spec.SetField(jobinstance.FieldScheduledTime, field.TypeTime, value)
	}
	if value, ok := jiu.mutation.DispatchTime(); ok {
		_spec.SetField(jobinstance.FieldDispatchTime, field.TypeTime, value)
	}
	if jiu.mutation.DispatchTimeCleared() {
		_spec.ClearField(jobinstance.FieldDispatchTime, field.TypeTime)
	}
	if value, ok := jiu.mutation.StartTime(); ok {
		_spec.SetField(jobinstance.FieldStartTime, field.TypeTime, value)
	}
	if jiu.mutation.StartTimeCleared() {
		_spec.ClearField(jobinstance.FieldStartTime, field.TypeTime)
	}
	if value, ok := jiu.mutation.FinishTime(); ok {
		_spec.SetField(jobinstance.FieldFinishTime, field.TypeTime, value)
	}
	if jiu.mutation.FinishTimeCleared() {
		_spec.ClearField(jobinstance.FieldFinishTime, field.TypeTime)
	}
	if value, ok := jiu.mutation.Status(); ok {
		_spec.SetField(jobinstance.FieldStatus, field.TypeString, value)
	}
	if value, ok := jiu.mutation.RetryCount(); ok {
		_spec.SetField(jobinstance.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := jiu.mutation.AddedRetryCount(); ok {
		_spec.AddField(jobinstance.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := jiu.mutation.CurrentBackoffMs(); ok {
		_spec.SetField(jobinstance.FieldCurrentBackoffMs, field.TypeInt64, value)
	}
	if value, ok := jiu.mutation.AddedCurrentBackoffMs(); ok {
		_spec.AddField(jobinstance.FieldCurrentBackoffMs, field.TypeInt64, value)
	}
	if value, ok := jiu.mutation.ExecutorID(); ok {
		_spec.SetField(jobinstance.FieldExecutorID, field.TypeInt64, value)
	}
	if value, ok := jiu.mutation.AddedExecutorID(); ok {
		_spec.AddField(jobinstance.FieldExecutorID, field.TypeInt64, value)
	}
	if jiu.mutation.ExecutorIDCleared() {
		_spec.ClearField(jobinstance.FieldExecutorID, field.TypeInt64)
	}
	if value, ok := jiu.mutation.ShardTotal(); ok {
		_spec.SetField(jobinstance.FieldShardTotal, field.TypeInt, value)
	}
	if value, ok := jiu.mutation.AddedShardTotal(); ok {
		_spec.AddField(jobinstance.FieldShardTotal, field.TypeInt, value)
	}
	if value, ok := jiu.mutation.SuccessShards(); ok {
		_spec.SetField(jobinstance.FieldSuccessShards, field.TypeInt, value)
	}
	if value, ok := jiu.mutation.AddedSuccessShards(); ok {
		_spec.AddField(jobinstance.FieldSuccessShards, field.TypeInt, value)
	}
	if value, ok := jiu.mutation.FailedShards(); ok {
		_spec.SetField(jobinstance.FieldFailedShards, field.TypeInt, value)
	}
	if value, ok := jiu.mutation.AddedFailedShards(); ok {
		_spec.AddField(jobinstance.FieldFailedShards, field.TypeInt, value)
	}
	if value, ok := jiu.mutation.Payload(); ok {
		_spec.SetField(jobinstance.FieldPayload, field.TypeString, value)
	}
	if jiu.mutation.PayloadCleared() {
		_spec.ClearField(jobinstance.FieldPayload, field.TypeString)
	}
	if value, ok := jiu.mutation.ResultSummary(); ok {
		_spec.SetField(jobinstance.FieldResultSummary, field.TypeString, value)
	}
	if jiu.mutation.ResultSummaryCleared() {
		_spec.ClearField(jobinstance.FieldResultSummary, field.TypeString)
	}
	if value, ok := jiu.mutation.ErrorCode(); ok {
		_spec.SetField(jobinstance.FieldErrorCode, field.TypeString, value)
	}
	if jiu.mutation.ErrorCodeCleared() {
		_spec.ClearField(jobinstance.FieldErrorCode, field.TypeString)
	}
	if value, ok := jiu.mutation.ErrorMessage(); ok {
		_spec.SetField(jobinstance.FieldErrorMessage, field.TypeString, value)
	}
	if jiu.mutation.ErrorMessageCleared() {
		_spec.ClearField(jobinstance.FieldErrorMessage, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, jiu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jobinstance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	jiu.mutation.done = true
	return n, nil
}

// JobInstanceUpdateOne is the builder for updating a single JobInstance entity.
type JobInstanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobInstanceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (jiuo *JobInstanceUpdateOne) SetUpdatedAt(t time.Time) *JobInstanceUpdateOne {
	jiuo.mutation.SetUpdatedAt(t)
	return jiuo
}

// SetDeletedAt sets the "deleted_at" field.
func (jiuo *JobInstanceUpdateOne) SetDeletedAt(t time.Time) *JobInstanceUpdateOne {
	jiuo.mutation.SetDeletedAt(t)
	return jiuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableDeletedAt(t *time.Time) *JobInstanceUpdateOne {
	if t != nil {
		jiuo.SetDeletedAt(*t)
	}
	return jiuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (jiuo *JobInstanceUpdateOne) ClearDeletedAt() *JobInstanceUpdateOne {
	jiuo.mutation.ClearDeletedAt()
	return jiuo
}

// SetInstanceNo sets the "instance_no" field.
func (jiuo *JobInstanceUpdateOne) SetInstanceNo(s string) *JobInstanceUpdateOne {
	jiuo.mutation.SetInstanceNo(s)
	return jiuo
}

// SetNillableInstanceNo sets the "instance_no" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableInstanceNo(s *string) *JobInstanceUpdateOne {
	if s != nil {
		jiuo.SetInstanceNo(*s)
	}
	return jiuo
}

// SetJobID sets the "job_id" field.
func (jiuo *JobInstanceUpdateOne) SetJobID(i int64) *JobInstanceUpdateOne {
	jiuo.mutation.ResetJobID()
	jiuo.mutation.SetJobID(i)
	return jiuo
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableJobID(i *int64) *JobInstanceUpdateOne {
	if i != nil {
		jiuo.SetJobID(*i)
	}
	return jiuo
}

// AddJobID adds i to the "job_id" field.
func (jiuo *JobInstanceUpdateOne) AddJobID(i int64) *JobInstanceUpdateOne {
	jiuo.mutation.AddJobID(i)
	return jiuo
}

// SetWorkflowID sets the "workflow_id" field.
func (jiuo *JobInstanceUpdateOne) SetWorkflowID(i int64) *JobInstanceUpdateOne {
	jiuo.mutation.ResetWorkflowID()
	jiuo.mutation.SetWorkflowID(i)
	return jiuo
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableWorkflowID(i *int64) *JobInstanceUpdateOne {
	if i != nil {
		jiuo.SetWorkflowID(*i)
	}
	return jiuo
}

// AddWorkflowID adds i to the "workflow_id" field.
func (jiuo *JobInstanceUpdateOne) AddWorkflowID(i int64) *JobInstanceUpdateOne {
	jiuo.mutation.AddWorkflowID(i)
	return jiuo
}

// ClearWorkflowID clears the value of the "workflow_id" field.
func (jiuo *JobInstanceUpdateOne) ClearWorkflowID() *JobInstanceUpdateOne {
	jiuo.mutation.ClearWorkflowID()
	return jiuo
}

// SetTriggerType sets the "trigger_type" field.
func (jiuo *JobInstanceUpdateOne) SetTriggerType(s string) *JobInstanceUpdateOne {
	jiuo.mutation.SetTriggerType(s)
	return jiuo
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableTriggerType(s *string) *JobInstanceUpdateOne {
	if s != nil {
		jiuo.SetTriggerType(*s)
	}
	return jiuo
}

// SetTriggerTime sets the "trigger_time" field.
func (jiuo *JobInstanceUpdateOne) SetTriggerTime(t time.Time) *JobInstanceUpdateOne {
	jiuo.mutation.SetTriggerTime(t)
	return jiuo
}

// SetNillableTriggerTime sets the "trigger_time" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableTriggerTime(t *time.Time) *JobInstanceUpdateOne {
	if t != nil {
		jiuo.SetTriggerTime(*t)
	}
	return jiuo
}

// SetScheduledTime sets the "scheduled_time" field.
func (jiuo *JobInstanceUpdateOne) SetScheduledTime(t time.Time) *JobInstanceUpdateOne {
	jiuo.mutation.SetScheduledTime(t)
	return jiuo
}

// SetNillableScheduledTime sets the "scheduled_time" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableScheduledTime(t *time.Time) *JobInstanceUpdateOne {
	if t != nil {
		jiuo.SetScheduledTime(*t)
	}
	return jiuo
}

// SetDispatchTime sets the "dispatch_time" field.
func (jiuo *JobInstanceUpdateOne) SetDispatchTime(t time.Time) *JobInstanceUpdateOne {
	jiuo.mutation.SetDispatchTime(t)
	return jiuo
}

// SetNillableDispatchTime sets the "dispatch_time" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableDispatchTime(t *time.Time) *JobInstanceUpdateOne {
	if t != nil {
		jiuo.SetDispatchTime(*t)
	}
	return jiuo
}

// ClearDispatchTime clears the value of the "dispatch_time" field.
func (jiuo *JobInstanceUpdateOne) ClearDispatchTime() *JobInstanceUpdateOne {
	jiuo.mutation.ClearDispatchTime()
	return jiuo
}

// SetStartTime sets the "start_time" field.
func (jiuo *JobInstanceUpdateOne) SetStartTime(t time.Time) *JobInstanceUpdateOne {
	jiuo.mutation.SetStartTime(t)
	return jiuo
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableStartTime(t *time.Time) *JobInstanceUpdateOne {
	if t != nil {
		jiuo.SetStartTime(*t)
	}
	return jiuo
}

// ClearStartTime clears the value of the "start_time" field.
func (jiuo *JobInstanceUpdateOne) ClearStartTime() *JobInstanceUpdateOne {
	jiuo.mutation.ClearStartTime()
	return jiuo
}

// SetFinishTime sets the "finish_time" field.
func (jiuo *JobInstanceUpdateOne) SetFinishTime(t time.Time) *JobInstanceUpdateOne {
	jiuo.mutation.SetFinishTime(t)
	return jiuo
}

// SetNillableFinishTime sets the "finish_time" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableFinishTime(t *time.Time) *JobInstanceUpdateOne {
	if t != nil {
		jiuo.SetFinishTime(*t)
	}
	return jiuo
}

// ClearFinishTime clears the value of the "finish_time" field.
func (jiuo *JobInstanceUpdateOne) ClearFinishTime() *JobInstanceUpdateOne {
	jiuo.mutation.ClearFinishTime()
	return jiuo
}

// SetStatus sets the "status" field.
func (jiuo *JobInstanceUpdateOne) SetStatus(s string) *JobInstanceUpdateOne {
	jiuo.mutation.SetStatus(s)
	return jiuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableStatus(s *string) *JobInstanceUpdateOne {
	if s != nil {
		jiuo.SetStatus(*s)
	}
	return jiuo
}

// SetRetryCount sets the "retry_count" field.
func (jiuo *JobInstanceUpdateOne) SetRetryCount(i int) *JobInstanceUpdateOne {
	jiuo.mutation.ResetRetryCount()
	jiuo.mutation.SetRetryCount(i)
	return jiuo
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableRetryCount(i *int) *JobInstanceUpdateOne {
	if i != nil {
		jiuo.SetRetryCount(*i)
	}
	return jiuo
}

// AddRetryCount adds i to the "retry_count" field.
func (jiuo *JobInstanceUpdateOne) AddRetryCount(i int) *JobInstanceUpdateOne {
	jiuo.mutation.AddRetryCount(i)
	return jiuo
}

// SetCurrentBackoffMs sets the "current_backoff_ms" field.
func (jiuo *JobInstanceUpdateOne) SetCurrentBackoffMs(i int64) *JobInstanceUpdateOne {
	jiuo.mutation.ResetCurrentBackoffMs()
	jiuo.mutation.SetCurrentBackoffMs(i)
	return jiuo
}

// SetNillableCurrentBackoffMs sets the "current_backoff_ms" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableCurrentBackoffMs(i *int64) *JobInstanceUpdateOne {
	if i != nil {
		jiuo.SetCurrentBackoffMs(*i)
	}
	return jiuo
}

// AddCurrentBackoffMs adds i to the "current_backoff_ms" field.
func (jiuo *JobInstanceUpdateOne) AddCurrentBackoffMs(i int64) *JobInstanceUpdateOne {
	jiuo.mutation.AddCurrentBackoffMs(i)
	return jiuo
}

// SetExecutorID sets the "executor_id" field.
func (jiuo *JobInstanceUpdateOne) SetExecutorID(i int64) *JobInstanceUpdateOne {
	jiuo.mutation.ResetExecutorID()
	jiuo.mutation.SetExecutorID(i)
	return jiuo
}

// SetNillableExecutorID sets the "executor_id" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableExecutorID(i *int64) *JobInstanceUpdateOne {
	if i != nil {
		jiuo.SetExecutorID(*i)
	}
	return jiuo
}

// AddExecutorID adds i to the "executor_id" field.
func (jiuo *JobInstanceUpdateOne) AddExecutorID(i int64) *JobInstanceUpdateOne {
	jiuo.mutation.AddExecutorID(i)
	return jiuo
}

// ClearExecutorID clears the value of the "executor_id" field.
func (jiuo *JobInstanceUpdateOne) ClearExecutorID() *JobInstanceUpdateOne {
	jiuo.mutation.ClearExecutorID()
	return jiuo
}

// SetShardTotal sets the "shard_total" field.
func (jiuo *JobInstanceUpdateOne) SetShardTotal(i int) *JobInstanceUpdateOne {
	jiuo.mutation.ResetShardTotal()
	jiuo.mutation.SetShardTotal(i)
	return jiuo
}

// SetNillableShardTotal sets the "shard_total" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableShardTotal(i *int) *JobInstanceUpdateOne {
	if i != nil {
		jiuo.SetShardTotal(*i)
	}
	return jiuo
}

// AddShardTotal adds i to the "shard_total" field.
func (jiuo *JobInstanceUpdateOne) AddShardTotal(i int) *JobInstanceUpdateOne {
	jiuo.mutation.AddShardTotal(i)
	return jiuo
}

// SetSuccessShards sets the "success_shards" field.
func (jiuo *JobInstanceUpdateOne) SetSuccessShards(i int) *JobInstanceUpdateOne {
	jiuo.mutation.ResetSuccessShards()
	jiuo.mutation.SetSuccessShards(i)
	return jiuo
}

// SetNillableSuccessShards sets the "success_shards" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableSuccessShards(i *int) *JobInstanceUpdateOne {
	if i != nil {
		jiuo.SetSuccessShards(*i)
	}
	return jiuo
}

// AddSuccessShards adds i to the "success_shards" field.
func (jiuo *JobInstanceUpdateOne) AddSuccessShards(i int) *JobInstanceUpdateOne {
	jiuo.mutation.AddSuccessShards(i)
	return jiuo
}

// SetFailedShards sets the "failed_shards" field.
func (jiuo *JobInstanceUpdateOne) SetFailedShards(i int) *JobInstanceUpdateOne {
	jiuo.mutation.ResetFailedShards()
	jiuo.mutation.SetFailedShards(i)
	return jiuo
}

// SetNillableFailedShards sets the "failed_shards" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableFailedShards(i *int) *JobInstanceUpdateOne {
	if i != nil {
		jiuo.SetFailedShards(*i)
	}
	return jiuo
}

// AddFailedShards adds i to the "failed_shards" field.
func (jiuo *JobInstanceUpdateOne) AddFailedShards(i int) *JobInstanceUpdateOne {
	jiuo.mutation.AddFailedShards(i)
	return jiuo
}

// SetPayload sets the "payload" field.
func (jiuo *JobInstanceUpdateOne) SetPayload(s string) *JobInstanceUpdateOne {
	jiuo.mutation.SetPayload(s)
	return jiuo
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillablePayload(s *string) *JobInstanceUpdateOne {
	if s != nil {
		jiuo.SetPayload(*s)
	}
	return jiuo
}

// ClearPayload clears the value of the "payload" field.
func (jiuo *JobInstanceUpdateOne) ClearPayload() *JobInstanceUpdateOne {
	jiuo.mutation.ClearPayload()
	return jiuo
}

// SetResultSummary sets the "result_summary" field.
func (jiuo *JobInstanceUpdateOne) SetResultSummary(s string) *JobInstanceUpdateOne {
	jiuo.mutation.SetResultSummary(s)
	return jiuo
}

// SetNillableResultSummary sets the "result_summary" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableResultSummary(s *string) *JobInstanceUpdateOne {
	if s != nil {
		jiuo.SetResultSummary(*s)
	}
	return jiuo
}

// ClearResultSummary clears the value of the "result_summary" field.
func (jiuo *JobInstanceUpdateOne) ClearResultSummary() *JobInstanceUpdateOne {
	jiuo.mutation.ClearResultSummary()
	return jiuo
}

// SetErrorCode sets the "error_code" field.
func (jiuo *JobInstanceUpdateOne) SetErrorCode(s string) *JobInstanceUpdateOne {
	jiuo.mutation.SetErrorCode(s)
	return jiuo
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableErrorCode(s *string) *JobInstanceUpdateOne {
	if s != nil {
		jiuo.SetErrorCode(*s)
	}
	return jiuo
}

// ClearErrorCode clears the value of the "error_code" field.
func (jiuo *JobInstanceUpdateOne) ClearErrorCode() *JobInstanceUpdateOne {
	jiuo.mutation.ClearErrorCode()
	return jiuo
}

// SetErrorMessage sets the "error_message" field.
func (jiuo *JobInstanceUpdateOne) SetErrorMessage(s string) *JobInstanceUpdateOne {
	jiuo.mutation.SetErrorMessage(s)
	return jiuo
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (jiuo *JobInstanceUpdateOne) SetNillableErrorMessage(s *string) *JobInstanceUpdateOne {
	if s != nil {
		jiuo.SetErrorMessage(*s)
	}
	return jiuo
}

// ClearErrorMessage clears the value of the "error_message" field.
func (jiuo *JobInstanceUpdateOne) ClearErrorMessage() *JobInstanceUpdateOne {
	jiuo.mutation.ClearErrorMessage()
	return jiuo
}

// Mutation returns the JobInstanceMutation object of the builder.
func (jiuo *JobInstanceUpdateOne) Mutation() *JobInstanceMutation {
	return jiuo.mutation
}

// Where appends a list predicates to the JobInstanceUpdate builder.
func (jiuo *JobInstanceUpdateOne) Where(ps ...predicate.JobInstance) *JobInstanceUpdateOne {
	jiuo.mutation.Where(ps...)
	return jiuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (jiuo *JobInstanceUpdateOne) Select(field string, fields ...string) *JobInstanceUpdateOne {
	jiuo.fields = append([]string{field}, fields...)
	return jiuo
}

// Save executes the query and returns the updated JobInstance entity.
func (jiuo *JobInstanceUpdateOne) Save(ctx context.Context) (*JobInstance, error) {
	jiuo.defaults()
	return withHooks(ctx, jiuo.sqlSave, jiuo.mutation, jiuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (jiuo *JobInstanceUpdateOne) SaveX(ctx context.Context) *JobInstance {
	node, err := jiuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (jiuo *JobInstanceUpdateOne) Exec(ctx context.Context) error {
	_, err := jiuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jiuo *JobInstanceUpdateOne) ExecX(ctx context.Context) {
	if err := jiuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jiuo *JobInstanceUpdateOne) defaults() {
	if _, ok := jiuo.mutation.UpdatedAt(); !ok {
		v := jobinstance.UpdateDefaultUpdatedAt()
		jiuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jiuo *JobInstanceUpdateOne) check() error {
	if v, ok := jiuo.mutation.InstanceNo(); ok {
		if err := jobinstance.InstanceNoValidator(v); err != nil {
			return &ValidationError{Name: "instance_no", err: fmt.Errorf(`ent: validator failed for field "JobInstance.instance_no": %w`, err)}
		}
	}
	if v, ok := jiuo.mutation.TriggerType(); ok {
		if err := jobinstance.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "JobInstance.trigger_type": %w`, err)}
		}
	}
	if v, ok := jiuo.mutation.Status(); ok {
		if err := jobinstance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "JobInstance.status": %w`, err)}
		}
	}
	if v, ok := jiuo.mutation.ResultSummary(); ok {
		if err := jobinstance.ResultSummaryValidator(v); err != nil {
			return &ValidationError{Name: "result_summary", err: fmt.Errorf(`ent: validator failed for field "JobInstance.result_summary": %w`, err)}
		}
	}
	if v, ok := jiuo.mutation.ErrorCode(); ok {
		if err := jobinstance.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "JobInstance.error_code": %w`, err)}
		}
	}
	if v, ok := jiuo.mutation.ErrorMessage(); ok {
		if err := jobinstance.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "JobInstance.error_message": %w`, err)}
		}
	}
	return nil
}

func (jiuo *JobInstanceUpdateOne) sqlSave(ctx context.Context) (_node *JobInstance, err error) {
	if err := jiuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(jobinstance.Table, jobinstance.Columns, sqlgraph.NewFieldSpec(jobinstance.FieldID, field.TypeInt))
	id, ok := jiuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "JobInstance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := jiuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobinstance.FieldID)
		for _, f := range fields {
			if !jobinstance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != jobinstance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := jiuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := jiuo.mutation.UpdatedAt(); ok {
		_spec.SetField(jobinstance.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := jiuo.mutation.DeletedAt(); ok {
		_spec.SetField(jobinstance.FieldDeletedAt, field.TypeTime, value)
	}
	if jiuo.mutation.DeletedAtCleared() {
		_spec.ClearField(jobinstance.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := jiuo.mutation.InstanceNo(); ok {
		_spec.SetField(jobinstance.FieldInstanceNo, field.TypeString, value)
	}
	if value, ok := jiuo.mutation.JobID(); ok {
		_spec.SetField(jobinstance.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := jiuo.mutation.AddedJobID(); ok {
		_spec.AddField(jobinstance.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := jiuo.mutation.WorkflowID(); ok {
		_spec.SetField(jobinstance.FieldWorkflowID, field.TypeInt64, value)
	}
	if value, ok := jiuo.mutation.AddedWorkflowID(); ok {
		_spec.AddField(jobinstance.FieldWorkflowID, field.TypeInt64, value)
	}
	if jiuo.mutation.WorkflowIDCleared() {
		_spec.ClearField(jobinstance.FieldWorkflowID, field.TypeInt64)
	}
	if value, ok := jiuo.mutation.TriggerType(); ok {
		_spec.SetField(jobinstance.FieldTriggerType, field.TypeString, value)
	}
	if value, ok := jiuo.mutation.TriggerTime(); ok {
		_spec.SetField(jobinstance.FieldTriggerTime, field.TypeTime, value)
	}
	if value, ok := jiuo.mutation.ScheduledTime(); ok {
		_spec.SetField(jobinstance.FieldScheduledTime, field.TypeTime, value)
	}
	if value, ok := jiuo.mutation.DispatchTime(); ok {
		_spec.SetField(jobinstance.FieldDispatchTime, field.TypeTime, value)
	}
	if jiuo.mutation.DispatchTimeCleared() {
		_spec.ClearField(jobinstance.FieldDispatchTime, field.TypeTime)
	}
	if value, ok := jiuo.mutation.StartTime(); ok {
		_spec.SetField(jobinstance.FieldStartTime, field.TypeTime, value)
	}
	if jiuo.mutation.StartTimeCleared() {
		_spec.ClearField(jobinstance.FieldStartTime, field.TypeTime)
	}
	if value, ok := jiuo.mutation.FinishTime(); ok {
		_spec.SetField(jobinstance.FieldFinishTime, field.TypeTime, value)
	}
	if jiuo.mutation.FinishTimeCleared() {
		_spec.ClearField(jobinstance.FieldFinishTime, field.TypeTime)
	}
	if value, ok := jiuo.mutation.Status(); ok {
		_spec.SetField(jobinstance.FieldStatus, field.TypeString, value)
	}
	if value, ok := jiuo.mutation.RetryCount(); ok {
		_spec.SetField(jobinstance.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := jiuo.mutation.AddedRetryCount(); ok {
		_spec.AddField(jobinstance.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := jiuo.mutation.CurrentBackoffMs(); ok {
		_spec.SetField(jobinstance.FieldCurrentBackoffMs, field.TypeInt64, value)
	}
	if value, ok := jiuo.mutation.AddedCurrentBackoffMs(); ok {
		_spec.AddField(jobinstance.FieldCurrentBackoffMs, field.TypeInt64, value)
	}
	if value, ok := jiuo.mutation.ExecutorID(); ok {
		_spec.SetField(jobinstance.FieldExecutorID, field.TypeInt64, value)
	}
	if value, ok := jiuo.mutation.AddedExecutorID(); ok {
		_spec.AddField(jobinstance.FieldExecutorID, field.TypeInt64, value)
	}
	if jiuo.mutation.ExecutorIDCleared() {
		_spec.ClearField(jobinstance.FieldExecutorID, field.TypeInt64)
	}
	if value, ok := jiuo.mutation.ShardTotal(); ok {
		_spec.SetField(jobinstance.FieldShardTotal, field.TypeInt, value)
	}
	if value, ok := jiuo.mutation.AddedShardTotal(); ok {
		_spec.AddField(jobinstance.FieldShardTotal, field.TypeInt, value)
	}
	if value, ok := jiuo.mutation.SuccessShards(); ok {
		_spec.SetField(jobinstance.FieldSuccessShards, field.TypeInt, value)
	}
	if value, ok := jiuo.mutation.AddedSuccessShards(); ok {
		_spec.AddField(jobinstance.FieldSuccessShards, field.TypeInt, value)
	}
	if value, ok := jiuo.mutation.FailedShards(); ok {
		_spec.SetField(jobinstance.FieldFailedShards, field.TypeInt, value)
	}
	if value, ok := jiuo.mutation.AddedFailedShards(); ok {
		_spec.AddField(jobinstance.FieldFailedShards, field.TypeInt, value)
	}
	if value, ok := jiuo.mutation.Payload(); ok {
		_spec.SetField(jobinstance.FieldPayload, field.TypeString, value)
	}
	if jiuo.mutation.PayloadCleared() {
		_spec.ClearField(jobinstance.FieldPayload, field.TypeString)
	}
	if value, ok := jiuo.mutation.ResultSummary(); ok {
		_spec.SetField(jobinstance.FieldResultSummary, field.TypeString, value)
	}
	if jiuo.mutation.ResultSummaryCleared() {
		_spec.ClearField(jobinstance.FieldResultSummary, field.TypeString)
	}
	if value, ok := jiuo.mutation.ErrorCode(); ok {
		_spec.SetField(jobinstance.FieldErrorCode, field.TypeString, value)
	}
	if jiuo.mutation.ErrorCodeCleared() {
		_spec.ClearField(jobinstance.FieldErrorCode, field.TypeString)
	}
	if value, ok := jiuo.mutation.ErrorMessage(); ok {
		_spec.SetField(jobinstance.FieldErrorMessage, field.TypeString, value)
	}
	if jiuo.mutation.ErrorMessageCleared() {
		_spec.ClearField(jobinstance.FieldErrorMessage, field.TypeString)
	}
	_node = &JobInstance{config: jiuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, jiuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{jobinstance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	jiuo.mutation.done = true
	return _node, nil
}
