// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/jobshard"
)

// JobShard is the model entity for the JobShard schema.
type JobShard struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// InstanceID holds the value of the "instance_id" field.
	InstanceID int64 `json:"instance_id,omitempty"`
	// ShardNo holds the value of the "shard_no" field.
	ShardNo string `json:"shard_no,omitempty"`
	// ShardIndex holds the value of the "shard_index" field.
	ShardIndex int `json:"shard_index,omitempty"`
	// ShardTotal holds the value of the "shard_total" field.
	ShardTotal int `json:"shard_total,omitempty"`
	// RouteKey holds the value of the "route_key" field.
	RouteKey *string `json:"route_key,omitempty"`
	// ExecutorID holds the value of the "executor_id" field.
	ExecutorID *int64 `json:"executor_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload *string `json:"payload,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// StartTime holds the value of the "start_time" field.
	StartTime *time.Time `json:"start_time,omitempty"`
	// FinishTime holds the value of the "finish_time" field.
	FinishTime *time.Time `json:"finish_time,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JobShard) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case jobshard.FieldID, jobshard.FieldInstanceID, jobshard.FieldShardIndex, jobshard.FieldShardTotal, jobshard.FieldExecutorID, jobshard.FieldRetryCount:
			values[i] = new(sql.NullInt64)
		case jobshard.FieldShardNo, jobshard.FieldRouteKey, jobshard.FieldStatus, jobshard.FieldPayload, jobshard.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case jobshard.FieldCreatedAt, jobshard.FieldUpdatedAt, jobshard.FieldDeletedAt, jobshard.FieldStartTime, jobshard.FieldFinishTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JobShard fields.
func (js *JobShard) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case jobshard.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			js.ID = int(value.Int64)
		case jobshard.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				js.CreatedAt = value.Time
			}
		case jobshard.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				js.UpdatedAt = value.Time
			}
		case jobshard.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				js.DeletedAt = new(time.Time)
				*js.DeletedAt = value.Time
			}
		case jobshard.FieldInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field instance_id", values[i])
			} else if value.Valid {
				js.InstanceID = value.Int64
			}
		case jobshard.FieldShardNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field shard_no", values[i])
			} else if value.Valid {
				js.ShardNo = value.String
			}
		case jobshard.FieldShardIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field shard_index", values[i])
			} else if value.Valid {
				js.ShardIndex = int(value.Int64)
			}
		case jobshard.FieldShardTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field shard_total", values[i])
			} else if value.Valid {
				js.ShardTotal = int(value.Int64)
			}
		case jobshard.FieldRouteKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_key", values[i])
			} else if value.Valid {
				js.RouteKey = new(string)
				*js.RouteKey = value.String
			}
		case jobshard.FieldExecutorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field executor_id", values[i])
			} else if value.Valid {
				js.ExecutorID = new(int64)
				*js.ExecutorID = value.Int64
			}
		case jobshard.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				js.Status = value.String
			}
		case jobshard.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				js.Payload = new(string)
				*js.Payload = value.String
			}
		case jobshard.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				js.RetryCount = int(value.Int64)
			}
		case jobshard.FieldStartTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_time", values[i])
			} else if value.Valid {
				js.StartTime = new(time.Time)
				*js.StartTime = value.Time
			}
		case jobshard.FieldFinishTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finish_time", values[i])
			} else if value.Valid {
				js.FinishTime = new(time.Time)
				*js.FinishTime = value.Time
			}
		case jobshard.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				js.ErrorMessage = new(string)
				*js.ErrorMessage = value.String
			}
		default:
			js.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JobShard.
// This includes values selected through modifiers, order, etc.
func (js *JobShard) Value(name string) (ent.Value, error) {
	return js.selectValues.Get(name)
}

// Update returns a builder for updating this JobShard.
// Note that you need to call JobShard.Unwrap() before calling this method if this JobShard
// was returned from a transaction, and the transaction was committed or rolled back.
func (js *JobShard) Update() *JobShardUpdateOne {
	return NewJobShardClient(js.config).UpdateOne(js)
}

// Unwrap unwraps the JobShard entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (js *JobShard) Unwrap() *JobShard {
	_tx, ok := js.config.driver.(*txDriver)
	if !ok {
		panic("ent: JobShard is not a transactional entity")
	}
	js.config.driver = _tx.drv
	return js
}

// String implements the fmt.Stringer.
func (js *JobShard) String() string {
	var builder strings.Builder
	builder.WriteString("JobShard(")
	builder.WriteString(fmt.Sprintf("id=%v, ", js.ID))
	builder.WriteString("created_at=")
	builder.WriteString(js.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(js.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := js.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("instance_id=")
	builder.WriteString(fmt.Sprintf("%v", js.InstanceID))
	builder.WriteString(", ")
	builder.WriteString("shard_no=")
	builder.WriteString(js.ShardNo)
	builder.WriteString(", ")
	builder.WriteString("shard_index=")
	builder.WriteString(fmt.Sprintf("%v", js.ShardIndex))
	builder.WriteString(", ")
	builder.WriteString("shard_total=")
	builder.WriteString(fmt.Sprintf("%v", js.ShardTotal))
	builder.WriteString(", ")
	if v := js.RouteKey; v != nil {
		builder.WriteString("route_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := js.ExecutorID; v != nil {
		builder.WriteString("executor_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(js.Status)
	builder.WriteString(", ")
	if v := js.Payload; v != nil {
		builder.WriteString("payload=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", js.RetryCount))
	builder.WriteString(", ")
	if v := js.StartTime; v != nil {
		builder.WriteString("start_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := js.FinishTime; v != nil {
		builder.WriteString("finish_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := js.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// JobShards is a parsable slice of JobShard.
type JobShards []*JobShard
