// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/jobshard"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
)

// JobShardDelete is the builder for deleting a JobShard entity.
type JobShardDelete struct {
	config
	hooks    []Hook
	mutation *JobShardMutation
}

// Where appends a list predicates to the JobShardDelete builder.
func (jsd *JobShardDelete) Where(ps ...predicate.JobShard) *JobShardDelete {
	jsd.mutation.Where(ps...)
	return jsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (jsd *JobShardDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, jsd.sqlExec, jsd.mutation, jsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (jsd *JobShardDelete) ExecX(ctx context.Context) int {
	n, err := jsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (jsd *JobShardDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(jobshard.Table, sqlgraph.NewFieldSpec(jobshard.FieldID, field.TypeInt))
	if ps := jsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, jsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	jsd.mutation.done = true
	return affected, err
}

// JobShardDeleteOne is the builder for deleting a single JobShard entity.
type JobShardDeleteOne struct {
	jsd *JobShardDelete
}

// Where appends a list predicates to the JobShardDelete builder.
func (jsdo *JobShardDeleteOne) Where(ps ...predicate.JobShard) *JobShardDeleteOne {
	jsdo.jsd.mutation.Where(ps...)
	return jsdo
}

// Exec executes the deletion query.
func (jsdo *JobShardDeleteOne) Exec(ctx context.Context) error {
	n, err := jsdo.jsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{jobshard.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (jsdo *JobShardDeleteOne) ExecX(ctx context.Context) {
	if err := jsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
