// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/workflowinstance"
)

// WorkflowInstanceCreate is the builder for creating a WorkflowInstance entity.
type WorkflowInstanceCreate struct {
	config
	mutation *WorkflowInstanceMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (wic *WorkflowInstanceCreate) SetCreatedAt(t time.Time) *WorkflowInstanceCreate {
	wic.mutation.SetCreatedAt(t)
	return wic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wic *WorkflowInstanceCreate) SetNillableCreatedAt(t *time.Time) *WorkflowInstanceCreate {
	if t != nil {
		wic.SetCreatedAt(*t)
	}
	return wic
}

// SetUpdatedAt sets the "updated_at" field.
func (wic *WorkflowInstanceCreate) SetUpdatedAt(t time.Time) *WorkflowInstanceCreate {
	wic.mutation.SetUpdatedAt(t)
	return wic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wic *WorkflowInstanceCreate) SetNillableUpdatedAt(t *time.Time) *WorkflowInstanceCreate {
	if t != nil {
		wic.SetUpdatedAt(*t)
	}
	return wic
}

// SetDeletedAt sets the "deleted_at" field.
func (wic *WorkflowInstanceCreate) SetDeletedAt(t time.Time) *WorkflowInstanceCreate {
	wic.mutation.SetDeletedAt(t)
	return wic
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (wic *WorkflowInstanceCreate) SetNillableDeletedAt(t *time.Time) *WorkflowInstanceCreate {
	if t != nil {
		wic.SetDeletedAt(*t)
	}
	return wic
}

// SetWorkflowInstanceNo sets the "workflow_instance_no" field.
func (wic *WorkflowInstanceCreate) SetWorkflowInstanceNo(s string) *WorkflowInstanceCreate {
	wic.mutation.SetWorkflowInstanceNo(s)
	return wic
}

// SetWorkflowID sets the "workflow_id" field.
func (wic *WorkflowInstanceCreate) SetWorkflowID(i int64) *WorkflowInstanceCreate {
	wic.mutation.SetWorkflowID(i)
	return wic
}

// SetWorkflowCode sets the "workflow_code" field.
func (wic *WorkflowInstanceCreate) SetWorkflowCode(s string) *WorkflowInstanceCreate {
	wic.mutation.SetWorkflowCode(s)
	return wic
}

// SetStatus sets the "status" field.
func (wic *WorkflowInstanceCreate) SetStatus(s string) *WorkflowInstanceCreate {
	wic.mutation.SetStatus(s)
	return wic
}

// SetStartTime sets the "start_time" field.
func (wic *WorkflowInstanceCreate) SetStartTime(t time.Time) *WorkflowInstanceCreate {
	wic.mutation.SetStartTime(t)
	return wic
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (wic *WorkflowInstanceCreate) SetNillableStartTime(t *time.Time) *WorkflowInstanceCreate {
	if t != nil {
		wic.SetStartTime(*t)
	}
	return wic
}

// SetFinishTime sets the "finish_time" field.
func (wic *WorkflowInstanceCreate) SetFinishTime(t time.Time) *WorkflowInstanceCreate {
	wic.mutation.SetFinishTime(t)
	return wic
}

// SetNillableFinishTime sets the "finish_time" field if the given value is not nil.
func (wic *WorkflowInstanceCreate) SetNillableFinishTime(t *time.Time) *WorkflowInstanceCreate {
	if t != nil {
		wic.SetFinishTime(*t)
	}
	return wic
}

// SetErrorMessage sets the "error_message" field.
func (wic *WorkflowInstanceCreate) SetErrorMessage(s string) *WorkflowInstanceCreate {
	wic.mutation.SetErrorMessage(s)
	return wic
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (wic *WorkflowInstanceCreate) SetNillableErrorMessage(s *string) *WorkflowInstanceCreate {
	if s != nil {
		wic.SetErrorMessage(*s)
	}
	return wic
}

// Mutation returns the WorkflowInstanceMutation object of the builder.
func (wic *WorkflowInstanceCreate) Mutation() *WorkflowInstanceMutation {
	return wic.mutation
}

// Save creates the WorkflowInstance in the database.
func (wic *WorkflowInstanceCreate) Save(ctx context.Context) (*WorkflowInstance, error) {
	wic.defaults()
	return withHooks(ctx, wic.sqlSave, wic.mutation, wic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wic *WorkflowInstanceCreate) SaveX(ctx context.Context) *WorkflowInstance {
	v, err := wic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wic *WorkflowInstanceCreate) Exec(ctx context.Context) error {
	_, err := wic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wic *WorkflowInstanceCreate) ExecX(ctx context.Context) {
	if err := wic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wic *WorkflowInstanceCreate) defaults() {
	if _, ok := wic.mutation.CreatedAt(); !ok {
		v := workflowinstance.DefaultCreatedAt()
		wic.mutation.SetCreatedAt(v)
	}
	if _, ok := wic.mutation.UpdatedAt(); !ok {
		v := workflowinstance.DefaultUpdatedAt()
		wic.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wic *WorkflowInstanceCreate) check() error {
	if _, ok := wic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WorkflowInstance.created_at"`)}
	}
	if _, ok := wic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WorkflowInstance.updated_at"`)}
	}
	if _, ok := wic.mutation.WorkflowInstanceNo(); !ok {
		return &ValidationError{Name: "workflow_instance_no", err: errors.New(`ent: missing required field "WorkflowInstance.workflow_instance_no"`)}
	}
	if v, ok := wic.mutation.WorkflowInstanceNo(); ok {
		if err := workflowinstance.WorkflowInstanceNoValidator(v); err != nil {
			return &ValidationError{Name: "workflow_instance_no", err: fmt.Errorf(`ent: validator failed for field "WorkflowInstance.workflow_instance_no": %w`, err)}
		}
	}
	if _, ok := wic.mutation.WorkflowID(); !ok {
		return &ValidationError{Name: "workflow_id", err: errors.New(`ent: missing required field "WorkflowInstance.workflow_id"`)}
	}
	if _, ok := wic.mutation.WorkflowCode(); !ok {
		return &ValidationError{Name: "workflow_code", err: errors.New(`ent: missing required field "WorkflowInstance.workflow_code"`)}
	}
	if v, ok := wic.mutation.WorkflowCode(); ok {
		if err := workflowinstance.WorkflowCodeValidator(v); err != nil {
			return &ValidationError{Name: "workflow_code", err: fmt.Errorf(`ent: validator failed for field "WorkflowInstance.workflow_code": %w`, err)}
		}
	}
	if _, ok := wic.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WorkflowInstance.status"`)}
	}
	if v, ok := wic.mutation.Status(); ok {
		if err := workflowinstance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkflowInstance.status": %w`, err)}
		}
	}
	if v, ok := wic.mutation.ErrorMessage(); ok {
		if err := workflowinstance.ErrorMessageValidator(v); err != nil {
			return &ValidationError{Name: "error_message", err: fmt.Errorf(`ent: validator failed for field "WorkflowInstance.error_message": %w`, err)}
		}
	}
	return nil
}

func (wic *WorkflowInstanceCreate) sqlSave(ctx context.Context) (*WorkflowInstance, error) {
	if err := wic.check(); err != nil {
		return nil, err
	}
	_node, _spec := wic.createSpec()
	if err := sqlgraph.CreateNode(ctx, wic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	wic.mutation.id = &_node.ID
	wic.mutation.done = true
	return _node, nil
}

func (wic *WorkflowInstanceCreate) createSpec() (*WorkflowInstance, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkflowInstance{config: wic.config}
		_spec = sqlgraph.NewCreateSpec(workflowinstance.Table, sqlgraph.NewFieldSpec(workflowinstance.FieldID, field.TypeInt))
	)
	if value, ok := wic.mutation.CreatedAt(); ok {
		_spec.SetField(workflowinstance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := wic.mutation.UpdatedAt(); ok {
		_spec.SetField(workflowinstance.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := wic.mutation.DeletedAt(); ok {
		_spec.SetField(workflowinstance.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := wic.mutation.WorkflowInstanceNo(); ok {
		_spec.SetField(workflowinstance.FieldWorkflowInstanceNo, field.TypeString, value)
		_node.WorkflowInstanceNo = value
	}
	if value, ok := wic.mutation.WorkflowID(); ok {
		_spec.SetField(workflowinstance.FieldWorkflowID, field.TypeInt64, value)
		_node.WorkflowID = value
	}
	if value, ok := wic.mutation.WorkflowCode(); ok {
		_spec.SetField(workflowinstance.FieldWorkflowCode, field.TypeString, value)
		_node.WorkflowCode = value
	}
	if value, ok := wic.mutation.Status(); ok {
		_spec.SetField(workflowinstance.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := wic.mutation.StartTime(); ok {
		_spec.SetField(workflowinstance.FieldStartTime, field.TypeTime, value)
		_node.StartTime = &value
	}
	if value, ok := wic.mutation.FinishTime(); ok {
		_spec.SetField(workflowinstance.FieldFinishTime, field.TypeTime, value)
		_node.FinishTime = &value
	}
	if value, ok := wic.mutation.ErrorMessage(); ok {
		_spec.SetField(workflowinstance.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	return _node, _spec
}

// WorkflowInstanceCreateBulk is the builder for creating many WorkflowInstance entities in bulk.
type WorkflowInstanceCreateBulk struct {
	config
	err      error
	builders []*WorkflowInstanceCreate
}

// Save creates the WorkflowInstance entities in the database.
func (wicb *WorkflowInstanceCreateBulk) Save(ctx context.Context) ([]*WorkflowInstance, error) {
	if wicb.err != nil {
		return nil, wicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(wicb.builders))
	nodes := make([]*WorkflowInstance, len(wicb.builders))
	mutators := make([]Mutator, len(wicb.builders))
	for i := range wicb.builders {
		func(i int, root context.Context) {
			builder := wicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkflowInstanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wicb *WorkflowInstanceCreateBulk) SaveX(ctx context.Context) []*WorkflowInstance {
	v, err := wicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wicb *WorkflowInstanceCreateBulk) Exec(ctx context.Context) error {
	_, err := wicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wicb *WorkflowInstanceCreateBulk) ExecX(ctx context.Context) {
	if err := wicb.Exec(ctx); err != nil {
		panic(err)
	}
}
