// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/workflownodeinstance"
)

// WorkflowNodeInstanceQuery is the builder for querying WorkflowNodeInstance entities.
type WorkflowNodeInstanceQuery struct {
	config
	ctx        *QueryContext
	order      []workflownodeinstance.OrderOption
	inters     []Interceptor
	predicates []predicate.WorkflowNodeInstance
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorkflowNodeInstanceQuery builder.
func (wniq *WorkflowNodeInstanceQuery) Where(ps ...predicate.WorkflowNodeInstance) *WorkflowNodeInstanceQuery {
	wniq.predicates = append(wniq.predicates, ps...)
	return wniq
}

// Limit the number of records to be returned by this query.
func (wniq *WorkflowNodeInstanceQuery) Limit(limit int) *WorkflowNodeInstanceQuery {
	wniq.ctx.Limit = &limit
	return wniq
}

// Offset to start from.
func (wniq *WorkflowNodeInstanceQuery) Offset(offset int) *WorkflowNodeInstanceQuery {
	wniq.ctx.Offset = &offset
	return wniq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wniq *WorkflowNodeInstanceQuery) Unique(unique bool) *WorkflowNodeInstanceQuery {
	wniq.ctx.Unique = &unique
	return wniq
}

// Order specifies how the records should be ordered.
func (wniq *WorkflowNodeInstanceQuery) Order(o ...workflownodeinstance.OrderOption) *WorkflowNodeInstanceQuery {
	wniq.order = append(wniq.order, o...)
	return wniq
}

// First returns the first WorkflowNodeInstance entity from the query.
// Returns a *NotFoundError when no WorkflowNodeInstance was found.
func (wniq *WorkflowNodeInstanceQuery) First(ctx context.Context) (*WorkflowNodeInstance, error) {
	nodes, err := wniq.Limit(1).All(setContextOp(ctx, wniq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{workflownodeinstance.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wniq *WorkflowNodeInstanceQuery) FirstX(ctx context.Context) *WorkflowNodeInstance {
	node, err := wniq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WorkflowNodeInstance ID from the query.
// Returns a *NotFoundError when no WorkflowNodeInstance ID was found.
func (wniq *WorkflowNodeInstanceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wniq.Limit(1).IDs(setContextOp(ctx, wniq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{workflownodeinstance.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wniq *WorkflowNodeInstanceQuery) FirstIDX(ctx context.Context) int {
	id, err := wniq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WorkflowNodeInstance entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WorkflowNodeInstance entity is found.
// Returns a *NotFoundError when no WorkflowNodeInstance entities are found.
func (wniq *WorkflowNodeInstanceQuery) Only(ctx context.Context) (*WorkflowNodeInstance, error) {
	nodes, err := wniq.Limit(2).All(setContextOp(ctx, wniq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{workflownodeinstance.Label}
	default:
		return nil, &NotSingularError{workflownodeinstance.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wniq *WorkflowNodeInstanceQuery) OnlyX(ctx context.Context) *WorkflowNodeInstance {
	node, err := wniq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WorkflowNodeInstance ID in the query.
// Returns a *NotSingularError when more than one WorkflowNodeInstance ID is found.
// Returns a *NotFoundError when no entities are found.
func (wniq *WorkflowNodeInstanceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wniq.Limit(2).IDs(setContextOp(ctx, wniq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{workflownodeinstance.Label}
	default:
		err = &NotSingularError{workflownodeinstance.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wniq *WorkflowNodeInstanceQuery) OnlyIDX(ctx context.Context) int {
	id, err := wniq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WorkflowNodeInstances.
func (wniq *WorkflowNodeInstanceQuery) All(ctx context.Context) ([]*WorkflowNodeInstance, error) {
	ctx = setContextOp(ctx, wniq.ctx, "All")
	if err := wniq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WorkflowNodeInstance, *WorkflowNodeInstanceQuery]()
	return withInterceptors[[]*WorkflowNodeInstance](ctx, wniq, qr, wniq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wniq *WorkflowNodeInstanceQuery) AllX(ctx context.Context) []*WorkflowNodeInstance {
	nodes, err := wniq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WorkflowNodeInstance IDs.
func (wniq *WorkflowNodeInstanceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wniq.ctx.Unique == nil && wniq.path != nil {
		wniq.Unique(true)
	}
	ctx = setContextOp(ctx, wniq.ctx, "IDs")
	if err = wniq.Select(workflownodeinstance.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wniq *WorkflowNodeInstanceQuery) IDsX(ctx context.Context) []int {
	ids, err := wniq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wniq *WorkflowNodeInstanceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wniq.ctx, "Count")
	if err := wniq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wniq, querierCount[*WorkflowNodeInstanceQuery](), wniq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wniq *WorkflowNodeInstanceQuery) CountX(ctx context.Context) int {
	count, err := wniq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wniq *WorkflowNodeInstanceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wniq.ctx, "Exist")
	switch _, err := wniq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wniq *WorkflowNodeInstanceQuery) ExistX(ctx context.Context) bool {
	exist, err := wniq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorkflowNodeInstanceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wniq *WorkflowNodeInstanceQuery) Clone() *WorkflowNodeInstanceQuery {
	if wniq == nil {
		return nil
	}
	return &WorkflowNodeInstanceQuery{
		config:     wniq.config,
		ctx:        wniq.ctx.Clone(),
		order:      append([]workflownodeinstance.OrderOption{}, wniq.order...),
		inters:     append([]Interceptor{}, wniq.inters...),
		predicates: append([]predicate.WorkflowNodeInstance{}, wniq.predicates...),
		// clone intermediate query.
		sql:  wniq.sql.Clone(),
		path: wniq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WorkflowNodeInstance.Query().
//		GroupBy(workflownodeinstance.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wniq *WorkflowNodeInstanceQuery) GroupBy(field string, fields ...string) *WorkflowNodeInstanceGroupBy {
	wniq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorkflowNodeInstanceGroupBy{build: wniq}
	grbuild.flds = &wniq.ctx.Fields
	grbuild.label = workflownodeinstance.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.WorkflowNodeInstance.Query().
//		Select(workflownodeinstance.FieldCreatedAt).
//		Scan(ctx, &v)
func (wniq *WorkflowNodeInstanceQuery) Select(fields ...string) *WorkflowNodeInstanceSelect {
	wniq.ctx.Fields = append(wniq.ctx.Fields, fields...)
	sbuild := &WorkflowNodeInstanceSelect{WorkflowNodeInstanceQuery: wniq}
	sbuild.label = workflownodeinstance.Label
	sbuild.flds, sbuild.scan = &wniq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorkflowNodeInstanceSelect configured with the given aggregations.
func (wniq *WorkflowNodeInstanceQuery) Aggregate(fns ...AggregateFunc) *WorkflowNodeInstanceSelect {
	return wniq.Select().Aggregate(fns...)
}

func (wniq *WorkflowNodeInstanceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wniq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wniq); err != nil {
				return err
			}
		}
	}
	for _, f := range wniq.ctx.Fields {
		if !workflownodeinstance.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wniq.path != nil {
		prev, err := wniq.path(ctx)
		if err != nil {
			return err
		}
		wniq.sql = prev
	}
	return nil
}

func (wniq *WorkflowNodeInstanceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WorkflowNodeInstance, error) {
	var (
		nodes = []*WorkflowNodeInstance{}
		_spec = wniq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WorkflowNodeInstance).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WorkflowNodeInstance{config: wniq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wniq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wniq *WorkflowNodeInstanceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wniq.querySpec()
	_spec.Node.Columns = wniq.ctx.Fields
	if len(wniq.ctx.Fields) > 0 {
		_spec.Unique = wniq.ctx.Unique != nil && *wniq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wniq.driver, _spec)
}

func (wniq *WorkflowNodeInstanceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(workflownodeinstance.Table, workflownodeinstance.Columns, sqlgraph.NewFieldSpec(workflownodeinstance.FieldID, field.TypeInt))
	_spec.From = wniq.sql
	if unique := wniq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wniq.path != nil {
		_spec.Unique = true
	}
	if fields := wniq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflownodeinstance.FieldID)
		for i := range fields {
			if fields[i] != workflownodeinstance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wniq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wniq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wniq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wniq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wniq *WorkflowNodeInstanceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wniq.driver.Dialect())
	t1 := builder.Table(workflownodeinstance.Table)
	columns := wniq.ctx.Fields
	if len(columns) == 0 {
		columns = workflownodeinstance.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wniq.sql != nil {
		selector = wniq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wniq.ctx.Unique != nil && *wniq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wniq.predicates {
		p(selector)
	}
	for _, p := range wniq.order {
		p(selector)
	}
	if offset := wniq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wniq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WorkflowNodeInstanceGroupBy is the group-by builder for WorkflowNodeInstance entities.
type WorkflowNodeInstanceGroupBy struct {
	selector
	build *WorkflowNodeInstanceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wnigb *WorkflowNodeInstanceGroupBy) Aggregate(fns ...AggregateFunc) *WorkflowNodeInstanceGroupBy {
	wnigb.fns = append(wnigb.fns, fns...)
	return wnigb
}

// Scan applies the selector query and scans the result into the given value.
func (wnigb *WorkflowNodeInstanceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wnigb.build.ctx, "GroupBy")
	if err := wnigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkflowNodeInstanceQuery, *WorkflowNodeInstanceGroupBy](ctx, wnigb.build, wnigb, wnigb.build.inters, v)
}

func (wnigb *WorkflowNodeInstanceGroupBy) sqlScan(ctx context.Context, root *WorkflowNodeInstanceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wnigb.fns))
	for _, fn := range wnigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wnigb.flds)+len(wnigb.fns))
		for _, f := range *wnigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wnigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wnigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorkflowNodeInstanceSelect is the builder for selecting fields of WorkflowNodeInstance entities.
type WorkflowNodeInstanceSelect struct {
	*WorkflowNodeInstanceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wnis *WorkflowNodeInstanceSelect) Aggregate(fns ...AggregateFunc) *WorkflowNodeInstanceSelect {
	wnis.fns = append(wnis.fns, fns...)
	return wnis
}

// Scan applies the selector query and scans the result into the given value.
func (wnis *WorkflowNodeInstanceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wnis.ctx, "Select")
	if err := wnis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkflowNodeInstanceQuery, *WorkflowNodeInstanceSelect](ctx, wnis.WorkflowNodeInstanceQuery, wnis, wnis.inters, v)
}

func (wnis *WorkflowNodeInstanceSelect) sqlScan(ctx context.Context, root *WorkflowNodeInstanceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wnis.fns))
	for _, fn := range wnis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wnis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wnis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
