// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/workflowdefinition"
)

// WorkflowDefinitionUpdate is the builder for updating WorkflowDefinition entities.
type WorkflowDefinitionUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowDefinitionMutation
}

// Where appends a list predicates to the WorkflowDefinitionUpdate builder.
func (wdu *WorkflowDefinitionUpdate) Where(ps ...predicate.WorkflowDefinition) *WorkflowDefinitionUpdate {
	wdu.mutation.Where(ps...)
	return wdu
}

// SetUpdatedAt sets the "updated_at" field.
func (wdu *WorkflowDefinitionUpdate) SetUpdatedAt(t time.Time) *WorkflowDefinitionUpdate {
	wdu.mutation.SetUpdatedAt(t)
	return wdu
}

// SetDeletedAt sets the "deleted_at" field.
func (wdu *WorkflowDefinitionUpdate) SetDeletedAt(t time.Time) *WorkflowDefinitionUpdate {
	wdu.mutation.SetDeletedAt(t)
	return wdu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (wdu *WorkflowDefinitionUpdate) SetNillableDeletedAt(t *time.Time) *WorkflowDefinitionUpdate {
	if t != nil {
		wdu.SetDeletedAt(*t)
	}
	return wdu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (wdu *WorkflowDefinitionUpdate) ClearDeletedAt() *WorkflowDefinitionUpdate {
	wdu.mutation.ClearDeletedAt()
	return wdu
}

// SetWorkflowCode sets the "workflow_code" field.
func (wdu *WorkflowDefinitionUpdate) SetWorkflowCode(s string) *WorkflowDefinitionUpdate {
	wdu.mutation.SetWorkflowCode(s)
	return wdu
}

// SetNillableWorkflowCode sets the "workflow_code" field if the given value is not nil.
func (wdu *WorkflowDefinitionUpdate) SetNillableWorkflowCode(s *string) *WorkflowDefinitionUpdate {
	if s != nil {
		wdu.SetWorkflowCode(*s)
	}
	return wdu
}

// SetWorkflowName sets the "workflow_name" field.
func (wdu *WorkflowDefinitionUpdate) SetWorkflowName(s string) *WorkflowDefinitionUpdate {
	wdu.mutation.SetWorkflowName(s)
	return wdu
}

// SetNillableWorkflowName sets the "workflow_name" field if the given value is not nil.
func (wdu *WorkflowDefinitionUpdate) SetNillableWorkflowName(s *string) *WorkflowDefinitionUpdate {
	if s != nil {
		wdu.SetWorkflowName(*s)
	}
	return wdu
}

// SetDescription sets the "description" field.
func (wdu *WorkflowDefinitionUpdate) SetDescription(s string) *WorkflowDefinitionUpdate {
	wdu.mutation.SetDescription(s)
	return wdu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wdu *WorkflowDefinitionUpdate) SetNillableDescription(s *string) *WorkflowDefinitionUpdate {
	if s != nil {
		wdu.SetDescription(*s)
	}
	return wdu
}

// ClearDescription clears the value of the "description" field.
func (wdu *WorkflowDefinitionUpdate) ClearDescription() *WorkflowDefinitionUpdate {
	wdu.mutation.ClearDescription()
	return wdu
}

// SetStatus sets the "status" field.
func (wdu *WorkflowDefinitionUpdate) SetStatus(s string) *WorkflowDefinitionUpdate {
	wdu.mutation.SetStatus(s)
	return wdu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wdu *WorkflowDefinitionUpdate) SetNillableStatus(s *string) *WorkflowDefinitionUpdate {
	if s != nil {
		wdu.SetStatus(*s)
	}
	return wdu
}

// Mutation returns the WorkflowDefinitionMutation object of the builder.
func (wdu *WorkflowDefinitionUpdate) Mutation() *WorkflowDefinitionMutation {
	return wdu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wdu *WorkflowDefinitionUpdate) Save(ctx context.Context) (int, error) {
	wdu.defaults()
	return withHooks(ctx, wdu.sqlSave, wdu.mutation, wdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wdu *WorkflowDefinitionUpdate) SaveX(ctx context.Context) int {
	affected, err := wdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wdu *WorkflowDefinitionUpdate) Exec(ctx context.Context) error {
	_, err := wdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wdu *WorkflowDefinitionUpdate) ExecX(ctx context.Context) {
	if err := wdu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wdu *WorkflowDefinitionUpdate) defaults() {
	if _, ok := wdu.mutation.UpdatedAt(); !ok {
		v := workflowdefinition.UpdateDefaultUpdatedAt()
		wdu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wdu *WorkflowDefinitionUpdate) check() error {
	if v, ok := wdu.mutation.WorkflowCode(); ok {
		if err := workflowdefinition.WorkflowCodeValidator(v); err != nil {
			return &ValidationError{Name: "workflow_code", err: fmt.Errorf(`ent: validator failed for field "WorkflowDefinition.workflow_code": %w`, err)}
		}
	}
	if v, ok := wdu.mutation.WorkflowName(); ok {
		if err := workflowdefinition.WorkflowNameValidator(v); err != nil {
			return &ValidationError{Name: "workflow_name", err: fmt.Errorf(`ent: validator failed for field "WorkflowDefinition.workflow_name": %w`, err)}
		}
	}
	if v, ok := wdu.mutation.Description(); ok {
		if err := workflowdefinition.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "WorkflowDefinition.description": %w`, err)}
		}
	}
	if v, ok := wdu.mutation.Status(); ok {
		if err := workflowdefinition.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkflowDefinition.status": %w`, err)}
		}
	}
	return nil
}

func (wdu *WorkflowDefinitionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wdu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowdefinition.Table, workflowdefinition.Columns, sqlgraph.NewFieldSpec(workflowdefinition.FieldID, field.TypeInt))
	if ps := wdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wdu.mutation.UpdatedAt(); ok {
		_spec.SetField(workflowdefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wdu.mutation.DeletedAt(); ok {
		_spec.SetField(workflowdefinition.FieldDeletedAt, field.TypeTime, value)
	}
	if wdu.mutation.DeletedAtCleared() {
		_spec.ClearField(workflowdefinition.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := wdu.mutation.WorkflowCode(); ok {
		_spec.SetField(workflowdefinition.FieldWorkflowCode, field.TypeString, value)
	}
	if value, ok := wdu.mutation.WorkflowName(); ok {
		_spec.SetField(workflowdefinition.FieldWorkflowName, field.TypeString, value)
	}
	if value, ok := wdu.mutation.Description(); ok {
		_spec.SetField(workflowdefinition.FieldDescription, field.TypeString, value)
	}
	if wdu.mutation.DescriptionCleared() {
		_spec.ClearField(workflowdefinition.FieldDescription, field.TypeString)
	}
	if value, ok := wdu.mutation.Status(); ok {
		_spec.SetField(workflowdefinition.FieldStatus, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowdefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wdu.mutation.done = true
	return n, nil
}

// WorkflowDefinitionUpdateOne is the builder for updating a single WorkflowDefinition entity.
type WorkflowDefinitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowDefinitionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (wduo *WorkflowDefinitionUpdateOne) SetUpdatedAt(t time.Time) *WorkflowDefinitionUpdateOne {
	wduo.mutation.SetUpdatedAt(t)
	return wduo
}

// SetDeletedAt sets the "deleted_at" field.
func (wduo *WorkflowDefinitionUpdateOne) SetDeletedAt(t time.Time) *WorkflowDefinitionUpdateOne {
	wduo.mutation.SetDeletedAt(t)
	return wduo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (wduo *WorkflowDefinitionUpdateOne) SetNillableDeletedAt(t *time.Time) *WorkflowDefinitionUpdateOne {
	if t != nil {
		wduo.SetDeletedAt(*t)
	}
	return wduo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (wduo *WorkflowDefinitionUpdateOne) ClearDeletedAt() *WorkflowDefinitionUpdateOne {
	wduo.mutation.ClearDeletedAt()
	return wduo
}

// SetWorkflowCode sets the "workflow_code" field.
func (wduo *WorkflowDefinitionUpdateOne) SetWorkflowCode(s string) *WorkflowDefinitionUpdateOne {
	wduo.mutation.SetWorkflowCode(s)
	return wduo
}

// SetNillableWorkflowCode sets the "workflow_code" field if the given value is not nil.
func (wduo *WorkflowDefinitionUpdateOne) SetNillableWorkflowCode(s *string) *WorkflowDefinitionUpdateOne {
	if s != nil {
		wduo.SetWorkflowCode(*s)
	}
	return wduo
}

// SetWorkflowName sets the "workflow_name" field.
func (wduo *WorkflowDefinitionUpdateOne) SetWorkflowName(s string) *WorkflowDefinitionUpdateOne {
	wduo.mutation.SetWorkflowName(s)
	return wduo
}

// SetNillableWorkflowName sets the "workflow_name" field if the given value is not nil.
func (wduo *WorkflowDefinitionUpdateOne) SetNillableWorkflowName(s *string) *WorkflowDefinitionUpdateOne {
	if s != nil {
		wduo.SetWorkflowName(*s)
	}
	return wduo
}

// SetDescription sets the "description" field.
func (wduo *WorkflowDefinitionUpdateOne) SetDescription(s string) *WorkflowDefinitionUpdateOne {
	wduo.mutation.SetDescription(s)
	return wduo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wduo *WorkflowDefinitionUpdateOne) SetNillableDescription(s *string) *WorkflowDefinitionUpdateOne {
	if s != nil {
		wduo.SetDescription(*s)
	}
	return wduo
}

// ClearDescription clears the value of the "description" field.
func (wduo *WorkflowDefinitionUpdateOne) ClearDescription() *WorkflowDefinitionUpdateOne {
	wduo.mutation.ClearDescription()
	return wduo
}

// SetStatus sets the "status" field.
func (wduo *WorkflowDefinitionUpdateOne) SetStatus(s string) *WorkflowDefinitionUpdateOne {
	wduo.mutation.SetStatus(s)
	return wduo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wduo *WorkflowDefinitionUpdateOne) SetNillableStatus(s *string) *WorkflowDefinitionUpdateOne {
	if s != nil {
		wduo.SetStatus(*s)
	}
	return wduo
}

// Mutation returns the WorkflowDefinitionMutation object of the builder.
func (wduo *WorkflowDefinitionUpdateOne) Mutation() *WorkflowDefinitionMutation {
	return wduo.mutation
}

// Where appends a list predicates to the WorkflowDefinitionUpdate builder.
func (wduo *WorkflowDefinitionUpdateOne) Where(ps ...predicate.WorkflowDefinition) *WorkflowDefinitionUpdateOne {
	wduo.mutation.Where(ps...)
	return wduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wduo *WorkflowDefinitionUpdateOne) Select(field string, fields ...string) *WorkflowDefinitionUpdateOne {
	wduo.fields = append([]string{field}, fields...)
	return wduo
}

// Save executes the query and returns the updated WorkflowDefinition entity.
func (wduo *WorkflowDefinitionUpdateOne) Save(ctx context.Context) (*WorkflowDefinition, error) {
	wduo.defaults()
	return withHooks(ctx, wduo.sqlSave, wduo.mutation, wduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wduo *WorkflowDefinitionUpdateOne) SaveX(ctx context.Context) *WorkflowDefinition {
	node, err := wduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wduo *WorkflowDefinitionUpdateOne) Exec(ctx context.Context) error {
	_, err := wduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wduo *WorkflowDefinitionUpdateOne) ExecX(ctx context.Context) {
	if err := wduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wduo *WorkflowDefinitionUpdateOne) defaults() {
	if _, ok := wduo.mutation.UpdatedAt(); !ok {
		v := workflowdefinition.UpdateDefaultUpdatedAt()
		wduo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wduo *WorkflowDefinitionUpdateOne) check() error {
	if v, ok := wduo.mutation.WorkflowCode(); ok {
		if err := workflowdefinition.WorkflowCodeValidator(v); err != nil {
			return &ValidationError{Name: "workflow_code", err: fmt.Errorf(`ent: validator failed for field "WorkflowDefinition.workflow_code": %w`, err)}
		}
	}
	if v, ok := wduo.mutation.WorkflowName(); ok {
		if err := workflowdefinition.WorkflowNameValidator(v); err != nil {
			return &ValidationError{Name: "workflow_name", err: fmt.Errorf(`ent: validator failed for field "WorkflowDefinition.workflow_name": %w`, err)}
		}
	}
	if v, ok := wduo.mutation.Description(); ok {
		if err := workflowdefinition.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "WorkflowDefinition.description": %w`, err)}
		}
	}
	if v, ok := wduo.mutation.Status(); ok {
		if err := workflowdefinition.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkflowDefinition.status": %w`, err)}
		}
	}
	return nil
}

func (wduo *WorkflowDefinitionUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowDefinition, err error) {
	if err := wduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowdefinition.Table, workflowdefinition.Columns, sqlgraph.NewFieldSpec(workflowdefinition.FieldID, field.TypeInt))
	id, ok := wduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowDefinition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowdefinition.FieldID)
		for _, f := range fields {
			if !workflowdefinition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowdefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wduo.mutation.UpdatedAt(); ok {
		_spec.SetField(workflowdefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wduo.mutation.DeletedAt(); ok {
		_spec.SetField(workflowdefinition.FieldDeletedAt, field.TypeTime, value)
	}
	if wduo.mutation.DeletedAtCleared() {
		_spec.ClearField(workflowdefinition.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := wduo.mutation.WorkflowCode(); ok {
		_spec.SetField(workflowdefinition.FieldWorkflowCode, field.TypeString, value)
	}
	if value, ok := wduo.mutation.WorkflowName(); ok {
		_spec.SetField(workflowdefinition.FieldWorkflowName, field.TypeString, value)
	}
	if value, ok := wduo.mutation.Description(); ok {
		_spec.SetField(workflowdefinition.FieldDescription, field.TypeString, value)
	}
	if wduo.mutation.DescriptionCleared() {
		_spec.ClearField(workflowdefinition.FieldDescription, field.TypeString)
	}
	if value, ok := wduo.mutation.Status(); ok {
		_spec.SetField(workflowdefinition.FieldStatus, field.TypeString, value)
	}
	_node = &WorkflowDefinition{config: wduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowdefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wduo.mutation.done = true
	return _node, nil
}
