// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/workflowdefinition"
)

// WorkflowDefinitionDelete is the builder for deleting a WorkflowDefinition entity.
type WorkflowDefinitionDelete struct {
	config
	hooks    []Hook
	mutation *WorkflowDefinitionMutation
}

// Where appends a list predicates to the WorkflowDefinitionDelete builder.
func (wdd *WorkflowDefinitionDelete) Where(ps ...predicate.WorkflowDefinition) *WorkflowDefinitionDelete {
	wdd.mutation.Where(ps...)
	return wdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wdd *WorkflowDefinitionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, wdd.sqlExec, wdd.mutation, wdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wdd *WorkflowDefinitionDelete) ExecX(ctx context.Context) int {
	n, err := wdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wdd *WorkflowDefinitionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(workflowdefinition.Table, sqlgraph.NewFieldSpec(workflowdefinition.FieldID, field.TypeInt))
	if ps := wdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wdd.mutation.done = true
	return affected, err
}

// WorkflowDefinitionDeleteOne is the builder for deleting a single WorkflowDefinition entity.
type WorkflowDefinitionDeleteOne struct {
	wdd *WorkflowDefinitionDelete
}

// Where appends a list predicates to the WorkflowDefinitionDelete builder.
func (wddo *WorkflowDefinitionDeleteOne) Where(ps ...predicate.WorkflowDefinition) *WorkflowDefinitionDeleteOne {
	wddo.wdd.mutation.Where(ps...)
	return wddo
}

// Exec executes the deletion query.
func (wddo *WorkflowDefinitionDeleteOne) Exec(ctx context.Context) error {
	n, err := wddo.wdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workflowdefinition.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wddo *WorkflowDefinitionDeleteOne) ExecX(ctx context.Context) {
	if err := wddo.Exec(ctx); err != nil {
		panic(err)
	}
}
