// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/workflownodeinstance"
)

// WorkflowNodeInstance is the model entity for the WorkflowNodeInstance schema.
type WorkflowNodeInstance struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// WorkflowInstanceID holds the value of the "workflow_instance_id" field.
	WorkflowInstanceID int64 `json:"workflow_instance_id,omitempty"`
	// WorkflowID holds the value of the "workflow_id" field.
	WorkflowID int64 `json:"workflow_id,omitempty"`
	// NodeCode holds the value of the "node_code" field.
	NodeCode string `json:"node_code,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID int64 `json:"job_id,omitempty"`
	// JobInstanceID holds the value of the "job_instance_id" field.
	JobInstanceID *int64 `json:"job_instance_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// StartTime holds the value of the "start_time" field.
	StartTime *time.Time `json:"start_time,omitempty"`
	// FinishTime holds the value of the "finish_time" field.
	FinishTime   *time.Time `json:"finish_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkflowNodeInstance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflownodeinstance.FieldID, workflownodeinstance.FieldWorkflowInstanceID, workflownodeinstance.FieldWorkflowID, workflownodeinstance.FieldJobID, workflownodeinstance.FieldJobInstanceID:
			values[i] = new(sql.NullInt64)
		case workflownodeinstance.FieldNodeCode, workflownodeinstance.FieldStatus, workflownodeinstance.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case workflownodeinstance.FieldCreatedAt, workflownodeinstance.FieldUpdatedAt, workflownodeinstance.FieldDeletedAt, workflownodeinstance.FieldStartTime, workflownodeinstance.FieldFinishTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkflowNodeInstance fields.
func (wni *WorkflowNodeInstance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflownodeinstance.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			wni.ID = int(value.Int64)
		case workflownodeinstance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				wni.CreatedAt = value.Time
			}
		case workflownodeinstance.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				wni.UpdatedAt = value.Time
			}
		case workflownodeinstance.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				wni.DeletedAt = new(time.Time)
				*wni.DeletedAt = value.Time
			}
		case workflownodeinstance.FieldWorkflowInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_instance_id", values[i])
			} else if value.Valid {
				wni.WorkflowInstanceID = value.Int64
			}
		case workflownodeinstance.FieldWorkflowID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value.Valid {
				wni.WorkflowID = value.Int64
			}
		case workflownodeinstance.FieldNodeCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_code", values[i])
			} else if value.Valid {
				wni.NodeCode = value.String
			}
		case workflownodeinstance.FieldJobID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				wni.JobID = value.Int64
			}
		case workflownodeinstance.FieldJobInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field job_instance_id", values[i])
			} else if value.Valid {
				wni.JobInstanceID = new(int64)
				*wni.JobInstanceID = value.Int64
			}
		case workflownodeinstance.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				wni.Status = value.String
			}
		case workflownodeinstance.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				wni.ErrorMessage = new(string)
				*wni.ErrorMessage = value.String
			}
		case workflownodeinstance.FieldStartTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_time", values[i])
			} else if value.Valid {
				wni.StartTime = new(time.Time)
				*wni.StartTime = value.Time
			}
		case workflownodeinstance.FieldFinishTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finish_time", values[i])
			} else if value.Valid {
				wni.FinishTime = new(time.Time)
				*wni.FinishTime = value.Time
			}
		default:
			wni.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkflowNodeInstance.
// This includes values selected through modifiers, order, etc.
func (wni *WorkflowNodeInstance) Value(name string) (ent.Value, error) {
	return wni.selectValues.Get(name)
}

// Update returns a builder for updating this WorkflowNodeInstance.
// Note that you need to call WorkflowNodeInstance.Unwrap() before calling this method if this WorkflowNodeInstance
// was returned from a transaction, and the transaction was committed or rolled back.
func (wni *WorkflowNodeInstance) Update() *WorkflowNodeInstanceUpdateOne {
	return NewWorkflowNodeInstanceClient(wni.config).UpdateOne(wni)
}

// Unwrap unwraps the WorkflowNodeInstance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (wni *WorkflowNodeInstance) Unwrap() *WorkflowNodeInstance {
	_tx, ok := wni.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkflowNodeInstance is not a transactional entity")
	}
	wni.config.driver = _tx.drv
	return wni
}

// String implements the fmt.Stringer.
func (wni *WorkflowNodeInstance) String() string {
	var builder strings.Builder
	builder.WriteString("WorkflowNodeInstance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", wni.ID))
	builder.WriteString("created_at=")
	builder.WriteString(wni.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(wni.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := wni.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("workflow_instance_id=")
	builder.WriteString(fmt.Sprintf("%v", wni.WorkflowInstanceID))
	builder.WriteString(", ")
	builder.WriteString("workflow_id=")
	builder.WriteString(fmt.Sprintf("%v", wni.WorkflowID))
	builder.WriteString(", ")
	builder.WriteString("node_code=")
	builder.WriteString(wni.NodeCode)
	builder.WriteString(", ")
	builder.WriteString("job_id=")
	builder.WriteString(fmt.Sprintf("%v", wni.JobID))
	builder.WriteString(", ")
	if v := wni.JobInstanceID; v != nil {
		builder.WriteString("job_instance_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(wni.Status)
	builder.WriteString(", ")
	if v := wni.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := wni.StartTime; v != nil {
		builder.WriteString("start_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := wni.FinishTime; v != nil {
		builder.WriteString("finish_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// WorkflowNodeInstances is a parsable slice of WorkflowNodeInstance.
type WorkflowNodeInstances []*WorkflowNodeInstance
