// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/workflowdefinition"
)

// WorkflowDefinitionQuery is the builder for querying WorkflowDefinition entities.
type WorkflowDefinitionQuery struct {
	config
	ctx        *QueryContext
	order      []workflowdefinition.OrderOption
	inters     []Interceptor
	predicates []predicate.WorkflowDefinition
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorkflowDefinitionQuery builder.
func (wdq *WorkflowDefinitionQuery) Where(ps ...predicate.WorkflowDefinition) *WorkflowDefinitionQuery {
	wdq.predicates = append(wdq.predicates, ps...)
	return wdq
}

// Limit the number of records to be returned by this query.
func (wdq *WorkflowDefinitionQuery) Limit(limit int) *WorkflowDefinitionQuery {
	wdq.ctx.Limit = &limit
	return wdq
}

// Offset to start from.
func (wdq *WorkflowDefinitionQuery) Offset(offset int) *WorkflowDefinitionQuery {
	wdq.ctx.Offset = &offset
	return wdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wdq *WorkflowDefinitionQuery) Unique(unique bool) *WorkflowDefinitionQuery {
	wdq.ctx.Unique = &unique
	return wdq
}

// Order specifies how the records should be ordered.
func (wdq *WorkflowDefinitionQuery) Order(o ...workflowdefinition.OrderOption) *WorkflowDefinitionQuery {
	wdq.order = append(wdq.order, o...)
	return wdq
}

// First returns the first WorkflowDefinition entity from the query.
// Returns a *NotFoundError when no WorkflowDefinition was found.
func (wdq *WorkflowDefinitionQuery) First(ctx context.Context) (*WorkflowDefinition, error) {
	nodes, err := wdq.Limit(1).All(setContextOp(ctx, wdq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{workflowdefinition.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wdq *WorkflowDefinitionQuery) FirstX(ctx context.Context) *WorkflowDefinition {
	node, err := wdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WorkflowDefinition ID from the query.
// Returns a *NotFoundError when no WorkflowDefinition ID was found.
func (wdq *WorkflowDefinitionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wdq.Limit(1).IDs(setContextOp(ctx, wdq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{workflowdefinition.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wdq *WorkflowDefinitionQuery) FirstIDX(ctx context.Context) int {
	id, err := wdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WorkflowDefinition entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WorkflowDefinition entity is found.
// Returns a *NotFoundError when no WorkflowDefinition entities are found.
func (wdq *WorkflowDefinitionQuery) Only(ctx context.Context) (*WorkflowDefinition, error) {
	nodes, err := wdq.Limit(2).All(setContextOp(ctx, wdq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{workflowdefinition.Label}
	default:
		return nil, &NotSingularError{workflowdefinition.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wdq *WorkflowDefinitionQuery) OnlyX(ctx context.Context) *WorkflowDefinition {
	node, err := wdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WorkflowDefinition ID in the query.
// Returns a *NotSingularError when more than one WorkflowDefinition ID is found.
// Returns a *NotFoundError when no entities are found.
func (wdq *WorkflowDefinitionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wdq.Limit(2).IDs(setContextOp(ctx, wdq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{workflowdefinition.Label}
	default:
		err = &NotSingularError{workflowdefinition.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wdq *WorkflowDefinitionQuery) OnlyIDX(ctx context.Context) int {
	id, err := wdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WorkflowDefinitions.
func (wdq *WorkflowDefinitionQuery) All(ctx context.Context) ([]*WorkflowDefinition, error) {
	ctx = setContextOp(ctx, wdq.ctx, "All")
	if err := wdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WorkflowDefinition, *WorkflowDefinitionQuery]()
	return withInterceptors[[]*WorkflowDefinition](ctx, wdq, qr, wdq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wdq *WorkflowDefinitionQuery) AllX(ctx context.Context) []*WorkflowDefinition {
	nodes, err := wdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WorkflowDefinition IDs.
func (wdq *WorkflowDefinitionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wdq.ctx.Unique == nil && wdq.path != nil {
		wdq.Unique(true)
	}
	ctx = setContextOp(ctx, wdq.ctx, "IDs")
	if err = wdq.Select(workflowdefinition.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wdq *WorkflowDefinitionQuery) IDsX(ctx context.Context) []int {
	ids, err := wdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wdq *WorkflowDefinitionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wdq.ctx, "Count")
	if err := wdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wdq, querierCount[*WorkflowDefinitionQuery](), wdq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wdq *WorkflowDefinitionQuery) CountX(ctx context.Context) int {
	count, err := wdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wdq *WorkflowDefinitionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wdq.ctx, "Exist")
	switch _, err := wdq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wdq *WorkflowDefinitionQuery) ExistX(ctx context.Context) bool {
	exist, err := wdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorkflowDefinitionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wdq *WorkflowDefinitionQuery) Clone() *WorkflowDefinitionQuery {
	if wdq == nil {
		return nil
	}
	return &WorkflowDefinitionQuery{
		config:     wdq.config,
		ctx:        wdq.ctx.Clone(),
		order:      append([]workflowdefinition.OrderOption{}, wdq.order...),
		inters:     append([]Interceptor{}, wdq.inters...),
		predicates: append([]predicate.WorkflowDefinition{}, wdq.predicates...),
		// clone intermediate query.
		sql:  wdq.sql.Clone(),
		path: wdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WorkflowDefinition.Query().
//		GroupBy(workflowdefinition.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wdq *WorkflowDefinitionQuery) GroupBy(field string, fields ...string) *WorkflowDefinitionGroupBy {
	wdq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorkflowDefinitionGroupBy{build: wdq}
	grbuild.flds = &wdq.ctx.Fields
	grbuild.label = workflowdefinition.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.WorkflowDefinition.Query().
//		Select(workflowdefinition.FieldCreatedAt).
//		Scan(ctx, &v)
func (wdq *WorkflowDefinitionQuery) Select(fields ...string) *WorkflowDefinitionSelect {
	wdq.ctx.Fields = append(wdq.ctx.Fields, fields...)
	sbuild := &WorkflowDefinitionSelect{WorkflowDefinitionQuery: wdq}
	sbuild.label = workflowdefinition.Label
	sbuild.flds, sbuild.scan = &wdq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorkflowDefinitionSelect configured with the given aggregations.
func (wdq *WorkflowDefinitionQuery) Aggregate(fns ...AggregateFunc) *WorkflowDefinitionSelect {
	return wdq.Select().Aggregate(fns...)
}

func (wdq *WorkflowDefinitionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wdq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wdq); err != nil {
				return err
			}
		}
	}
	for _, f := range wdq.ctx.Fields {
		if !workflowdefinition.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wdq.path != nil {
		prev, err := wdq.path(ctx)
		if err != nil {
			return err
		}
		wdq.sql = prev
	}
	return nil
}

func (wdq *WorkflowDefinitionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WorkflowDefinition, error) {
	var (
		nodes = []*WorkflowDefinition{}
		_spec = wdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WorkflowDefinition).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WorkflowDefinition{config: wdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wdq *WorkflowDefinitionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wdq.querySpec()
	_spec.Node.Columns = wdq.ctx.Fields
	if len(wdq.ctx.Fields) > 0 {
		_spec.Unique = wdq.ctx.Unique != nil && *wdq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wdq.driver, _spec)
}

func (wdq *WorkflowDefinitionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(workflowdefinition.Table, workflowdefinition.Columns, sqlgraph.NewFieldSpec(workflowdefinition.FieldID, field.TypeInt))
	_spec.From = wdq.sql
	if unique := wdq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wdq.path != nil {
		_spec.Unique = true
	}
	if fields := wdq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowdefinition.FieldID)
		for i := range fields {
			if fields[i] != workflowdefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wdq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wdq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wdq *WorkflowDefinitionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wdq.driver.Dialect())
	t1 := builder.Table(workflowdefinition.Table)
	columns := wdq.ctx.Fields
	if len(columns) == 0 {
		columns = workflowdefinition.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wdq.sql != nil {
		selector = wdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wdq.ctx.Unique != nil && *wdq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wdq.predicates {
		p(selector)
	}
	for _, p := range wdq.order {
		p(selector)
	}
	if offset := wdq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wdq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WorkflowDefinitionGroupBy is the group-by builder for WorkflowDefinition entities.
type WorkflowDefinitionGroupBy struct {
	selector
	build *WorkflowDefinitionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wdgb *WorkflowDefinitionGroupBy) Aggregate(fns ...AggregateFunc) *WorkflowDefinitionGroupBy {
	wdgb.fns = append(wdgb.fns, fns...)
	return wdgb
}

// Scan applies the selector query and scans the result into the given value.
func (wdgb *WorkflowDefinitionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wdgb.build.ctx, "GroupBy")
	if err := wdgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkflowDefinitionQuery, *WorkflowDefinitionGroupBy](ctx, wdgb.build, wdgb, wdgb.build.inters, v)
}

func (wdgb *WorkflowDefinitionGroupBy) sqlScan(ctx context.Context, root *WorkflowDefinitionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wdgb.fns))
	for _, fn := range wdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wdgb.flds)+len(wdgb.fns))
		for _, f := range *wdgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wdgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wdgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorkflowDefinitionSelect is the builder for selecting fields of WorkflowDefinition entities.
type WorkflowDefinitionSelect struct {
	*WorkflowDefinitionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wds *WorkflowDefinitionSelect) Aggregate(fns ...AggregateFunc) *WorkflowDefinitionSelect {
	wds.fns = append(wds.fns, fns...)
	return wds
}

// Scan applies the selector query and scans the result into the given value.
func (wds *WorkflowDefinitionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wds.ctx, "Select")
	if err := wds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkflowDefinitionQuery, *WorkflowDefinitionSelect](ctx, wds.WorkflowDefinitionQuery, wds, wds.inters, v)
}

func (wds *WorkflowDefinitionSelect) sqlScan(ctx context.Context, root *WorkflowDefinitionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wds.fns))
	for _, fn := range wds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
