// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/workflownode"
)

// WorkflowNode is the model entity for the WorkflowNode schema.
type WorkflowNode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// WorkflowID holds the value of the "workflow_id" field.
	WorkflowID int64 `json:"workflow_id,omitempty"`
	// NodeCode holds the value of the "node_code" field.
	NodeCode string `json:"node_code,omitempty"`
	// NodeName holds the value of the "node_name" field.
	NodeName string `json:"node_name,omitempty"`
	// JobCode holds the value of the "job_code" field.
	JobCode string `json:"job_code,omitempty"`
	// UpstreamCodes holds the value of the "upstream_codes" field.
	UpstreamCodes *string `json:"upstream_codes,omitempty"`
	// TriggerCondition holds the value of the "trigger_condition" field.
	TriggerCondition string `json:"trigger_condition,omitempty"`
	// FailStrategy holds the value of the "fail_strategy" field.
	FailStrategy string `json:"fail_strategy,omitempty"`
	// TimeoutMs holds the value of the "timeout_ms" field.
	TimeoutMs int `json:"timeout_ms,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder    int `json:"sort_order,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkflowNode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workflownode.FieldID, workflownode.FieldWorkflowID, workflownode.FieldTimeoutMs, workflownode.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case workflownode.FieldNodeCode, workflownode.FieldNodeName, workflownode.FieldJobCode, workflownode.FieldUpstreamCodes, workflownode.FieldTriggerCondition, workflownode.FieldFailStrategy:
			values[i] = new(sql.NullString)
		case workflownode.FieldCreatedAt, workflownode.FieldUpdatedAt, workflownode.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkflowNode fields.
func (wn *WorkflowNode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workflownode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			wn.ID = int(value.Int64)
		case workflownode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				wn.CreatedAt = value.Time
			}
		case workflownode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				wn.UpdatedAt = value.Time
			}
		case workflownode.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				wn.DeletedAt = new(time.Time)
				*wn.DeletedAt = value.Time
			}
		case workflownode.FieldWorkflowID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value.Valid {
				wn.WorkflowID = value.Int64
			}
		case workflownode.FieldNodeCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_code", values[i])
			} else if value.Valid {
				wn.NodeCode = value.String
			}
		case workflownode.FieldNodeName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_name", values[i])
			} else if value.Valid {
				wn.NodeName = value.String
			}
		case workflownode.FieldJobCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_code", values[i])
			} else if value.Valid {
				wn.JobCode = value.String
			}
		case workflownode.FieldUpstreamCodes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_codes", values[i])
			} else if value.Valid {
				wn.UpstreamCodes = new(string)
				*wn.UpstreamCodes = value.String
			}
		case workflownode.FieldTriggerCondition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_condition", values[i])
			} else if value.Valid {
				wn.TriggerCondition = value.String
			}
		case workflownode.FieldFailStrategy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fail_strategy", values[i])
			} else if value.Valid {
				wn.FailStrategy = value.String
			}
		case workflownode.FieldTimeoutMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout_ms", values[i])
			} else if value.Valid {
				wn.TimeoutMs = int(value.Int64)
			}
		case workflownode.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				wn.SortOrder = int(value.Int64)
			}
		default:
			wn.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkflowNode.
// This includes values selected through modifiers, order, etc.
func (wn *WorkflowNode) Value(name string) (ent.Value, error) {
	return wn.selectValues.Get(name)
}

// Update returns a builder for updating this WorkflowNode.
// Note that you need to call WorkflowNode.Unwrap() before calling this method if this WorkflowNode
// was returned from a transaction, and the transaction was committed or rolled back.
func (wn *WorkflowNode) Update() *WorkflowNodeUpdateOne {
	return NewWorkflowNodeClient(wn.config).UpdateOne(wn)
}

// Unwrap unwraps the WorkflowNode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (wn *WorkflowNode) Unwrap() *WorkflowNode {
	_tx, ok := wn.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkflowNode is not a transactional entity")
	}
	wn.config.driver = _tx.drv
	return wn
}

// String implements the fmt.Stringer.
func (wn *WorkflowNode) String() string {
	var builder strings.Builder
	builder.WriteString("WorkflowNode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", wn.ID))
	builder.WriteString("created_at=")
	builder.WriteString(wn.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(wn.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := wn.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("workflow_id=")
	builder.WriteString(fmt.Sprintf("%v", wn.WorkflowID))
	builder.WriteString(", ")
	builder.WriteString("node_code=")
	builder.WriteString(wn.NodeCode)
	builder.WriteString(", ")
	builder.WriteString("node_name=")
	builder.WriteString(wn.NodeName)
	builder.WriteString(", ")
	builder.WriteString("job_code=")
	builder.WriteString(wn.JobCode)
	builder.WriteString(", ")
	if v := wn.UpstreamCodes; v != nil {
		builder.WriteString("upstream_codes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("trigger_condition=")
	builder.WriteString(wn.TriggerCondition)
	builder.WriteString(", ")
	builder.WriteString("fail_strategy=")
	builder.WriteString(wn.FailStrategy)
	builder.WriteString(", ")
	builder.WriteString("timeout_ms=")
	builder.WriteString(fmt.Sprintf("%v", wn.TimeoutMs))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", wn.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// WorkflowNodes is a parsable slice of WorkflowNode.
type WorkflowNodes []*WorkflowNode
