// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/workflownode"
)

// WorkflowNodeUpdate is the builder for updating WorkflowNode entities.
type WorkflowNodeUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowNodeMutation
}

// Where appends a list predicates to the WorkflowNodeUpdate builder.
func (wnu *WorkflowNodeUpdate) Where(ps ...predicate.WorkflowNode) *WorkflowNodeUpdate {
	wnu.mutation.Where(ps...)
	return wnu
}

// SetUpdatedAt sets the "updated_at" field.
func (wnu *WorkflowNodeUpdate) SetUpdatedAt(t time.Time) *WorkflowNodeUpdate {
	wnu.mutation.SetUpdatedAt(t)
	return wnu
}

// SetDeletedAt sets the "deleted_at" field.
func (wnu *WorkflowNodeUpdate) SetDeletedAt(t time.Time) *WorkflowNodeUpdate {
	wnu.mutation.SetDeletedAt(t)
	return wnu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (wnu *WorkflowNodeUpdate) SetNillableDeletedAt(t *time.Time) *WorkflowNodeUpdate {
	if t != nil {
		wnu.SetDeletedAt(*t)
	}
	return wnu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (wnu *WorkflowNodeUpdate) ClearDeletedAt() *WorkflowNodeUpdate {
	wnu.mutation.ClearDeletedAt()
	return wnu
}

// SetWorkflowID sets the "workflow_id" field.
func (wnu *WorkflowNodeUpdate) SetWorkflowID(i int64) *WorkflowNodeUpdate {
	wnu.mutation.ResetWorkflowID()
	wnu.mutation.SetWorkflowID(i)
	return wnu
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (wnu *WorkflowNodeUpdate) SetNillableWorkflowID(i *int64) *WorkflowNodeUpdate {
	if i != nil {
		wnu.SetWorkflowID(*i)
	}
	return wnu
}

// AddWorkflowID adds i to the "workflow_id" field.
func (wnu *WorkflowNodeUpdate) AddWorkflowID(i int64) *WorkflowNodeUpdate {
	wnu.mutation.AddWorkflowID(i)
	return wnu
}

// SetNodeCode sets the "node_code" field.
func (wnu *WorkflowNodeUpdate) SetNodeCode(s string) *WorkflowNodeUpdate {
	wnu.mutation.SetNodeCode(s)
	return wnu
}

// SetNillableNodeCode sets the "node_code" field if the given value is not nil.
func (wnu *WorkflowNodeUpdate) SetNillableNodeCode(s *string) *WorkflowNodeUpdate {
	if s != nil {
		wnu.SetNodeCode(*s)
	}
	return wnu
}

// SetNodeName sets the "node_name" field.
func (wnu *WorkflowNodeUpdate) SetNodeName(s string) *WorkflowNodeUpdate {
	wnu.mutation.SetNodeName(s)
	return wnu
}

// SetNillableNodeName sets the "node_name" field if the given value is not nil.
func (wnu *WorkflowNodeUpdate) SetNillableNodeName(s *string) *WorkflowNodeUpdate {
	if s != nil {
		wnu.SetNodeName(*s)
	}
	return wnu
}

// SetJobCode sets the "job_code" field.
func (wnu *WorkflowNodeUpdate) SetJobCode(s string) *WorkflowNodeUpdate {
	wnu.mutation.SetJobCode(s)
	return wnu
}

// SetNillableJobCode sets the "job_code" field if the given value is not nil.
func (wnu *WorkflowNodeUpdate) SetNillableJobCode(s *string) *WorkflowNodeUpdate {
	if s != nil {
		wnu.SetJobCode(*s)
	}
	return wnu
}

// SetUpstreamCodes sets the "upstream_codes" field.
func (wnu *WorkflowNodeUpdate) SetUpstreamCodes(s string) *WorkflowNodeUpdate {
	wnu.mutation.SetUpstreamCodes(s)
	return wnu
}

// SetNillableUpstreamCodes sets the "upstream_codes" field if the given value is not nil.
func (wnu *WorkflowNodeUpdate) SetNillableUpstreamCodes(s *string) *WorkflowNodeUpdate {
	if s != nil {
		wnu.SetUpstreamCodes(*s)
	}
	return wnu
}

// ClearUpstreamCodes clears the value of the "upstream_codes" field.
func (wnu *WorkflowNodeUpdate) ClearUpstreamCodes() *WorkflowNodeUpdate {
	wnu.mutation.ClearUpstreamCodes()
	return wnu
}

// SetTriggerCondition sets the "trigger_condition" field.
func (wnu *WorkflowNodeUpdate) SetTriggerCondition(s string) *WorkflowNodeUpdate {
	wnu.mutation.SetTriggerCondition(s)
	return wnu
}

// SetNillableTriggerCondition sets the "trigger_condition" field if the given value is not nil.
func (wnu *WorkflowNodeUpdate) SetNillableTriggerCondition(s *string) *WorkflowNodeUpdate {
	if s != nil {
		wnu.SetTriggerCondition(*s)
	}
	return wnu
}

// SetFailStrategy sets the "fail_strategy" field.
func (wnu *WorkflowNodeUpdate) SetFailStrategy(s string) *WorkflowNodeUpdate {
	wnu.mutation.SetFailStrategy(s)
	return wnu
}

// SetNillableFailStrategy sets the "fail_strategy" field if the given value is not nil.
func (wnu *WorkflowNodeUpdate) SetNillableFailStrategy(s *string) *WorkflowNodeUpdate {
	if s != nil {
		wnu.SetFailStrategy(*s)
	}
	return wnu
}

// SetTimeoutMs sets the "timeout_ms" field.
func (wnu *WorkflowNodeUpdate) SetTimeoutMs(i int) *WorkflowNodeUpdate {
	wnu.mutation.ResetTimeoutMs()
	wnu.mutation.SetTimeoutMs(i)
	return wnu
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (wnu *WorkflowNodeUpdate) SetNillableTimeoutMs(i *int) *WorkflowNodeUpdate {
	if i != nil {
		wnu.SetTimeoutMs(*i)
	}
	return wnu
}

// AddTimeoutMs adds i to the "timeout_ms" field.
func (wnu *WorkflowNodeUpdate) AddTimeoutMs(i int) *WorkflowNodeUpdate {
	wnu.mutation.AddTimeoutMs(i)
	return wnu
}

// SetSortOrder sets the "sort_order" field.
func (wnu *WorkflowNodeUpdate) SetSortOrder(i int) *WorkflowNodeUpdate {
	wnu.mutation.ResetSortOrder()
	wnu.mutation.SetSortOrder(i)
	return wnu
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (wnu *WorkflowNodeUpdate) SetNillableSortOrder(i *int) *WorkflowNodeUpdate {
	if i != nil {
		wnu.SetSortOrder(*i)
	}
	return wnu
}

// AddSortOrder adds i to the "sort_order" field.
func (wnu *WorkflowNodeUpdate) AddSortOrder(i int) *WorkflowNodeUpdate {
	wnu.mutation.AddSortOrder(i)
	return wnu
}

// Mutation returns the WorkflowNodeMutation object of the builder.
func (wnu *WorkflowNodeUpdate) Mutation() *WorkflowNodeMutation {
	return wnu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wnu *WorkflowNodeUpdate) Save(ctx context.Context) (int, error) {
	wnu.defaults()
	return withHooks(ctx, wnu.sqlSave, wnu.mutation, wnu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wnu *WorkflowNodeUpdate) SaveX(ctx context.Context) int {
	affected, err := wnu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wnu *WorkflowNodeUpdate) Exec(ctx context.Context) error {
	_, err := wnu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wnu *WorkflowNodeUpdate) ExecX(ctx context.Context) {
	if err := wnu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wnu *WorkflowNodeUpdate) defaults() {
	if _, ok := wnu.mutation.UpdatedAt(); !ok {
		v := workflownode.UpdateDefaultUpdatedAt()
		wnu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wnu *WorkflowNodeUpdate) check() error {
	if v, ok := wnu.mutation.NodeCode(); ok {
		if err := workflownode.NodeCodeValidator(v); err != nil {
			return &ValidationError{Name: "node_code", err: fmt.Errorf(`ent: validator failed for field "WorkflowNode.node_code": %w`, err)}
		}
	}
	if v, ok := wnu.mutation.NodeName(); ok {
		if err := workflownode.NodeNameValidator(v); err != nil {
			return &ValidationError{Name: "node_name", err: fmt.Errorf(`ent: validator failed for field "WorkflowNode.node_name": %w`, err)}
		}
	}
	if v, ok := wnu.mutation.JobCode(); ok {
		if err := workflownode.JobCodeValidator(v); err != nil {
			return &ValidationError{Name: "job_code", err: fmt.Errorf(`ent: validator failed for field "WorkflowNode.job_code": %w`, err)}
		}
	}
	if v, ok := wnu.mutation.TriggerCondition(); ok {
		if err := workflownode.TriggerConditionValidator(v); err != nil {
			return &ValidationError{Name: "trigger_condition", err: fmt.Errorf(`ent: validator failed for field "WorkflowNode.trigger_condition": %w`, err)}
		}
	}
	if v, ok := wnu.mutation.FailStrategy(); ok {
		if err := workflownode.FailStrategyValidator(v); err != nil {
			return &ValidationError{Name: "fail_strategy", err: fmt.Errorf(`ent: validator failed for field "WorkflowNode.fail_strategy": %w`, err)}
		}
	}
	return nil
}

func (wnu *WorkflowNodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wnu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflownode.Table, workflownode.Columns, sqlgraph.NewFieldSpec(workflownode.FieldID, field.TypeInt))
	if ps := wnu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wnu.mutation.UpdatedAt(); ok {
		_spec.SetField(workflownode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wnu.mutation.DeletedAt(); ok {
		_spec.SetField(workflownode.FieldDeletedAt, field.TypeTime, value)
	}
	if wnu.mutation.DeletedAtCleared() {
		_spec.ClearField(workflownode.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := wnu.mutation.WorkflowID(); ok {
		_spec.SetField(workflownode.FieldWorkflowID, field.TypeInt64, value)
	}
	if value, ok := wnu.mutation.AddedWorkflowID(); ok {
		_spec.AddField(workflownode.FieldWorkflowID, field.TypeInt64, value)
	}
	if value, ok := wnu.mutation.NodeCode(); ok {
		_spec.SetField(workflownode.FieldNodeCode, field.TypeString, value)
	}
	if value, ok := wnu.mutation.NodeName(); ok {
		_spec.SetField(workflownode.FieldNodeName, field.TypeString, value)
	}
	if value, ok := wnu.mutation.JobCode(); ok {
		_spec.SetField(workflownode.FieldJobCode, field.TypeString, value)
	}
	if value, ok := wnu.mutation.UpstreamCodes(); ok {
		_spec.SetField(workflownode.FieldUpstreamCodes, field.TypeString, value)
	}
	if wnu.mutation.UpstreamCodesCleared() {
		_spec.ClearField(workflownode.FieldUpstreamCodes, field.TypeString)
	}
	if value, ok := wnu.mutation.TriggerCondition(); ok {
		_spec.SetField(workflownode.FieldTriggerCondition, field.TypeString, value)
	}
	if value, ok := wnu.mutation.FailStrategy(); ok {
		_spec.SetField(workflownode.FieldFailStrategy, field.TypeString, value)
	}
	if value, ok := wnu.mutation.TimeoutMs(); ok {
		_spec.SetField(workflownode.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := wnu.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(workflownode.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := wnu.mutation.SortOrder(); ok {
		_spec.SetField(workflownode.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := wnu.mutation.AddedSortOrder(); ok {
		_spec.AddField(workflownode.FieldSortOrder, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wnu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflownode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wnu.mutation.done = true
	return n, nil
}

// WorkflowNodeUpdateOne is the builder for updating a single WorkflowNode entity.
type WorkflowNodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowNodeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (wnuo *WorkflowNodeUpdateOne) SetUpdatedAt(t time.Time) *WorkflowNodeUpdateOne {
	wnuo.mutation.SetUpdatedAt(t)
	return wnuo
}

// SetDeletedAt sets the "deleted_at" field.
func (wnuo *WorkflowNodeUpdateOne) SetDeletedAt(t time.Time) *WorkflowNodeUpdateOne {
	wnuo.mutation.SetDeletedAt(t)
	return wnuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (wnuo *WorkflowNodeUpdateOne) SetNillableDeletedAt(t *time.Time) *WorkflowNodeUpdateOne {
	if t != nil {
		wnuo.SetDeletedAt(*t)
	}
	return wnuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (wnuo *WorkflowNodeUpdateOne) ClearDeletedAt() *WorkflowNodeUpdateOne {
	wnuo.mutation.ClearDeletedAt()
	return wnuo
}

// SetWorkflowID sets the "workflow_id" field.
func (wnuo *WorkflowNodeUpdateOne) SetWorkflowID(i int64) *WorkflowNodeUpdateOne {
	wnuo.mutation.ResetWorkflowID()
	wnuo.mutation.SetWorkflowID(i)
	return wnuo
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (wnuo *WorkflowNodeUpdateOne) SetNillableWorkflowID(i *int64) *WorkflowNodeUpdateOne {
	if i != nil {
		wnuo.SetWorkflowID(*i)
	}
	return wnuo
}

// AddWorkflowID adds i to the "workflow_id" field.
func (wnuo *WorkflowNodeUpdateOne) AddWorkflowID(i int64) *WorkflowNodeUpdateOne {
	wnuo.mutation.AddWorkflowID(i)
	return wnuo
}

// SetNodeCode sets the "node_code" field.
func (wnuo *WorkflowNodeUpdateOne) SetNodeCode(s string) *WorkflowNodeUpdateOne {
	wnuo.mutation.SetNodeCode(s)
	return wnuo
}

// SetNillableNodeCode sets the "node_code" field if the given value is not nil.
func (wnuo *WorkflowNodeUpdateOne) SetNillableNodeCode(s *string) *WorkflowNodeUpdateOne {
	if s != nil {
		wnuo.SetNodeCode(*s)
	}
	return wnuo
}

// SetNodeName sets the "node_name" field.
func (wnuo *WorkflowNodeUpdateOne) SetNodeName(s string) *WorkflowNodeUpdateOne {
	wnuo.mutation.SetNodeName(s)
	return wnuo
}

// SetNillableNodeName sets the "node_name" field if the given value is not nil.
func (wnuo *WorkflowNodeUpdateOne) SetNillableNodeName(s *string) *WorkflowNodeUpdateOne {
	if s != nil {
		wnuo.SetNodeName(*s)
	}
	return wnuo
}

// SetJobCode sets the "job_code" field.
func (wnuo *WorkflowNodeUpdateOne) SetJobCode(s string) *WorkflowNodeUpdateOne {
	wnuo.mutation.SetJobCode(s)
	return wnuo
}

// SetNillableJobCode sets the "job_code" field if the given value is not nil.
func (wnuo *WorkflowNodeUpdateOne) SetNillableJobCode(s *string) *WorkflowNodeUpdateOne {
	if s != nil {
		wnuo.SetJobCode(*s)
	}
	return wnuo
}

// SetUpstreamCodes sets the "upstream_codes" field.
func (wnuo *WorkflowNodeUpdateOne) SetUpstreamCodes(s string) *WorkflowNodeUpdateOne {
	wnuo.mutation.SetUpstreamCodes(s)
	return wnuo
}

// SetNillableUpstreamCodes sets the "upstream_codes" field if the given value is not nil.
func (wnuo *WorkflowNodeUpdateOne) SetNillableUpstreamCodes(s *string) *WorkflowNodeUpdateOne {
	if s != nil {
		wnuo.SetUpstreamCodes(*s)
	}
	return wnuo
}

// ClearUpstreamCodes clears the value of the "upstream_codes" field.
func (wnuo *WorkflowNodeUpdateOne) ClearUpstreamCodes() *WorkflowNodeUpdateOne {
	wnuo.mutation.ClearUpstreamCodes()
	return wnuo
}

// SetTriggerCondition sets the "trigger_condition" field.
func (wnuo *WorkflowNodeUpdateOne) SetTriggerCondition(s string) *WorkflowNodeUpdateOne {
	wnuo.mutation.SetTriggerCondition(s)
	return wnuo
}

// SetNillableTriggerCondition sets the "trigger_condition" field if the given value is not nil.
func (wnuo *WorkflowNodeUpdateOne) SetNillableTriggerCondition(s *string) *WorkflowNodeUpdateOne {
	if s != nil {
		wnuo.SetTriggerCondition(*s)
	}
	return wnuo
}

// SetFailStrategy sets the "fail_strategy" field.
func (wnuo *WorkflowNodeUpdateOne) SetFailStrategy(s string) *WorkflowNodeUpdateOne {
	wnuo.mutation.SetFailStrategy(s)
	return wnuo
}

// SetNillableFailStrategy sets the "fail_strategy" field if the given value is not nil.
func (wnuo *WorkflowNodeUpdateOne) SetNillableFailStrategy(s *string) *WorkflowNodeUpdateOne {
	if s != nil {
		wnuo.SetFailStrategy(*s)
	}
	return wnuo
}

// SetTimeoutMs sets the "timeout_ms" field.
func (wnuo *WorkflowNodeUpdateOne) SetTimeoutMs(i int) *WorkflowNodeUpdateOne {
	wnuo.mutation.ResetTimeoutMs()
	wnuo.mutation.SetTimeoutMs(i)
	return wnuo
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (wnuo *WorkflowNodeUpdateOne) SetNillableTimeoutMs(i *int) *WorkflowNodeUpdateOne {
	if i != nil {
		wnuo.SetTimeoutMs(*i)
	}
	return wnuo
}

// AddTimeoutMs adds i to the "timeout_ms" field.
func (wnuo *WorkflowNodeUpdateOne) AddTimeoutMs(i int) *WorkflowNodeUpdateOne {
	wnuo.mutation.AddTimeoutMs(i)
	return wnuo
}

// SetSortOrder sets the "sort_order" field.
func (wnuo *WorkflowNodeUpdateOne) SetSortOrder(i int) *WorkflowNodeUpdateOne {
	wnuo.mutation.ResetSortOrder()
	wnuo.mutation.SetSortOrder(i)
	return wnuo
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (wnuo *WorkflowNodeUpdateOne) SetNillableSortOrder(i *int) *WorkflowNodeUpdateOne {
	if i != nil {
		wnuo.SetSortOrder(*i)
	}
	return wnuo
}

// AddSortOrder adds i to the "sort_order" field.
func (wnuo *WorkflowNodeUpdateOne) AddSortOrder(i int) *WorkflowNodeUpdateOne {
	wnuo.mutation.AddSortOrder(i)
	return wnuo
}

// Mutation returns the WorkflowNodeMutation object of the builder.
func (wnuo *WorkflowNodeUpdateOne) Mutation() *WorkflowNodeMutation {
	return wnuo.mutation
}

// Where appends a list predicates to the WorkflowNodeUpdate builder.
func (wnuo *WorkflowNodeUpdateOne) Where(ps ...predicate.WorkflowNode) *WorkflowNodeUpdateOne {
	wnuo.mutation.Where(ps...)
	return wnuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wnuo *WorkflowNodeUpdateOne) Select(field string, fields ...string) *WorkflowNodeUpdateOne {
	wnuo.fields = append([]string{field}, fields...)
	return wnuo
}

// Save executes the query and returns the updated WorkflowNode entity.
func (wnuo *WorkflowNodeUpdateOne) Save(ctx context.Context) (*WorkflowNode, error) {
	wnuo.defaults()
	return withHooks(ctx, wnuo.sqlSave, wnuo.mutation, wnuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wnuo *WorkflowNodeUpdateOne) SaveX(ctx context.Context) *WorkflowNode {
	node, err := wnuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wnuo *WorkflowNodeUpdateOne) Exec(ctx context.Context) error {
	_, err := wnuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wnuo *WorkflowNodeUpdateOne) ExecX(ctx context.Context) {
	if err := wnuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wnuo *WorkflowNodeUpdateOne) defaults() {
	if _, ok := wnuo.mutation.UpdatedAt(); !ok {
		v := workflownode.UpdateDefaultUpdatedAt()
		wnuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wnuo *WorkflowNodeUpdateOne) check() error {
	if v, ok := wnuo.mutation.NodeCode(); ok {
		if err := workflownode.NodeCodeValidator(v); err != nil {
			return &ValidationError{Name: "node_code", err: fmt.Errorf(`ent: validator failed for field "WorkflowNode.node_code": %w`, err)}
		}
	}
	if v, ok := wnuo.mutation.NodeName(); ok {
		if err := workflownode.NodeNameValidator(v); err != nil {
			return &ValidationError{Name: "node_name", err: fmt.Errorf(`ent: validator failed for field "WorkflowNode.node_name": %w`, err)}
		}
	}
	if v, ok := wnuo.mutation.JobCode(); ok {
		if err := workflownode.JobCodeValidator(v); err != nil {
			return &ValidationError{Name: "job_code", err: fmt.Errorf(`ent: validator failed for field "WorkflowNode.job_code": %w`, err)}
		}
	}
	if v, ok := wnuo.mutation.TriggerCondition(); ok {
		if err := workflownode.TriggerConditionValidator(v); err != nil {
			return &ValidationError{Name: "trigger_condition", err: fmt.Errorf(`ent: validator failed for field "WorkflowNode.trigger_condition": %w`, err)}
		}
	}
	if v, ok := wnuo.mutation.FailStrategy(); ok {
		if err := workflownode.FailStrategyValidator(v); err != nil {
			return &ValidationError{Name: "fail_strategy", err: fmt.Errorf(`ent: validator failed for field "WorkflowNode.fail_strategy": %w`, err)}
		}
	}
	return nil
}

func (wnuo *WorkflowNodeUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowNode, err error) {
	if err := wnuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflownode.Table, workflownode.Columns, sqlgraph.NewFieldSpec(workflownode.FieldID, field.TypeInt))
	id, ok := wnuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowNode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wnuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflownode.FieldID)
		for _, f := range fields {
			if !workflownode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflownode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wnuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wnuo.mutation.UpdatedAt(); ok {
		_spec.SetField(workflownode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wnuo.mutation.DeletedAt(); ok {
		_spec.SetField(workflownode.FieldDeletedAt, field.TypeTime, value)
	}
	if wnuo.mutation.DeletedAtCleared() {
		_spec.ClearField(workflownode.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := wnuo.mutation.WorkflowID(); ok {
		_spec.SetField(workflownode.FieldWorkflowID, field.TypeInt64, value)
	}
	if value, ok := wnuo.mutation.AddedWorkflowID(); ok {
		_spec.AddField(workflownode.FieldWorkflowID, field.TypeInt64, value)
	}
	if value, ok := wnuo.mutation.NodeCode(); ok {
		_spec.SetField(workflownode.FieldNodeCode, field.TypeString, value)
	}
	if value, ok := wnuo.mutation.NodeName(); ok {
		_spec.SetField(workflownode.FieldNodeName, field.TypeString, value)
	}
	if value, ok := wnuo.mutation.JobCode(); ok {
		_spec.SetField(workflownode.FieldJobCode, field.TypeString, value)
	}
	if value, ok := wnuo.mutation.UpstreamCodes(); ok {
		_spec.SetField(workflownode.FieldUpstreamCodes, field.TypeString, value)
	}
	if wnuo.mutation.UpstreamCodesCleared() {
		_spec.ClearField(workflownode.FieldUpstreamCodes, field.TypeString)
	}
	if value, ok := wnuo.mutation.TriggerCondition(); ok {
		_spec.SetField(workflownode.FieldTriggerCondition, field.TypeString, value)
	}
	if value, ok := wnuo.mutation.FailStrategy(); ok {
		_spec.SetField(workflownode.FieldFailStrategy, field.TypeString, value)
	}
	if value, ok := wnuo.mutation.TimeoutMs(); ok {
		_spec.SetField(workflownode.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := wnuo.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(workflownode.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := wnuo.mutation.SortOrder(); ok {
		_spec.SetField(workflownode.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := wnuo.mutation.AddedSortOrder(); ok {
		_spec.AddField(workflownode.FieldSortOrder, field.TypeInt, value)
	}
	_node = &WorkflowNode{config: wnuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wnuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflownode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wnuo.mutation.done = true
	return _node, nil
}
