// Code generated by ent, DO NOT EDIT.

package workflowdefinition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldDeletedAt, v))
}

// WorkflowCode applies equality check predicate on the "workflow_code" field. It's identical to WorkflowCodeEQ.
func WorkflowCode(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldWorkflowCode, v))
}

// WorkflowName applies equality check predicate on the "workflow_name" field. It's identical to WorkflowNameEQ.
func WorkflowName(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldWorkflowName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNotNull(FieldDeletedAt))
}

// WorkflowCodeEQ applies the EQ predicate on the "workflow_code" field.
func WorkflowCodeEQ(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldWorkflowCode, v))
}

// WorkflowCodeNEQ applies the NEQ predicate on the "workflow_code" field.
func WorkflowCodeNEQ(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNEQ(FieldWorkflowCode, v))
}

// WorkflowCodeIn applies the In predicate on the "workflow_code" field.
func WorkflowCodeIn(vs ...string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldIn(FieldWorkflowCode, vs...))
}

// WorkflowCodeNotIn applies the NotIn predicate on the "workflow_code" field.
func WorkflowCodeNotIn(vs ...string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNotIn(FieldWorkflowCode, vs...))
}

// WorkflowCodeGT applies the GT predicate on the "workflow_code" field.
func WorkflowCodeGT(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGT(FieldWorkflowCode, v))
}

// WorkflowCodeGTE applies the GTE predicate on the "workflow_code" field.
func WorkflowCodeGTE(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGTE(FieldWorkflowCode, v))
}

// WorkflowCodeLT applies the LT predicate on the "workflow_code" field.
func WorkflowCodeLT(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLT(FieldWorkflowCode, v))
}

// WorkflowCodeLTE applies the LTE predicate on the "workflow_code" field.
func WorkflowCodeLTE(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLTE(FieldWorkflowCode, v))
}

// WorkflowCodeContains applies the Contains predicate on the "workflow_code" field.
func WorkflowCodeContains(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldContains(FieldWorkflowCode, v))
}

// WorkflowCodeHasPrefix applies the HasPrefix predicate on the "workflow_code" field.
func WorkflowCodeHasPrefix(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldHasPrefix(FieldWorkflowCode, v))
}

// WorkflowCodeHasSuffix applies the HasSuffix predicate on the "workflow_code" field.
func WorkflowCodeHasSuffix(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldHasSuffix(FieldWorkflowCode, v))
}

// WorkflowCodeEqualFold applies the EqualFold predicate on the "workflow_code" field.
func WorkflowCodeEqualFold(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEqualFold(FieldWorkflowCode, v))
}

// WorkflowCodeContainsFold applies the ContainsFold predicate on the "workflow_code" field.
func WorkflowCodeContainsFold(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldContainsFold(FieldWorkflowCode, v))
}

// WorkflowNameEQ applies the EQ predicate on the "workflow_name" field.
func WorkflowNameEQ(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldWorkflowName, v))
}

// WorkflowNameNEQ applies the NEQ predicate on the "workflow_name" field.
func WorkflowNameNEQ(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNEQ(FieldWorkflowName, v))
}

// WorkflowNameIn applies the In predicate on the "workflow_name" field.
func WorkflowNameIn(vs ...string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldIn(FieldWorkflowName, vs...))
}

// WorkflowNameNotIn applies the NotIn predicate on the "workflow_name" field.
func WorkflowNameNotIn(vs ...string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNotIn(FieldWorkflowName, vs...))
}

// WorkflowNameGT applies the GT predicate on the "workflow_name" field.
func WorkflowNameGT(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGT(FieldWorkflowName, v))
}

// WorkflowNameGTE applies the GTE predicate on the "workflow_name" field.
func WorkflowNameGTE(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGTE(FieldWorkflowName, v))
}

// WorkflowNameLT applies the LT predicate on the "workflow_name" field.
func WorkflowNameLT(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLT(FieldWorkflowName, v))
}

// WorkflowNameLTE applies the LTE predicate on the "workflow_name" field.
func WorkflowNameLTE(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLTE(FieldWorkflowName, v))
}

// WorkflowNameContains applies the Contains predicate on the "workflow_name" field.
func WorkflowNameContains(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldContains(FieldWorkflowName, v))
}

// WorkflowNameHasPrefix applies the HasPrefix predicate on the "workflow_name" field.
func WorkflowNameHasPrefix(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldHasPrefix(FieldWorkflowName, v))
}

// WorkflowNameHasSuffix applies the HasSuffix predicate on the "workflow_name" field.
func WorkflowNameHasSuffix(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldHasSuffix(FieldWorkflowName, v))
}

// WorkflowNameEqualFold applies the EqualFold predicate on the "workflow_name" field.
func WorkflowNameEqualFold(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEqualFold(FieldWorkflowName, v))
}

// WorkflowNameContainsFold applies the ContainsFold predicate on the "workflow_name" field.
func WorkflowNameContainsFold(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldContainsFold(FieldWorkflowName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkflowDefinition) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkflowDefinition) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkflowDefinition) predicate.WorkflowDefinition {
	return predicate.WorkflowDefinition(sql.NotPredicates(p))
}
