// Code generated by ent, DO NOT EDIT.

package deadletter

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Humphrey-He/star-flow-scheduler/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldDeletedAt, v))
}

// InstanceNo applies equality check predicate on the "instance_no" field. It's identical to InstanceNoEQ.
func InstanceNo(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldInstanceNo, v))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldJobID, v))
}

// DeadReason applies equality check predicate on the "dead_reason" field. It's identical to DeadReasonEQ.
func DeadReason(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldDeadReason, v))
}

// DeadMessage applies equality check predicate on the "dead_message" field. It's identical to DeadMessageEQ.
func DeadMessage(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldDeadMessage, v))
}

// RetrySnapshot applies equality check predicate on the "retry_snapshot" field. It's identical to RetrySnapshotEQ.
func RetrySnapshot(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldRetrySnapshot, v))
}

// LastExecutorID applies equality check predicate on the "last_executor_id" field. It's identical to LastExecutorIDEQ.
func LastExecutorID(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldLastExecutorID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotNull(FieldDeletedAt))
}

// InstanceNoEQ applies the EQ predicate on the "instance_no" field.
func InstanceNoEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldInstanceNo, v))
}

// InstanceNoNEQ applies the NEQ predicate on the "instance_no" field.
func InstanceNoNEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldInstanceNo, v))
}

// InstanceNoIn applies the In predicate on the "instance_no" field.
func InstanceNoIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldInstanceNo, vs...))
}

// InstanceNoNotIn applies the NotIn predicate on the "instance_no" field.
func InstanceNoNotIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldInstanceNo, vs...))
}

// InstanceNoGT applies the GT predicate on the "instance_no" field.
func InstanceNoGT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldInstanceNo, v))
}

// InstanceNoGTE applies the GTE predicate on the "instance_no" field.
func InstanceNoGTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldInstanceNo, v))
}

// InstanceNoLT applies the LT predicate on the "instance_no" field.
func InstanceNoLT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldInstanceNo, v))
}

// InstanceNoLTE applies the LTE predicate on the "instance_no" field.
func InstanceNoLTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldInstanceNo, v))
}

// InstanceNoContains applies the Contains predicate on the "instance_no" field.
func InstanceNoContains(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContains(FieldInstanceNo, v))
}

// InstanceNoHasPrefix applies the HasPrefix predicate on the "instance_no" field.
func InstanceNoHasPrefix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasPrefix(FieldInstanceNo, v))
}

// InstanceNoHasSuffix applies the HasSuffix predicate on the "instance_no" field.
func InstanceNoHasSuffix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasSuffix(FieldInstanceNo, v))
}

// InstanceNoEqualFold applies the EqualFold predicate on the "instance_no" field.
func InstanceNoEqualFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEqualFold(FieldInstanceNo, v))
}

// InstanceNoContainsFold applies the ContainsFold predicate on the "instance_no" field.
func InstanceNoContainsFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContainsFold(FieldInstanceNo, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldJobID, v))
}

// DeadReasonEQ applies the EQ predicate on the "dead_reason" field.
func DeadReasonEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldDeadReason, v))
}

// DeadReasonNEQ applies the NEQ predicate on the "dead_reason" field.
func DeadReasonNEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldDeadReason, v))
}

// DeadReasonIn applies the In predicate on the "dead_reason" field.
func DeadReasonIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldDeadReason, vs...))
}

// DeadReasonNotIn applies the NotIn predicate on the "dead_reason" field.
func DeadReasonNotIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldDeadReason, vs...))
}

// DeadReasonGT applies the GT predicate on the "dead_reason" field.
func DeadReasonGT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldDeadReason, v))
}

// DeadReasonGTE applies the GTE predicate on the "dead_reason" field.
func DeadReasonGTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldDeadReason, v))
}

// DeadReasonLT applies the LT predicate on the "dead_reason" field.
func DeadReasonLT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldDeadReason, v))
}

// DeadReasonLTE applies the LTE predicate on the "dead_reason" field.
func DeadReasonLTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldDeadReason, v))
}

// DeadReasonContains applies the Contains predicate on the "dead_reason" field.
func DeadReasonContains(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContains(FieldDeadReason, v))
}

// DeadReasonHasPrefix applies the HasPrefix predicate on the "dead_reason" field.
func DeadReasonHasPrefix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasPrefix(FieldDeadReason, v))
}

// DeadReasonHasSuffix applies the HasSuffix predicate on the "dead_reason" field.
func DeadReasonHasSuffix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasSuffix(FieldDeadReason, v))
}

// DeadReasonEqualFold applies the EqualFold predicate on the "dead_reason" field.
func DeadReasonEqualFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEqualFold(FieldDeadReason, v))
}

// DeadReasonContainsFold applies the ContainsFold predicate on the "dead_reason" field.
func DeadReasonContainsFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContainsFold(FieldDeadReason, v))
}

// DeadMessageEQ applies the EQ predicate on the "dead_message" field.
func DeadMessageEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldDeadMessage, v))
}

// DeadMessageNEQ applies the NEQ predicate on the "dead_message" field.
func DeadMessageNEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldDeadMessage, v))
}

// DeadMessageIn applies the In predicate on the "dead_message" field.
func DeadMessageIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldDeadMessage, vs...))
}

// DeadMessageNotIn applies the NotIn predicate on the "dead_message" field.
func DeadMessageNotIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldDeadMessage, vs...))
}

// DeadMessageGT applies the GT predicate on the "dead_message" field.
func DeadMessageGT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldDeadMessage, v))
}

// DeadMessageGTE applies the GTE predicate on the "dead_message" field.
func DeadMessageGTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldDeadMessage, v))
}

// DeadMessageLT applies the LT predicate on the "dead_message" field.
func DeadMessageLT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldDeadMessage, v))
}

// DeadMessageLTE applies the LTE predicate on the "dead_message" field.
func DeadMessageLTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldDeadMessage, v))
}

// DeadMessageContains applies the Contains predicate on the "dead_message" field.
func DeadMessageContains(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContains(FieldDeadMessage, v))
}

// DeadMessageHasPrefix applies the HasPrefix predicate on the "dead_message" field.
func DeadMessageHasPrefix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasPrefix(FieldDeadMessage, v))
}

// DeadMessageHasSuffix applies the HasSuffix predicate on the "dead_message" field.
func DeadMessageHasSuffix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasSuffix(FieldDeadMessage, v))
}

// DeadMessageIsNil applies the IsNil predicate on the "dead_message" field.
func DeadMessageIsNil() predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIsNull(FieldDeadMessage))
}

// DeadMessageNotNil applies the NotNil predicate on the "dead_message" field.
func DeadMessageNotNil() predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotNull(FieldDeadMessage))
}

// DeadMessageEqualFold applies the EqualFold predicate on the "dead_message" field.
func DeadMessageEqualFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEqualFold(FieldDeadMessage, v))
}

// DeadMessageContainsFold applies the ContainsFold predicate on the "dead_message" field.
func DeadMessageContainsFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContainsFold(FieldDeadMessage, v))
}

// RetrySnapshotEQ applies the EQ predicate on the "retry_snapshot" field.
func RetrySnapshotEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldRetrySnapshot, v))
}

// RetrySnapshotNEQ applies the NEQ predicate on the "retry_snapshot" field.
func RetrySnapshotNEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldRetrySnapshot, v))
}

// RetrySnapshotIn applies the In predicate on the "retry_snapshot" field.
func RetrySnapshotIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldRetrySnapshot, vs...))
}

// RetrySnapshotNotIn applies the NotIn predicate on the "retry_snapshot" field.
func RetrySnapshotNotIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldRetrySnapshot, vs...))
}

// RetrySnapshotGT applies the GT predicate on the "retry_snapshot" field.
func RetrySnapshotGT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldRetrySnapshot, v))
}

// RetrySnapshotGTE applies the GTE predicate on the "retry_snapshot" field.
func RetrySnapshotGTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldRetrySnapshot, v))
}

// RetrySnapshotLT applies the LT predicate on the "retry_snapshot" field.
func RetrySnapshotLT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldRetrySnapshot, v))
}

// RetrySnapshotLTE applies the LTE predicate on the "retry_snapshot" field.
func RetrySnapshotLTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldRetrySnapshot, v))
}

// RetrySnapshotContains applies the Contains predicate on the "retry_snapshot" field.
func RetrySnapshotContains(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContains(FieldRetrySnapshot, v))
}

// RetrySnapshotHasPrefix applies the HasPrefix predicate on the "retry_snapshot" field.
func RetrySnapshotHasPrefix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasPrefix(FieldRetrySnapshot, v))
}

// RetrySnapshotHasSuffix applies the HasSuffix predicate on the "retry_snapshot" field.
func RetrySnapshotHasSuffix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasSuffix(FieldRetrySnapshot, v))
}

// RetrySnapshotIsNil applies the IsNil predicate on the "retry_snapshot" field.
func RetrySnapshotIsNil() predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIsNull(FieldRetrySnapshot))
}

// RetrySnapshotNotNil applies the NotNil predicate on the "retry_snapshot" field.
func RetrySnapshotNotNil() predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotNull(FieldRetrySnapshot))
}

// RetrySnapshotEqualFold applies the EqualFold predicate on the "retry_snapshot" field.
func RetrySnapshotEqualFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEqualFold(FieldRetrySnapshot, v))
}

// RetrySnapshotContainsFold applies the ContainsFold predicate on the "retry_snapshot" field.
func RetrySnapshotContainsFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContainsFold(FieldRetrySnapshot, v))
}

// LastExecutorIDEQ applies the EQ predicate on the "last_executor_id" field.
func LastExecutorIDEQ(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldLastExecutorID, v))
}

// LastExecutorIDNEQ applies the NEQ predicate on the "last_executor_id" field.
func LastExecutorIDNEQ(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldLastExecutorID, v))
}

// LastExecutorIDIn applies the In predicate on the "last_executor_id" field.
func LastExecutorIDIn(vs ...int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldLastExecutorID, vs...))
}

// LastExecutorIDNotIn applies the NotIn predicate on the "last_executor_id" field.
func LastExecutorIDNotIn(vs ...int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldLastExecutorID, vs...))
}

// LastExecutorIDGT applies the GT predicate on the "last_executor_id" field.
func LastExecutorIDGT(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldLastExecutorID, v))
}

// LastExecutorIDGTE applies the GTE predicate on the "last_executor_id" field.
func LastExecutorIDGTE(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldLastExecutorID, v))
}

// LastExecutorIDLT applies the LT predicate on the "last_executor_id" field.
func LastExecutorIDLT(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldLastExecutorID, v))
}

// LastExecutorIDLTE applies the LTE predicate on the "last_executor_id" field.
func LastExecutorIDLTE(v int64) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldLastExecutorID, v))
}

// LastExecutorIDIsNil applies the IsNil predicate on the "last_executor_id" field.
func LastExecutorIDIsNil() predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIsNull(FieldLastExecutorID))
}

// LastExecutorIDNotNil applies the NotNil predicate on the "last_executor_id" field.
func LastExecutorIDNotNil() predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotNull(FieldLastExecutorID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DeadLetter {
	return predicate.DeadLetter(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeadLetter) predicate.DeadLetter {
	return predicate.DeadLetter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeadLetter) predicate.DeadLetter {
	return predicate.DeadLetter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeadLetter) predicate.DeadLetter {
	return predicate.DeadLetter(sql.NotPredicates(p))
}
