// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type CreateJobRequest struct {
	JobCode           string                 `json:"job_code"`
	JobName           string                 `json:"job_name"`
	JobType           string                 `json:"job_type"`
	ScheduleExpr      *string                `json:"schedule_expr,optional"`
	DelayMs           *int64                 `json:"delay_ms,optional"`
	ExecuteMode       string                 `json:"execute_mode"`
	HandlerName       string                 `json:"handler_name"`
	Payload           map[string]interface{} `json:"payload,optional"`
	TimeoutMs         int                    `json:"timeout_ms,optional"`
	RetryLimit        int                    `json:"retry_limit,optional"`
	RetryBackoff      string                 `json:"retry_backoff,optional"`
	Priority          int                    `json:"priority,optional"`
	ShardTotal        int                    `json:"shard_total,optional"`
	RouteStrategy     string                 `json:"route_strategy,optional"`
	ExecutorTag       *string                `json:"executor_tag,optional"`
	IdempotentKeyExpr *string                `json:"idempotent_key_expr,optional"`
	Status            string                 `json:"status,optional"`
	CreatedBy         *string                `json:"created_by,optional"`
	UpdatedBy         *string                `json:"updated_by,optional"`
}

type CreateJobResponse struct {
	JobId   int64  `json:"job_id"`
	JobCode string `json:"job_code"`
}

type GetJobInstanceRequest struct {
	InstanceNo string `path:"instanceNo"`
}

type GetJobInstanceResponse struct {
	Instance JobInstance `json:"instance"`
}

type GetJobRequest struct {
	JobCode string `path:"jobCode"`
}

type GetJobResponse struct {
	Job JobDefinition `json:"job"`
}

type JobDefinition struct {
	Id                int64   `json:"id"`
	JobCode           string  `json:"job_code"`
	JobName           string  `json:"job_name"`
	JobType           string  `json:"job_type"`
	ScheduleExpr      *string `json:"schedule_expr,optional"`
	DelayMs           *int64  `json:"delay_ms,optional"`
	ExecuteMode       string  `json:"execute_mode"`
	HandlerName       string  `json:"handler_name"`
	HandlerPayload    *string `json:"handler_payload,optional"`
	TimeoutMs         int     `json:"timeout_ms"`
	RetryLimit        int     `json:"retry_limit"`
	RetryBackoff      string  `json:"retry_backoff"`
	Priority          int     `json:"priority"`
	ShardTotal        int     `json:"shard_total"`
	RouteStrategy     string  `json:"route_strategy"`
	ExecutorTag       *string `json:"executor_tag,optional"`
	IdempotentKeyExpr *string `json:"idempotent_key_expr,optional"`
	Status            string  `json:"status"`
	CreatedBy         *string `json:"created_by,optional"`
	UpdatedBy         *string `json:"updated_by,optional"`
	CreatedAt         string  `json:"created_at"`
	UpdatedAt         string  `json:"updated_at"`
}

type JobInstance struct {
	Id             int64   `json:"id"`
	InstanceNo     string  `json:"instance_no"`
	JobId          int64   `json:"job_id"`
	WorkflowId     *int64  `json:"workflow_id,optional"`
	TriggerType    string  `json:"trigger_type"`
	TriggerTime    string  `json:"trigger_time"`
	ScheduledTime  string  `json:"scheduled_time"`
	DispatchTime   *string `json:"dispatch_time,optional"`
	StartTime      *string `json:"start_time,optional"`
	FinishTime     *string `json:"finish_time,optional"`
	Status         string  `json:"status"`
	RetryCount     int     `json:"retry_count"`
	CurrentBackoff int64   `json:"current_backoff_ms"`
	ExecutorId     *int64  `json:"executor_id,optional"`
	ShardTotal     int     `json:"shard_total"`
	SuccessShards  int     `json:"success_shards"`
	FailedShards   int     `json:"failed_shards"`
	Payload        *string `json:"payload,optional"`
	ResultSummary  *string `json:"result_summary,optional"`
	ErrorCode      *string `json:"error_code,optional"`
	ErrorMessage   *string `json:"error_message,optional"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
}

type ListJobInstancesRequest struct {
	JobCode   string `form:"job_code,optional"`
	Status    string `form:"status,optional"`
	StartTime string `form:"start_time,optional"`
	EndTime   string `form:"end_time,optional"`
	Page      int    `form:"page,optional"`
	PageSize  int    `form:"page_size,optional"`
}

type ListJobInstancesResponse struct {
	Items    []JobInstance `json:"items"`
	Total    int           `json:"total"`
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`
}
