CREATE TABLE IF NOT EXISTS job_definitions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  job_code VARCHAR(64) NOT NULL UNIQUE COMMENT 'Task unique code',
  job_name VARCHAR(128) NOT NULL COMMENT 'Task name',
  job_type VARCHAR(32) NOT NULL COMMENT 'cron/delay/once/dag',
  schedule_expr VARCHAR(128) DEFAULT NULL COMMENT 'Cron expression',
  delay_ms BIGINT DEFAULT NULL COMMENT 'Delay in milliseconds',
  execute_mode VARCHAR(32) NOT NULL DEFAULT 'standalone' COMMENT 'standalone/sharding/dag',
  handler_name VARCHAR(128) NOT NULL COMMENT 'Executor handler name',
  handler_payload JSON DEFAULT NULL COMMENT 'Default task payload',
  timeout_ms INT NOT NULL DEFAULT 60000,
  retry_limit INT NOT NULL DEFAULT 3,
  retry_backoff VARCHAR(64) DEFAULT '1s,3s,5s' COMMENT 'Retry backoff settings',
  priority INT NOT NULL DEFAULT 5,
  shard_total INT NOT NULL DEFAULT 1,
  route_strategy VARCHAR(32) NOT NULL DEFAULT 'least_load' COMMENT 'least_load/hash/tag',
  executor_tag VARCHAR(64) DEFAULT NULL COMMENT 'Executor tag',
  idempotent_key_expr VARCHAR(128) DEFAULT NULL COMMENT 'Idempotent key expression',
  status VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT 'enabled/disabled',
  created_by VARCHAR(64) DEFAULT NULL,
  updated_by VARCHAR(64) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_job_type_status (job_type, status),
  INDEX idx_handler_name (handler_name)
);

CREATE TABLE IF NOT EXISTS job_instances (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  instance_no VARCHAR(64) NOT NULL UNIQUE COMMENT 'Instance number',
  job_id BIGINT NOT NULL,
  workflow_id BIGINT DEFAULT NULL COMMENT 'Workflow ID',
  trigger_type VARCHAR(32) NOT NULL COMMENT 'cron/manual/delay/event/retry',
  trigger_time DATETIME NOT NULL COMMENT 'Theoretical trigger time',
  scheduled_time DATETIME NOT NULL COMMENT 'Scheduler enqueue time',
  dispatch_time DATETIME DEFAULT NULL,
  start_time DATETIME DEFAULT NULL,
  finish_time DATETIME DEFAULT NULL,
  status VARCHAR(32) NOT NULL COMMENT 'pending/dispatched/running/success/failed/retry_wait/dead/canceled',
  retry_count INT NOT NULL DEFAULT 0,
  current_backoff_ms BIGINT DEFAULT 0,
  executor_id BIGINT DEFAULT NULL,
  shard_total INT NOT NULL DEFAULT 1,
  success_shards INT NOT NULL DEFAULT 0,
  failed_shards INT NOT NULL DEFAULT 0,
  payload JSON DEFAULT NULL COMMENT 'Runtime payload',
  result_summary VARCHAR(512) DEFAULT NULL,
  error_code VARCHAR(64) DEFAULT NULL,
  error_message VARCHAR(1024) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_job_id_trigger_time (job_id, trigger_time),
  INDEX idx_status_scheduled_time (status, scheduled_time),
  INDEX idx_executor_id_status (executor_id, status)
);

CREATE TABLE IF NOT EXISTS executors (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  executor_code VARCHAR(64) NOT NULL UNIQUE,
  host VARCHAR(128) NOT NULL,
  ip VARCHAR(64) NOT NULL,
  grpc_addr VARCHAR(128) NOT NULL,
  http_addr VARCHAR(128) DEFAULT NULL,
  tags VARCHAR(256) DEFAULT NULL COMMENT 'Comma separated tags',
  capacity INT NOT NULL DEFAULT 100 COMMENT 'Max concurrent slots',
  current_load INT NOT NULL DEFAULT 0,
  version VARCHAR(32) DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'online' COMMENT 'online/offline/draining',
  last_heartbeat_at DATETIME NOT NULL,
  metadata JSON DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_status_heartbeat (status, last_heartbeat_at)
);

CREATE TABLE IF NOT EXISTS job_execution_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  instance_id BIGINT NOT NULL,
  shard_id BIGINT DEFAULT NULL,
  executor_id BIGINT DEFAULT NULL,
  log_level VARCHAR(16) NOT NULL DEFAULT 'INFO',
  phase VARCHAR(32) NOT NULL COMMENT 'dispatch/start/progress/finish/error/retry',
  message VARCHAR(2048) NOT NULL,
  trace_id VARCHAR(64) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_instance_created (instance_id, created_at),
  INDEX idx_trace_id (trace_id)
);
