// Code generated by ent, DO NOT EDIT.

package workflownode

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the workflownode type in the database.
	Label = "workflow_node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldWorkflowID holds the string denoting the workflow_id field in the database.
	FieldWorkflowID = "workflow_id"
	// FieldNodeCode holds the string denoting the node_code field in the database.
	FieldNodeCode = "node_code"
	// FieldNodeName holds the string denoting the node_name field in the database.
	FieldNodeName = "node_name"
	// FieldJobCode holds the string denoting the job_code field in the database.
	FieldJobCode = "job_code"
	// FieldUpstreamCodes holds the string denoting the upstream_codes field in the database.
	FieldUpstreamCodes = "upstream_codes"
	// FieldTriggerCondition holds the string denoting the trigger_condition field in the database.
	FieldTriggerCondition = "trigger_condition"
	// FieldFailStrategy holds the string denoting the fail_strategy field in the database.
	FieldFailStrategy = "fail_strategy"
	// FieldTimeoutMs holds the string denoting the timeout_ms field in the database.
	FieldTimeoutMs = "timeout_ms"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// Table holds the table name of the workflownode in the database.
	Table = "workflow_nodes"
)

// Columns holds all SQL columns for workflownode fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldWorkflowID,
	FieldNodeCode,
	FieldNodeName,
	FieldJobCode,
	FieldUpstreamCodes,
	FieldTriggerCondition,
	FieldFailStrategy,
	FieldTimeoutMs,
	FieldSortOrder,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NodeCodeValidator is a validator for the "node_code" field. It is called by the builders before save.
	NodeCodeValidator func(string) error
	// NodeNameValidator is a validator for the "node_name" field. It is called by the builders before save.
	NodeNameValidator func(string) error
	// JobCodeValidator is a validator for the "job_code" field. It is called by the builders before save.
	JobCodeValidator func(string) error
	// DefaultTriggerCondition holds the default value on creation for the "trigger_condition" field.
	DefaultTriggerCondition string
	// TriggerConditionValidator is a validator for the "trigger_condition" field. It is called by the builders before save.
	TriggerConditionValidator func(string) error
	// DefaultFailStrategy holds the default value on creation for the "fail_strategy" field.
	DefaultFailStrategy string
	// FailStrategyValidator is a validator for the "fail_strategy" field. It is called by the builders before save.
	FailStrategyValidator func(string) error
	// DefaultTimeoutMs holds the default value on creation for the "timeout_ms" field.
	DefaultTimeoutMs int
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
)

// OrderOption defines the ordering options for the WorkflowNode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByWorkflowID orders the results by the workflow_id field.
func ByWorkflowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowID, opts...).ToFunc()
}

// ByNodeCode orders the results by the node_code field.
func ByNodeCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeCode, opts...).ToFunc()
}

// ByNodeName orders the results by the node_name field.
func ByNodeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeName, opts...).ToFunc()
}

// ByJobCode orders the results by the job_code field.
func ByJobCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobCode, opts...).ToFunc()
}

// ByUpstreamCodes orders the results by the upstream_codes field.
func ByUpstreamCodes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamCodes, opts...).ToFunc()
}

// ByTriggerCondition orders the results by the trigger_condition field.
func ByTriggerCondition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerCondition, opts...).ToFunc()
}

// ByFailStrategy orders the results by the fail_strategy field.
func ByFailStrategy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailStrategy, opts...).ToFunc()
}

// ByTimeoutMs orders the results by the timeout_ms field.
func ByTimeoutMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeoutMs, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}
